import type { TimelineCard } from "@/types/content";

export const demoCards: TimelineCard[] = [
  {
    id: "first-gp-appointment",
    slug: "first-gp-appointment",
    title: "First GP appointment",
    subtitle: "The first boring-but-important step",
    card_type: "Big Milestone",
    category: "Pregnancy / Health",
    life_stage: "Pregnancy",
    start_age_days: null,
    end_age_days: null,
    pregnancy_week_start: 6,
    pregnancy_week_end: 8,
    priority: 100,
    time_critical: false,
    short_summary:
      "Book a GP appointment to confirm pregnancy, organise early bloods, discuss supplements and plan the next steps.",
    wish_i_knew:
      "The first appointment is less dramatic than you imagine, but it starts the whole Australian pregnancy pathway.",
    why_it_matters:
      "Your GP can help confirm pregnancy, organise early tests, discuss folate and iodine, talk through public/private care options and refer you into the right pathway.",
    what_to_do_now:
      "Book a GP appointment and bring your estimated last menstrual period or positive pregnancy test date if known.",
    what_can_wait:
      "You do not need to have every hospital or birth decision made before this appointment.",
    checklist_items: [
      "Book a GP appointment",
      "Note your estimated last menstrual period if known",
      "Write down any early questions",
    ],
    shopping_items: [],
    source_urls: ["https://www.pregnancybirthbaby.org.au/your-first-antenatal-visit"],
    source_notes: "Review against current Australian pregnancy guidance before production use.",
    medical_sensitivity: true,
    government_sensitivity: false,
    safety_sensitivity: false,
    allergy_sensitivity: false,
    feeding_sensitivity: false,
    state_specific: false,
    states: [],
    conditions: { unborn_only: true },
    illustration_prompt:
      "A warm illustrated calendar with a tiny positive pregnancy test and coffee cup nearby.",
    image_url: "/card-images/pixel/px-first-gp-appointment.png",
    thumbnail_url: null,
    hero_image_url: null,
    image_alt: "Illustrated calendar with a positive pregnancy test and coffee cup.",
    image_style: "cute 8-bit pixel art item",
    image_status: "approved",
    status: "published",
    review_due_date: "2027-06-25",
    last_reviewed_at: "2026-06-25",
  },
  {
    id: "start-thinking-about-childcare",
    slug: "start-thinking-about-childcare",
    title: "Start thinking about childcare",
    subtitle: "Annoyingly early, but worth it",
    card_type: "Admin Trap",
    category: "Childcare / Planning",
    life_stage: "Pregnancy or early baby",
    start_age_days: 0,
    end_age_days: 90,
    pregnancy_week_start: 24,
    pregnancy_week_end: 40,
    priority: 90,
    time_critical: false,
    short_summary:
      "If you might need childcare, start researching and joining waitlists earlier than feels reasonable.",
    wish_i_knew: "Childcare planning starts before you feel ready to think about childcare.",
    why_it_matters:
      "Popular centres can have long waitlists, and it takes time to compare locations, fees, availability, orientation and Child Care Subsidy.",
    what_to_do_now:
      "Make a shortlist of centres near home and work, ask about nursery availability, and join waitlists if needed.",
    what_can_wait:
      "You do not need your exact return-to-work date locked in before you start researching.",
    checklist_items: [
      "List centres near home and work",
      "Ask about nursery availability",
      "Check waitlist fees",
      "Read the Child Care Subsidy basics",
    ],
    shopping_items: [],
    source_urls: ["https://www.servicesaustralia.gov.au/child-care-subsidy"],
    source_notes: "Review Child Care Subsidy wording before production use.",
    medical_sensitivity: false,
    government_sensitivity: true,
    safety_sensitivity: false,
    allergy_sensitivity: false,
    feeding_sensitivity: false,
    state_specific: false,
    states: [],
    conditions: { childcare_yes_or_unsure: true, first_child_only: true },
    illustration_prompt:
      "A playful illustrated clipboard with tiny blocks, a dummy and a calendar.",
    image_url: "/card-images/pixel/px-start-thinking-about-childcare.png",
    thumbnail_url: null,
    hero_image_url: null,
    image_alt: "Illustrated childcare planning clipboard with blocks, dummy and calendar.",
    image_style: "cute 8-bit pixel art item",
    image_status: "approved",
    status: "published",
    review_due_date: "2027-06-25",
    last_reviewed_at: "2026-06-25",
  },
  {
    id: "two-month-immunisations",
    slug: "two-month-immunisations",
    title: "Two-month immunisations",
    subtitle: "Book it before the week gets away from you",
    card_type: "Big Milestone",
    category: "Health / Immunisations",
    life_stage: "Baby",
    start_age_days: 42,
    end_age_days: 70,
    pregnancy_week_start: null,
    pregnancy_week_end: null,
    priority: 100,
    time_critical: true,
    short_summary:
      "The first major post-birth immunisation appointment comes around quickly.",
    wish_i_knew:
      "Two months sounds far away when they are born, then suddenly it is next week.",
    why_it_matters:
      "The Australian immunisation schedule has key vaccines due in infancy. Booking ahead helps avoid scrambling.",
    what_to_do_now:
      "Check your child's due date for immunisations and book with your GP or provider.",
    what_can_wait:
      "You do not need to understand every vaccine in detail before booking. Your provider can talk you through it.",
    checklist_items: [
      "Check the immunisation schedule",
      "Book with your GP or provider",
      "Add the appointment to your calendar",
    ],
    shopping_items: [],
    source_urls: [
      "https://www.health.gov.au/topics/immunisation/when-to-get-vaccinated/national-immunisation-program-schedule",
    ],
    source_notes: "Review against current National Immunisation Program schedule before production use.",
    medical_sensitivity: true,
    government_sensitivity: false,
    safety_sensitivity: false,
    allergy_sensitivity: false,
    feeding_sensitivity: false,
    state_specific: false,
    states: [],
    conditions: { born_only: true },
    illustration_prompt:
      "A gentle illustrated calendar with a tiny bandage sticker, not a scary needle.",
    image_url: "/card-images/pixel/px-two-month-immunisations.png",
    thumbnail_url: null,
    hero_image_url: null,
    image_alt: "Illustrated calendar with a small bandage sticker.",
    image_style: "cute 8-bit pixel art item",
    image_status: "approved",
    status: "published",
    review_due_date: "2026-12-25",
    last_reviewed_at: "2026-06-25",
  },
  {
    id: "starting-solids",
    slug: "starting-solids",
    title: "Starting solids",
    subtitle: "Cute mess, but also a bit of a project",
    card_type: "Big Milestone",
    category: "Feeding / Solids",
    life_stage: "Baby",
    start_age_days: 120,
    end_age_days: 190,
    pregnancy_week_start: null,
    pregnancy_week_end: null,
    priority: 95,
    time_critical: false,
    short_summary:
      "Solids are about more than purees. You will be thinking about readiness, iron, allergens, textures, mess and routine.",
    wish_i_knew:
      "Starting solids is less about fancy recipes and more about repetition, safety and not losing your mind cleaning the floor.",
    why_it_matters:
      "This stage introduces new skills, flavours and routines. It can feel overwhelming, but you can keep it simple.",
    what_to_do_now:
      "Get a high chair, a few bibs, some easy first foods and learn the basics of choking versus gagging.",
    what_can_wait:
      "You do not need elaborate recipes or a freezer full of tiny gourmet cubes.",
    checklist_items: [
      "Check readiness signs with trusted guidance",
      "Set up a high chair",
      "Get a few easy-clean bibs",
      "Read choking and allergy basics",
    ],
    shopping_items: [],
    source_urls: [
      "https://raisingchildren.net.au/babies/breastfeeding-bottle-feeding-solids/solids-drinks/introducing-solids",
      "https://www.allergy.org.au/patients/allergy-prevention/ascia-how-to-introduce-solid-foods-to-babies",
    ],
    source_notes: "Review feeding, allergy and safety claims before production use.",
    medical_sensitivity: false,
    government_sensitivity: false,
    safety_sensitivity: true,
    allergy_sensitivity: false,
    feeding_sensitivity: true,
    state_specific: false,
    states: [],
    conditions: { born_only: true },
    illustration_prompt: "A cute messy high chair with pumpkin, spoon and bib.",
    image_url: "/card-images/pixel/px-starting-solids.png",
    thumbnail_url: null,
    hero_image_url: null,
    image_alt: "Illustrated messy high chair with pumpkin, spoon and bib.",
    image_style: "cute 8-bit pixel art item",
    image_status: "approved",
    status: "published",
    review_due_date: "2026-12-25",
    last_reviewed_at: "2026-06-25",
  },
  {
    id: "time-for-proper-spoons",
    slug: "time-for-proper-spoons",
    title: "Time for proper spoons",
    subtitle: "Soft-tip baby spoons had a good run",
    card_type: "Tiny Gear Shift",
    category: "Feeding / Gear",
    life_stage: "Baby",
    start_age_days: 320,
    end_age_days: 380,
    pregnancy_week_start: null,
    pregnancy_week_end: null,
    priority: 70,
    time_critical: false,
    short_summary:
      "Your baby may be ready for more normal toddler spoons as they eat thicker food and practise self-feeding.",
    wish_i_knew:
      "Soft-tip baby spoons are great early on, but eventually they can make real food and self-feeding more annoying than helpful.",
    why_it_matters:
      "Around this stage, babies are often eating thicker textures, grabbing the spoon, chewing on utensils and trying to feed themselves. A slightly more normal toddler spoon can make meals easier.",
    what_to_do_now:
      "Buy 2-4 toddler spoons that are small enough for their mouth but sturdier than soft-tip baby spoons.",
    what_can_wait: "You do not need a fancy full cutlery set. A few good spoons are enough.",
    checklist_items: [
      "Check if your current spoons are too shallow or floppy",
      "Buy a small set of toddler spoons",
      "Keep old soft spoons if still useful",
      "Let baby practise holding one spoon while you use another",
    ],
    shopping_items: [],
    source_urls: [],
    source_notes: null,
    medical_sensitivity: false,
    government_sensitivity: false,
    safety_sensitivity: false,
    allergy_sensitivity: false,
    feeding_sensitivity: false,
    state_specific: false,
    states: [],
    conditions: { born_only: true },
    illustration_prompt:
      "A cute illustrated toddler spoon presented like a tiny level-up item.",
    image_url: "/card-images/pixel/px-time-for-proper-spoons.png",
    thumbnail_url: null,
    hero_image_url: null,
    image_alt: "Illustrated toddler spoon presented like a tiny level-up item.",
    image_style: "cute 8-bit pixel art item",
    image_status: "approved",
    status: "published",
    review_due_date: null,
    last_reviewed_at: "2026-06-25",
  },
  {
    id: "daycare-sickness-era",
    slug: "daycare-sickness-era",
    title: "The daycare sickness era",
    subtitle: "Stock up before the first snot wave",
    card_type: "Heads Up",
    category: "Childcare / Illness",
    life_stage: "Baby / Toddler",
    start_age_days: 240,
    end_age_days: 540,
    pregnancy_week_start: null,
    pregnancy_week_end: null,
    priority: 80,
    time_critical: false,
    short_summary:
      "Starting daycare often means more bugs. It helps to have a basic illness setup before everyone is tired and covered in snot.",
    wish_i_knew: "Daycare sickness is not one cold. It is a season of life.",
    why_it_matters: "Having basics ready can make sick days less chaotic.",
    what_to_do_now: "Prepare a simple sick-day kit and know your GP and after-hours options.",
    what_can_wait:
      "You do not need to panic-buy every medicine. Keep it sensible and ask your pharmacist or GP what is appropriate.",
    checklist_items: [
      "Save your GP and after-hours details",
      "Check what your childcare asks parents to do when children are sick",
      "Ask your pharmacist or GP what basics suit your child",
    ],
    shopping_items: [],
    source_urls: ["https://raisingchildren.net.au/guides/a-z-health-reference/colds"],
    source_notes: "Review illness wording before production use.",
    medical_sensitivity: true,
    government_sensitivity: false,
    safety_sensitivity: false,
    allergy_sensitivity: false,
    feeding_sensitivity: false,
    state_specific: false,
    states: [],
    conditions: { born_only: true, childcare_yes_or_unsure: true },
    illustration_prompt:
      "A cute tissue box, thermometer and tiny socks in a warm illustrated style.",
    image_url: "/card-images/pixel/px-daycare-sickness-era.png",
    thumbnail_url: null,
    hero_image_url: null,
    image_alt: "Illustrated tissue box, thermometer and tiny socks.",
    image_style: "cute 8-bit pixel art item",
    image_status: "approved",
    status: "published",
    review_due_date: "2026-12-25",
    last_reviewed_at: "2026-06-25",
  },
];
