-- Wish I Knew content library: pregnancy → 24 months.
-- Run after migrations 001–004 and seed.sql. Safe to re-run (upserts by slug).
-- All content is calm, Australian, and cautious. Sensitive cards carry sources
-- and review dates. Review against current guidance before production use.

insert into public.timeline_cards (
  slug,
  title,
  subtitle,
  card_type,
  category,
  life_stage,
  start_age_days,
  end_age_days,
  pregnancy_week_start,
  pregnancy_week_end,
  priority,
  time_critical,
  short_summary,
  wish_i_knew,
  why_it_matters,
  what_to_do_now,
  what_can_wait,
  checklist_items,
  source_urls,
  source_notes,
  medical_sensitivity,
  government_sensitivity,
  safety_sensitivity,
  allergy_sensitivity,
  feeding_sensitivity,
  conditions,
  illustration_prompt,
  image_url,
  image_alt,
  image_style,
  image_status,
  status,
  last_reviewed_at,
  review_due_date,
  published_at
) values

-- ============================================================
-- PREGNANCY
-- ============================================================
(
  'choose-your-care-pathway',
  'Choose your pregnancy care pathway',
  'Public, private, midwife  -  all real options',
  'Big Milestone',
  'Pregnancy / Planning',
  'Pregnancy',
  null, null, 8, 14, 95, false,
  'Australia has several pregnancy care options: public hospital clinics, midwifery group practice, GP shared care and private obstetricians. Some fill up early.',
  'You choose a care pathway much earlier than you expect  -  and midwife programs can book out by week 12.',
  'Your care pathway shapes who you see, where you give birth and what it costs. Public care is excellent and free with Medicare; midwifery group practice offers continuity but has limited places; private care has out-of-pocket costs and needs obstetric cover on your health insurance well in advance.',
  'Ask your GP about the pathways available at your local hospitals and put your name down for any continuity-of-care programs you like the sound of.',
  'You do not need to have a birth plan, a parenting philosophy or an opinion about water births yet.',
  '["Ask your GP which pathways your local hospitals offer", "Check what your health insurance actually covers (if you have it)", "Register interest in midwifery group practice early if it appeals"]'::jsonb,
  '["https://www.pregnancybirthbaby.org.au/antenatal-care-during-your-pregnancy"]'::jsonb,
  'Review pathway availability wording against current state health guidance before production use.',
  true, false, false, false, false,
  '{"unborn_only": true}'::jsonb,
  'A friendly signpost with three gentle path markers leading toward a soft hospital, a small clinic and a home, warm cream background.',
  '/card-images/pixel/px-choose-your-care-pathway.png',
  'Pixel art signpost with three paths leading to different maternity care options.',
  'cute 8-bit pixel art item',
  'approved', 'in_review', null, null, null
),
(
  'medicare-mygov-setup',
  'Get Medicare and myGov talking',
  'Ten boring minutes that save hours later',
  'Admin Trap',
  'Admin / Government',
  'Pregnancy',
  null, null, 6, 16, 80, false,
  'Almost every pregnancy and baby payment, rebate and record runs through Medicare and myGov. Linking them now makes every later step easier.',
  'Half the paperwork of early parenthood is really just one login you set up while pregnant.',
  'Medicare rebates for appointments and scans, Centrelink payments and your future child''s immunisation records all flow through myGov. Doing the linking while you can still concentrate is a gift to your future self.',
  'Log in to myGov, link Medicare and Centrelink, and check your bank details are current with both.',
  'Any actual claims. This step is just plumbing  -  the payments come later.',
  '["Create or dust off your myGov account", "Link Medicare and Centrelink services", "Check your name, address and bank details are current"]'::jsonb,
  '["https://www.servicesaustralia.gov.au/mygov"]'::jsonb,
  'Government service wording  -  review against current Services Australia guidance before production use.',
  false, true, false, false, false,
  '{"unborn_only": true}'::jsonb,
  'A friendly folder with a gum leaf sticker, a small green-and-gold service card shape and a tiny padlock, organised and calm, warm cream background.',
  '/card-images/pixel/px-medicare-mygov-setup.png',
  'Pixel art folder with a service card and padlock representing linked government accounts.',
  'cute 8-bit pixel art item',
  'approved', 'in_review', null, null, null
),
(
  'early-pregnancy-screening-choices',
  'Early screening: your call, no rush panic',
  'Options exist  -  and optional means optional',
  'Heads Up',
  'Pregnancy / Health',
  'Pregnancy',
  null, null, 9, 13, 85, false,
  'First-trimester screening options (like combined screening and NIPT) have a timing window. Your GP or midwife can explain what each one does and costs.',
  'Screening tests are optional, some have out-of-pocket costs, and the window comes around faster than expected.',
  'Some screening happens in a specific week range, so it helps to have the conversation early rather than discover the window has closed. There is no right answer  -  only what is right for you.',
  'Ask your GP or midwife which screening options are available, what they cost and when they need to happen.',
  'Deciding instantly. You can take the information away and think about it  -  that is completely normal.',
  '["Ask about screening options at your next appointment", "Check timing windows and any out-of-pocket costs", "Take time to decide  -  optional means optional"]'::jsonb,
  '["https://www.pregnancybirthbaby.org.au/screening-tests-during-pregnancy"]'::jsonb,
  'Medical content  -  review against current RANZCOG and state guidance before production use.',
  true, false, false, false, false,
  '{"unborn_only": true}'::jsonb,
  'A gentle calendar page with a soft question-mark bubble and a friendly clipboard, no medical fear, teal and cream palette.',
  '/card-images/pixel/px-early-pregnancy-screening-choices.png',
  'Pixel art calendar and clipboard representing optional pregnancy screening choices.',
  'cute 8-bit pixel art item',
  'approved', 'in_review', null, null, null
),
(
  'morphology-scan-window',
  'The 20-week scan',
  'The long look at how bub is growing',
  'Big Milestone',
  'Pregnancy / Health',
  'Pregnancy',
  null, null, 17, 21, 90, false,
  'The morphology (anatomy) scan usually happens between 18 and 21 weeks. It is longer than earlier scans and needs booking ahead in many areas.',
  'The 20-week scan books out  -  organising it at week 16 beats scrambling at week 19.',
  'This scan checks how your baby is developing and where the placenta sits. Imaging clinics in busy areas can have waits, so booking early keeps the timing comfortable.',
  'Book the scan for the window your care provider recommends, and ask whether you need a referral.',
  'You do not need to decide whether to find out the sex until you are in the room.',
  '["Get the referral from your GP, midwife or clinic", "Book the scan for the recommended window", "Decide (or happily not decide) about finding out the sex"]'::jsonb,
  '["https://www.pregnancybirthbaby.org.au/morphology-scan"]'::jsonb,
  'Medical content  -  review against current guidance before production use.',
  true, false, false, false, false,
  '{"unborn_only": true}'::jsonb,
  'A cosy ultrasound picture frame with a tiny star and soft sparkles, warm and exciting, not clinical, cream background.',
  '/card-images/pixel/px-morphology-scan-window.png',
  'Pixel art framed ultrasound picture with a small star, warm and friendly.',
  'cute 8-bit pixel art item',
  'approved', 'in_review', null, null, null
),
(
  'whooping-cough-booster-pregnancy',
  'Whooping cough booster in pregnancy',
  'One jab that protects bub before day one',
  'Heads Up',
  'Pregnancy / Health',
  'Pregnancy',
  null, null, 20, 32, 92, false,
  'A whooping cough (pertussis) booster is recommended in every pregnancy, usually between 20 and 32 weeks. It is free under the National Immunisation Program.',
  'The booster you get while pregnant is what protects your newborn in the gap before their own vaccines start.',
  'Newborns cannot be vaccinated against whooping cough until six weeks old. Your booster passes protection across before birth. Partners and close family may also be advised to update theirs.',
  'Mention the booster at your next appointment and book it into the recommended window. Ask whether household adults should update theirs too.',
  'Perfect timing debates. Anywhere your provider recommends inside the window is a win.',
  '["Book the booster with your GP, midwife or pharmacy", "Ask whether partners and grandparents need an update", "Ask about the flu vaccine at the same visit"]'::jsonb,
  '["https://www.health.gov.au/topics/immunisation/when-to-get-vaccinated/immunisation-for-pregnancy"]'::jsonb,
  'Medical content  -  review against current National Immunisation Program guidance before production use.',
  true, false, false, false, false,
  '{"unborn_only": true}'::jsonb,
  'A gentle shield with a small heart and a friendly bandage sticker, protective and warm, no needles, teal and coral accents.',
  '/card-images/pixel/px-whooping-cough-booster-pregnancy.png',
  'Pixel art shield with a heart and bandage sticker representing vaccination protection.',
  'cute 8-bit pixel art item',
  'approved', 'in_review', null, null, null
),
(
  'parental-leave-pay-groundwork',
  'Parental Leave Pay groundwork',
  'You can claim before bub arrives',
  'Admin Trap',
  'Money / Government',
  'Pregnancy',
  null, null, 22, 34, 85, false,
  'Government Parental Leave Pay claims can be lodged up to three months before your baby is due. Employer leave also usually needs formal notice.',
  'You can start the Parental Leave Pay claim while pregnant  -  and your employer usually needs about ten weeks'' written notice.',
  'Doing the claim early means the payment side is mostly sorted before the sleep deprivation starts. Eligibility rules involve work history and income, so it is worth checking rather than assuming either way.',
  'Check your eligibility on the Services Australia site, start the claim in myGov, and give your employer written notice of your leave dates.',
  'Finalising the claim. It completes after birth when you confirm the details  -  starting it is the win.',
  '["Check Parental Leave Pay eligibility", "Start the claim in myGov (up to 3 months early)", "Give your employer written notice of leave dates", "Ask your employer about their own paid leave scheme"]'::jsonb,
  '["https://www.servicesaustralia.gov.au/parental-leave-pay"]'::jsonb,
  'Government payment wording  -  review against current Services Australia guidance before production use.',
  false, true, false, false, false,
  '{"unborn_only": true}'::jsonb,
  'A friendly envelope with a small coin, a calendar sticker and tiny baby socks beside it, organised and hopeful, cream and navy palette.',
  '/card-images/pixel/px-parental-leave-pay-groundwork.png',
  'Pixel art envelope with a coin and calendar representing parental leave payments.',
  'cute 8-bit pixel art item',
  'approved', 'in_review', null, null, null
),
(
  'car-seat-sorted-before-birth',
  'Car seat sorted before the hospital bag',
  'The one thing you truly need on day one',
  'Big Milestone',
  'Safety / Gear',
  'Pregnancy',
  null, null, 30, 37, 98, false,
  'You need an approved rear-facing infant restraint fitted before you can drive your baby anywhere  -  including home from hospital.',
  'The car seat is the only piece of gear you genuinely cannot leave hospital without.',
  'Australian law requires an approved child restraint from the very first drive. Fitting one properly takes longer than expected, and professional fitting services exist in most areas.',
  'Buy or borrow an Australian-standard (AS/NZS 1754) rear-facing restraint and get it fitted  -  professionally if you can, or carefully using the manual and an anchor point.',
  'The pram, the nursery theme, the wardrobe. None of that is needed for the drive home.',
  '["Choose an AS/NZS 1754 approved rear-facing restraint", "Book a professional fitting or fit it carefully yourself", "Do a practice buckle with a teddy  -  genuinely helpful"]'::jsonb,
  '["https://www.kidsafe.com.au/child-car-seats/"]'::jsonb,
  'Safety content  -  review against current Kidsafe and state road authority guidance before production use.',
  false, false, true, false, false,
  '{"unborn_only": true}'::jsonb,
  'A cute rear-facing baby capsule with a soft glow and small sparkle, sturdy and reassuring, teal and sunshine yellow accents.',
  '/card-images/pixel/px-car-seat-sorted-before-birth.png',
  'Pixel art rear-facing baby car seat with a gentle sparkle.',
  'cute 8-bit pixel art item',
  'approved', 'in_review', null, null, null
),
(
  'hospital-bag-and-plan-b',
  'Hospital bag and the flexible plan',
  'Packed-ish beats perfect',
  'Heads Up',
  'Pregnancy / Planning',
  'Pregnancy',
  null, null, 32, 38, 75, false,
  'A mostly-packed bag from around 34 weeks covers you. Babies keep their own schedules, and flexible plans hold up better than detailed ones.',
  'The bag matters less than knowing how you will get to the hospital at 3am and who is watching the dog.',
  'Late pregnancy is easier when the logistics are boring and settled: transport, contact numbers, who to call, where the bags sit. Birth plans work best as preferences, not scripts.',
  'Pack the essentials, write your preferences down loosely, and sort the 3am logistics: transport, parking, phone chargers, other kids or pets.',
  'Packing for every scenario. Hospitals have supplies, and someone can always bring the forgotten thing.',
  '["Pack the bag to 80% done", "Sort transport and parking for any hour", "Save the hospital and care provider numbers in both phones", "Write preferences down  -  loosely"]'::jsonb,
  '["https://www.pregnancybirthbaby.org.au/what-to-pack-for-hospital-or-birth-centre"]'::jsonb,
  null,
  false, false, false, false, false,
  '{"unborn_only": true}'::jsonb,
  'A cosy open overnight bag with tiny baby socks, a phone charger and a small toiletries pouch, warm lamplight mood, cream background.',
  '/card-images/pixel/px-hospital-bag-and-plan-b.png',
  'Pixel art overnight hospital bag with baby socks and a phone charger.',
  'cute 8-bit pixel art item',
  'approved', 'published', current_date, current_date + interval '12 months', now()
),
(
  'safe-sleep-setup',
  'Set up safe sleep before bub arrives',
  'Simple rules, calm nights',
  'Heads Up',
  'Safety / Sleep',
  'Pregnancy',
  null, null, 30, 39, 96, false,
  'Safe sleep in Australia follows Red Nose guidance: baby on their back, in their own safe space, flat firm mattress, no loose bedding, face uncovered, smoke-free.',
  'Safe sleep is a short list of rules, not a catalogue of products  -  and most sleep gadgets are not on the list.',
  'Setting up the bassinet or cot to Red Nose guidelines before the birth means 3am decisions are already made. Many heavily-marketed sleep products do not meet safe sleep guidance.',
  'Set up a safe sleep space to Australian standards: firm flat mattress, fitted sheet, nothing loose in the cot, in your room for the first six months if possible.',
  'Buying sleep aids, positioners, cot bumpers or wedges  -  safe sleep guidance says skip them.',
  '["Set up a cot or bassinet meeting Australian standards", "Firm flat mattress, fitted sheet, nothing else in the bed", "Read the Red Nose safe sleep basics once now"]'::jsonb,
  '["https://rednose.org.au/section/safe-sleeping"]'::jsonb,
  'Safety content  -  review against current Red Nose guidance before production use.',
  false, false, true, false, false,
  '{"unborn_only": true}'::jsonb,
  'A calm cot with a firm flat mattress and fitted sheet under gentle moonlight, a small moon and star above, peaceful and uncluttered.',
  '/card-images/pixel/px-safe-sleep-setup.png',
  'Pixel art cot with a flat mattress under a gentle moon, representing safe sleep.',
  'cute 8-bit pixel art item',
  'approved', 'in_review', null, null, null
),

-- ============================================================
-- NEWBORN (0–3 months)
-- ============================================================
(
  'register-birth-and-medicare',
  'Register the birth, add bub to Medicare',
  'The paperwork that unlocks everything else',
  'Admin Trap',
  'Admin / Government',
  'Newborn',
  0, 60, null, null, 100, true,
  'Registering the birth with your state registry and adding your baby to Medicare unlocks almost everything else: payments, immunisations, doctor visits.',
  'Nothing else in the system works until the birth is registered and bub is on Medicare  -  and the hospital paperwork is only step one.',
  'Birth registration is free and done through your state registry (the hospital gives you the forms or a link). Medicare enrolment usually rides along with it or happens via myGov. Payments and immunisation records need both.',
  'Do the birth registration as soon as the fog allows, then confirm your baby appears on your Medicare card in myGov.',
  'The birth certificate order can wait a little  -  but registration itself should not.',
  '["Complete birth registration with your state registry", "Add bub to Medicare (often part of the same flow)", "Check your Medicare card shows the new name in myGov"]'::jsonb,
  '["https://www.servicesaustralia.gov.au/enrolling-your-baby-medicare"]'::jsonb,
  'Government process wording  -  review against current state registry and Services Australia guidance before production use.',
  false, true, false, false, false,
  '{"born_only": true}'::jsonb,
  'A friendly certificate scroll with a tiny footprint stamp and a green service card shape beside it, official but warm, cream background.',
  '/card-images/pixel/px-register-birth-and-medicare.png',
  'Pixel art birth certificate scroll with a tiny footprint and Medicare-style card.',
  'cute 8-bit pixel art item',
  'approved', 'in_review', null, null, null
),
(
  'centrelink-claims-after-birth',
  'Finish the Centrelink claims',
  'The money side, wrapped up',
  'Admin Trap',
  'Money / Government',
  'Newborn',
  0, 90, null, null, 88, false,
  'After the birth is registered, you can finalise Parental Leave Pay and check Family Tax Benefit eligibility. Both run through myGov.',
  'The claims you started (or meant to start) while pregnant only finish after you confirm the birth  -  and Family Tax Benefit is a separate thing worth checking.',
  'Parental Leave Pay completes once the birth is confirmed. Family Tax Benefit is income-tested and separate; plenty of families are eligible without realising. Backdating rules exist but are kinder the sooner you claim.',
  'Confirm the birth in your myGov claims, finalise Parental Leave Pay, and run the Family Tax Benefit eligibility check.',
  'Understanding every payment type in the system. Just these two are the core.',
  '["Confirm the birth in myGov", "Finalise the Parental Leave Pay claim", "Check Family Tax Benefit eligibility"]'::jsonb,
  '["https://www.servicesaustralia.gov.au/family-tax-benefit"]'::jsonb,
  'Government payment wording  -  review against current Services Australia guidance before production use.',
  false, true, false, false, false,
  '{"born_only": true}'::jsonb,
  'A small piggy bank with a gum leaf sticker and a friendly completed checklist beside it, relieved and organised mood, cream and teal.',
  '/card-images/pixel/px-centrelink-claims-after-birth.png',
  'Pixel art piggy bank and completed checklist representing finished payment claims.',
  'cute 8-bit pixel art item',
  'approved', 'in_review', null, null, null
),
(
  'child-health-checks-book',
  'Your baby book and free health checks',
  'The little book that runs the first year',
  'Aussie System',
  'Health / Checks',
  'Newborn',
  0, 42, null, null, 82, false,
  'Every state gives you a child health record book (blue, red, green  -  colours vary) and a schedule of free child health nurse checks. They are genuinely useful.',
  'The child health nurse visits are free, unhurried, and one of the few places you can ask every "is this normal?" question in one sitting.',
  'The book tracks growth, immunisations and milestones, and the nurse checks catch things early while reassuring you about the rest. Bring the book to every appointment  -  GPs and hospitals use it too.',
  'Book the first child health nurse visit for your area and keep the book somewhere you can actually find it.',
  'Filling in every page. The health professionals fill the important parts; the baby-photo pages are optional joy.',
  '["Book the first child and family health nurse visit", "Keep the health record book with the nappy bag", "Write questions in your phone as they occur to you"]'::jsonb,
  '["https://www.pregnancybirthbaby.org.au/baby-health-checks"]'::jsonb,
  'Check schedules vary by state  -  review wording before production use.',
  true, false, false, false, false,
  '{"born_only": true}'::jsonb,
  'A cute health record book with a tiny growth chart sticker and a friendly stethoscope draped nearby, trusted and local, gum green accents.',
  '/card-images/pixel/px-child-health-checks-book.png',
  'Pixel art child health record book with a growth chart and stethoscope.',
  'cute 8-bit pixel art item',
  'approved', 'in_review', null, null, null
),
(
  'feeding-help-exists',
  'Feeding help exists  -  and it is free',
  'However you feed, support is a call away',
  'Parent Sanity',
  'Feeding / Support',
  'Newborn',
  0, 60, null, null, 84, false,
  'Feeding is rarely instinctive for anyone at the start. Free support exists: the ABA helpline, lactation consultants, child health nurses and your GP  -  for any feeding style.',
  'Feeding help is not just for emergencies, and asking early is normal  -  not a sign something is wrong.',
  'Whether breastfeeding, formula feeding, pumping or mixing, the early weeks come with questions. The Australian Breastfeeding Association helpline (1800 686 268) runs 24/7, and child health nurses help with all feeding styles without judgement.',
  'Save the ABA helpline number now, and raise any feeding questions at your child health nurse visit  -  none are too small.',
  'Having feeding sorted. Almost nobody does in the first weeks, whatever the photos suggest.',
  '["Save the ABA helpline: 1800 686 268", "Ask feeding questions at nurse visits  -  all of them", "Remember fed, safe and supported is the goal"]'::jsonb,
  '["https://www.breastfeeding.asn.au/", "https://www.pregnancybirthbaby.org.au/feeding-your-baby"]'::jsonb,
  'Feeding content  -  keep wording inclusive of all feeding methods. Review before production use.',
  false, false, false, false, true,
  '{"born_only": true}'::jsonb,
  'A warm phone with a heart on screen next to a baby bottle and a soft cushion, supportive midnight-lamp mood, jacaranda and cream palette.',
  '/card-images/pixel/px-feeding-help-exists.png',
  'Pixel art phone with a heart beside a baby bottle, representing feeding support.',
  'cute 8-bit pixel art item',
  'approved', 'in_review', null, null, null
),
(
  'crying-peaks-and-coping',
  'Crying peaks around week six',
  'It is a phase with a shape, not a verdict',
  'Parent Sanity',
  'Development / Coping',
  'Newborn',
  14, 90, null, null, 90, false,
  'Infant crying typically increases from two weeks, peaks around six to eight weeks, then eases. It is developmental, it is not your fault, and there are safe ways through the hard moments.',
  'The crying peak is a known, temporary pattern  -  and putting a safe baby down to take a breather is good parenting, not failure.',
  'Knowing the shape of the curve helps at 2am. If it ever feels like too much: put baby safely in the cot on their back, step away, breathe. Never shake a baby. If you are worried about the crying or about yourself, your GP, health nurse or PANDA (1300 726 306) are there.',
  'Save the PANDA number, tell your support people about the six-week peak, and agree on a tag-out signal for the hard evenings.',
  'Fixing the crying. Some crying in this window has no fixable cause  -  comfort, safety and shifts are the strategy.',
  '["Know the curve: rises at 2 weeks, peaks 6–8, eases after", "Safe cot + step away is always an option", "Save PANDA: 1300 726 306", "Agree tag-out shifts with your support people"]'::jsonb,
  '["https://www.pregnancybirthbaby.org.au/crying-baby", "https://panda.org.au/"]'::jsonb,
  'Sensitive coping content  -  review wording with clinical guidance before production use.',
  true, false, true, false, false,
  '{"born_only": true}'::jsonb,
  'A gentle moon above a calm cot and an armchair with a warm cup of tea, quiet exhale mood, soft navy and jacaranda night palette.',
  '/card-images/pixel/px-crying-peaks-and-coping.png',
  'Pixel art moonlit cot and armchair with tea, representing calm during the crying peak.',
  'cute 8-bit pixel art item',
  'approved', 'in_review', null, null, null
),
(
  'four-month-immunisations',
  'Four-month immunisations',
  'Round two  -  you know the drill now',
  'Big Milestone',
  'Health / Immunisations',
  'Baby',
  100, 140, null, null, 96, true,
  'The four-month round of the National Immunisation Program is due. Same idea as two months  -  book ahead so the week does not get away from you.',
  'The second round sneaks up faster than the first because now you are busier and more tired.',
  'Staying roughly on schedule keeps protection building as maternal antibodies fade. GPs, council clinics and some pharmacies run immunisation appointments; the visit is quick.',
  'Book the four-month appointment now, and plan a quiet rest-of-day for bub (and you).',
  'Worrying about mild post-vaccine grizzles  -  a clingy 24 hours is common and okay. Call your provider if anything concerns you.',
  '["Book the 4-month immunisation visit", "Bring the child health record book", "Plan a gentle rest-of-day afterwards"]'::jsonb,
  '["https://www.health.gov.au/topics/immunisation/when-to-get-vaccinated/national-immunisation-program-schedule"]'::jsonb,
  'Review against current National Immunisation Program schedule before production use.',
  true, false, false, false, false,
  '{"born_only": true}'::jsonb,
  'A friendly calendar with a small bandage sticker and a tiny gold star, second-time-around confidence, teal and sun yellow accents.',
  '/card-images/pixel/px-four-month-immunisations.png',
  'Pixel art calendar with bandage sticker and gold star for the four-month immunisations.',
  'cute 8-bit pixel art item',
  'approved', 'in_review', null, null, null
),
(
  'four-month-sleep-shakeup',
  'The four-month sleep shake-up',
  'Not broken  -  upgrading',
  'Parent Sanity',
  'Sleep / Development',
  'Baby',
  100, 170, null, null, 70, false,
  'Around four months, babies'' sleep cycles mature and previously fine sleep can go sideways. It is a development leap, not a regression in the failure sense.',
  'The "four-month sleep regression" is really baby sleep growing up  -  which is why none of the old tricks suddenly work.',
  'Baby sleep architecture permanently changes around now: more wakeful phases between cycles. It is common, temporary in intensity, and not caused by anything you did. Consistent, boring bedtime rhythms help more than any product.',
  'Lower expectations for a few weeks, keep the safe sleep basics steady, and split nights with your support people if you can.',
  'Sleep training decisions, expensive sleep aids, or reading seventeen conflicting books at 3am.',
  '["Expect bumpier sleep for a few weeks around now", "Keep bedtime rhythm boring and consistent", "Split the nights where possible", "Safe sleep rules stay the same"]'::jsonb,
  '["https://raisingchildren.net.au/babies/sleep/understanding-sleep/sleep-3-6-months"]'::jsonb,
  null,
  false, false, false, false, false,
  '{"born_only": true}'::jsonb,
  'A sweet moon wearing a tiny level-up arrow, clouds and stars rearranging themselves, gentle humour, soft night navy palette.',
  '/card-images/pixel/px-four-month-sleep-shakeup.png',
  'Pixel art moon with a level-up arrow among rearranging stars, for changing baby sleep.',
  'cute 8-bit pixel art item',
  'approved', 'published', current_date, current_date + interval '12 months', now()
),

-- ============================================================
-- BABY (3–12 months)
-- ============================================================
(
  'six-month-immunisations',
  'Six-month immunisations',
  'Round three of the early set',
  'Big Milestone',
  'Health / Immunisations',
  'Baby',
  165, 215, null, null, 96, true,
  'The six-month round of the National Immunisation Program is due  -  the last of the tight early series before a breather until twelve months.',
  'After six months there is a gap in the schedule  -  this round closes out the intensive early set.',
  'The six-month vaccines complete several primary courses. Timeliness keeps protection strong through the crawling-and-licking-everything era that is about to begin.',
  'Book the six-month visit, bring the health record book, and enjoy that the next round is not until the first birthday.',
  'Nothing here needs to be perfect  -  a week or two either side is normal life. Just book it.',
  '["Book the 6-month immunisation visit", "Bring the child health record book", "Note: next round is at 12 months"]'::jsonb,
  '["https://www.health.gov.au/topics/immunisation/when-to-get-vaccinated/national-immunisation-program-schedule"]'::jsonb,
  'Review against current National Immunisation Program schedule before production use.',
  true, false, false, false, false,
  '{"born_only": true}'::jsonb,
  'A calendar with three friendly bandage stickers in a row and a small trophy, completing-the-set feeling, teal and cream.',
  '/card-images/pixel/px-six-month-immunisations.png',
  'Pixel art calendar with three bandage stickers and a trophy for the six-month round.',
  'cute 8-bit pixel art item',
  'approved', 'in_review', null, null, null
),
(
  'introducing-allergens-early',
  'Introducing allergens: early and ongoing',
  'Peanut and egg in year one  -  on purpose',
  'Heads Up',
  'Feeding / Allergy',
  'Baby',
  165, 300, null, null, 88, false,
  'Australian allergy guidance recommends introducing common allergens (including peanut and cooked egg) in the first year, once solids are going, and keeping them in the diet regularly.',
  'The advice flipped a generation ago: introducing allergens early  -  not avoiding them  -  is what current Australian guidance recommends.',
  'ASCIA and the "Nip Allergies in the Bub" program recommend common allergens in age-appropriate forms (smooth peanut butter, well-cooked egg) around six months and not later than twelve, then regularly. Families with eczema or existing allergies should chat to their GP about the best approach first.',
  'Read the Nip Allergies in the Bub introduction guide, and plan allergens one at a time, early in the day, in age-safe forms.',
  'Rushing every allergen at once. One at a time, a few days apart, is the calm way through the list.',
  '["Read the Nip Allergies in the Bub guide", "One new allergen at a time, early in the day", "Keep introduced allergens in the rotation", "GP first if bub has eczema or known allergies"]'::jsonb,
  '["https://preventallergies.org.au/", "https://www.allergy.org.au/patients/allergy-prevention"]'::jsonb,
  'Allergy content  -  review against current ASCIA guidance before production use.',
  true, false, false, true, true,
  '{"born_only": true}'::jsonb,
  'A cheerful little bowl of smooth peanut butter and a soft-boiled egg with tiny sparkles, brave and positive food mood, coral and yellow accents.',
  '/card-images/pixel/px-introducing-allergens-early.png',
  'Pixel art bowl of peanut butter and a cooked egg with sparkles, for early allergen introduction.',
  'cute 8-bit pixel art item',
  'approved', 'in_review', null, null, null
),
(
  'baby-proofing-before-crawling',
  'Baby-proof before the crawling starts',
  'They get mobile overnight  -  literally',
  'Heads Up',
  'Safety / Home',
  'Baby',
  180, 280, null, null, 86, false,
  'Crawling tends to arrive suddenly somewhere around six to ten months. The easiest time to baby-proof is before you need it.',
  'You do not get a warning week  -  one day they are stationary, the next they are behind the TV.',
  'The big-ticket items are furniture anchoring (bookshelves and drawers tip), power points, blind cords, cleaning chemicals, medicines and stairs. A crawl around your own floor reveals more than any checklist.',
  'Anchor tip-risk furniture, move chemicals and medicines up high, cover points in reach and check blind cords  -  then literally crawl the house at baby height.',
  'The full fortress. Doors, fireplace and pool-level things matter at walking; this round is about the floor world.',
  '["Anchor bookshelves, drawers and the TV", "Chemicals and medicines up high or locked", "Check blind and curtain cords", "Crawl the house at baby height once"]'::jsonb,
  '["https://www.kidsafe.com.au/home-safety/"]'::jsonb,
  'Safety content  -  review against current Kidsafe guidance before production use.',
  false, false, true, false, false,
  '{"born_only": true}'::jsonb,
  'A sturdy bookshelf with a friendly anchor strap and a small padlock badge, protective level-up feeling, navy and gum green accents.',
  '/card-images/pixel/px-baby-proofing-before-crawling.png',
  'Pixel art anchored bookshelf with a strap and padlock badge, for baby-proofing.',
  'cute 8-bit pixel art item',
  'approved', 'in_review', null, null, null
),
(
  'child-care-subsidy-paperwork',
  'Child Care Subsidy before the first day',
  'The CCS approval is the slow bit',
  'Admin Trap',
  'Childcare / Money',
  'Baby',
  180, 330, null, null, 87, false,
  'If childcare is on the horizon, the Child Care Subsidy claim through myGov should happen well before the first day  -  approval takes time and it is not automatic.',
  'The CCS is not applied magically by the childcare centre  -  you claim it yourself, and unclaimed weeks can cost real money.',
  'The subsidy is income-tested and substantial for many families. You claim through Centrelink in myGov, then confirm enrolment details once the centre lodges theirs. Doing it early avoids paying full fees while approval catches up.',
  'Start the CCS claim in myGov, and once your centre offers a place, confirm the enrolment when it appears in your account.',
  'Choosing final days and sessions  -  estimates are fine for the claim; details firm up with the centre later.',
  '["Start the Child Care Subsidy claim in myGov", "Have income estimates ready", "Confirm the enrolment notice when the centre lodges it"]'::jsonb,
  '["https://www.servicesaustralia.gov.au/child-care-subsidy"]'::jsonb,
  'Government payment wording  -  review against current Services Australia guidance before production use.',
  false, true, false, false, false,
  '{"born_only": true, "childcare_yes_or_unsure": true}'::jsonb,
  'A tiny childcare backpack next to a friendly approved-stamp document, ready-for-the-first-day feeling, teal and coral accents.',
  '/card-images/pixel/px-child-care-subsidy-paperwork.png',
  'Pixel art childcare backpack beside an approved document, for the Child Care Subsidy.',
  'cute 8-bit pixel art item',
  'approved', 'in_review', null, null, null
),
(
  'water-safety-around-babies',
  'Water safety: the quiet rule',
  'Arm''s reach, always  -  everything else is bonus',
  'Heads Up',
  'Safety / Water',
  'Baby',
  240, 420, null, null, 92, false,
  'Babies and toddlers can drown quickly and silently in very little water  -  baths, pools, buckets, ponds, dams. Active adult supervision within arm''s reach is the core rule.',
  'Drowning is silent  -  the splashing-and-shouting version is a movie invention.',
  'Royal Life Saving guidance: within arm''s reach in and around any water, empty the bath straight away, secure pool fences and gates (and never prop them), and learn infant CPR  -  courses run everywhere and take an evening.',
  'Check any pool fence and gate actually latches, book an infant CPR course, and make "arm''s reach, always" the house rule for every carer.',
  'Swimming lessons are lovely but they are a bonus, not a substitute for supervision at this age.',
  '["Arm''s reach, always, near any water", "Empty baths and buckets immediately", "Check pool fence and gate latch  -  never prop the gate", "Book an infant CPR course"]'::jsonb,
  '["https://www.royallifesaving.com.au/programs/keep-watch"]'::jsonb,
  'Safety content  -  review against current Royal Life Saving guidance before production use.',
  false, false, true, false, false,
  '{"born_only": true}'::jsonb,
  'A calm ocean-pool scene with a bright life ring, a secure gate latch and a small watchful star above, protective coastal mood, ocean teal palette.',
  '/card-images/pixel/px-water-safety-around-babies.png',
  'Pixel art life ring and pool gate latch by an ocean pool, for water safety.',
  'cute 8-bit pixel art item',
  'approved', 'in_review', null, null, null
),
(
  'twelve-month-immunisations',
  'Twelve-month immunisations',
  'The birthday-season booster round',
  'Big Milestone',
  'Health / Immunisations',
  'Baby',
  340, 400, null, null, 95, true,
  'The twelve-month round of the National Immunisation Program is due around the first birthday  -  easy to lose in the party planning.',
  'The first-birthday season is exactly when this round slips through the cracks  -  book it before the cake.',
  'The twelve-month vaccines include measles, mumps and rubella protection. Immunisation records also feed into Child Care Subsidy eligibility, so staying current keeps the admin side happy too.',
  'Book the twelve-month visit near (before or after) the birthday, and bring the health record book as always.',
  'Coordinating it perfectly with the birthday  -  any date in the window works.',
  '["Book the 12-month immunisation visit", "Bring the child health record book", "Check your records updated in myGov afterwards"]'::jsonb,
  '["https://www.health.gov.au/topics/immunisation/when-to-get-vaccinated/national-immunisation-program-schedule"]'::jsonb,
  'Review against current National Immunisation Program schedule before production use.',
  true, false, false, false, false,
  '{"born_only": true}'::jsonb,
  'A calendar with a bandage sticker wearing a tiny party hat, birthday-season-but-organised feeling, sun yellow and coral accents.',
  '/card-images/pixel/px-twelve-month-immunisations.png',
  'Pixel art calendar with a party-hat bandage sticker for the twelve-month immunisations.',
  'cute 8-bit pixel art item',
  'approved', 'in_review', null, null, null
),
(
  'first-birthday-you-made-it',
  'One year: you actually did it',
  'The keeping-a-human-alive achievement',
  'Fun First',
  'Milestones / Reflection',
  'Baby',
  350, 390, null, null, 60, false,
  'Whatever this year looked like  -  smooth, chaotic, nothing like the plan  -  you kept a small human alive and growing for a whole year. That is the achievement.',
  'The first birthday is mostly for the parents  -  bub will not remember it, but you will.',
  'A year of feeds, wake-ups, appointments, firsts and recalibrations deserves a pause. Keep the party as small as you like; the milestone is yours as much as theirs.',
  'Mark it however suits you  -  a cake smash photo, a quiet beach walk, takeaway on the good plates. Take one photo of yourselves too, not just bub.',
  'A Pinterest party. A one-year-old is equally delighted by wrapping paper.',
  '["Plan something tiny (or nothing  -  also valid)", "Take a photo with you in it", "Look at the day-one photos and be a bit amazed"]'::jsonb,
  '[]'::jsonb,
  null,
  false, false, false, false, false,
  '{"born_only": true}'::jsonb,
  'A single delightful birthday cake with one candle and a tiny gold crown beside it, warm celebration sparkles, coral and sun yellow palette.',
  '/card-images/pixel/px-first-birthday-you-made-it.png',
  'Pixel art birthday cake with one candle and a small gold crown.',
  'cute 8-bit pixel art item',
  'approved', 'published', current_date, current_date + interval '12 months', now()
),

-- ============================================================
-- TODDLER (12–24 months)
-- ============================================================
(
  'sun-safety-little-skin',
  'Sun safety for little skin',
  'Slip, slop, slap  -  the toddler edition',
  'Heads Up',
  'Safety / Outdoors',
  'Toddler',
  365, 550, null, null, 78, false,
  'Toddlers outside means real sun exposure. Australian UV is serious: hats, shade, clothing and toddler-appropriate sunscreen become everyday kit.',
  'UV here damages skin even on mild, cloudy days  -  the UV index, not the temperature, is the thing to check.',
  'SunSmart guidance: sun protection whenever UV is 3 or above  -  broad-brim hat, covering clothes, shade, and sunscreen on what is left. Building the hat habit at this age pays off for years.',
  'Stock the kit (hat that stays on, toddler sunscreen, shade options for the pram) and check the UV index in your weather app.',
  'Perfect compliance. A toddler who mostly wears the hat is a win worth celebrating.',
  '["Broad-brim hat that actually stays on", "Toddler-appropriate SPF 50+ sunscreen", "Check the UV index, not the temperature", "Shade for pram and play"]'::jsonb,
  '["https://www.cancer.org.au/cancer-information/causes-and-prevention/sun-safety"]'::jsonb,
  'Safety content  -  review against current SunSmart guidance before production use.',
  false, false, true, false, false,
  '{"born_only": true}'::jsonb,
  'A cheerful tiny sun hat with sunscreen bottle and a smiling sun peeking over a beach umbrella, bright Aussie summer mood, sun yellow and aqua.',
  '/card-images/pixel/px-sun-safety-little-skin.png',
  'Pixel art tiny sun hat, sunscreen and beach umbrella under a friendly sun.',
  'cute 8-bit pixel art item',
  'approved', 'in_review', null, null, null
),
(
  'toddler-tantrums-are-normal',
  'Tantrums are development, not defiance',
  'Big feelings, tiny prefrontal cortex',
  'Parent Sanity',
  'Development / Behaviour',
  'Toddler',
  420, 600, null, null, 72, false,
  'Somewhere in the second year, big feelings arrive before the brain hardware to manage them. Tantrums are a normal developmental stage  -  including the supermarket ones.',
  'A tantrum is a nervous system overflowing, not a child manipulating you  -  and not a reflection of your parenting.',
  'Toddlers feel everything at full volume with almost no self-regulation circuitry yet. Staying calm and nearby (not fixing, not punishing the feeling) is the evidence-aligned play. Public tantrums feel mortifying; every parent watching has been there.',
  'Pick your calm script now ("I''m here, you''re safe, big feeling") and use it on repeat. Guard sleep and snacks  -  most epic tantrums are half tiredness or hunger.',
  'Explaining logic mid-tantrum. Words come back online after the storm, not during it.',
  '["Have one calm script and reuse it", "Protect naps and snacks  -  tantrum insurance", "Stay nearby; connection beats correction mid-storm", "Debrief later, briefly, when calm"]'::jsonb,
  '["https://raisingchildren.net.au/toddlers/behaviour/crying-tantrums/tantrums"]'::jsonb,
  null,
  false, false, false, false, false,
  '{"born_only": true}'::jsonb,
  'A tiny storm cloud with a rainbow starting to peek through, and a warm cup of tea waiting beside it, weathering-the-storm humour, jacaranda and coral.',
  '/card-images/pixel/px-toddler-tantrums-are-normal.png',
  'Pixel art small storm cloud with emerging rainbow and a cup of tea.',
  'cute 8-bit pixel art item',
  'approved', 'published', current_date, current_date + interval '12 months', now()
),
(
  'eighteen-month-immunisations',
  'Eighteen-month immunisations',
  'The easy-to-forget round',
  'Big Milestone',
  'Health / Immunisations',
  'Toddler',
  520, 580, null, null, 94, true,
  'The eighteen-month round of the National Immunisation Program is the one families most often drift past  -  the schedule has been quiet since the first birthday.',
  'After the newborn flurry, eighteen months arrives with no fanfare  -  this is the round to consciously remember.',
  'This round includes boosters that keep earlier protection strong. Records stay linked to family payments, so staying current avoids surprise letters too.',
  'Book the eighteen-month visit now while it is in front of you.',
  'Nothing else  -  this one is genuinely just "book the appointment".',
  '["Book the 18-month immunisation visit", "Bring the child health record book", "Note the next routine round is at 4 years"]'::jsonb,
  '["https://www.health.gov.au/topics/immunisation/when-to-get-vaccinated/national-immunisation-program-schedule"]'::jsonb,
  'Review against current National Immunisation Program schedule before production use.',
  true, false, false, false, false,
  '{"born_only": true}'::jsonb,
  'A friendly string-around-the-finger reminder ribbon tied to a calendar with a bandage sticker, gentle memory-jog humour, teal and cream.',
  '/card-images/pixel/px-eighteen-month-immunisations.png',
  'Pixel art reminder ribbon tied around a calendar with a bandage sticker.',
  'cute 8-bit pixel art item',
  'approved', 'in_review', null, null, null
),
(
  'talking-and-hearing-checks',
  'Words on the way: talking and hearing',
  'Wide range of normal, easy to check',
  'Aussie System',
  'Development / Speech',
  'Toddler',
  540, 730, null, null, 76, false,
  'Language between 18 and 24 months varies enormously. If words seem slow, a free hearing check and a chat with your child health nurse are easy, pressure-free first steps.',
  'Checking hearing early is the step that matters  -  lots of "late talkers" just had fluid in their ears all winter.',
  'Most toddlers say more words month by month, but ear infections and glue ear can quietly muffle a learning-to-listen brain. Hearing tests are free and gentle, and early speech support (if ever needed) works best early. Checking is caring, not catastrophising.',
  'Mention any speech questions at the eighteen-month-ish nurse check, and ask for a hearing test referral if words seem slow or ears have been snotty all year.',
  'Comparing with other toddlers at playgroup. The range of normal is enormous  -  checks beat comparisons.',
  '["Raise speech questions at the nurse check", "Ask about a free hearing test if unsure", "Narrate your day  -  cheap, effective, dorky", "Books at bedtime count double"]'::jsonb,
  '["https://raisingchildren.net.au/toddlers/development/language-development/language-development-1-2-years"]'::jsonb,
  'Development content  -  review against current guidance before production use.',
  true, false, false, false, false,
  '{"born_only": true}'::jsonb,
  'A cute speech bubble sprouting like a small plant next to a friendly ear with a tiny headphone, growing-words mood, gum green and sky blue.',
  '/card-images/pixel/px-talking-and-hearing-checks.png',
  'Pixel art speech bubble sprouting like a plant beside a friendly ear.',
  'cute 8-bit pixel art item',
  'approved', 'in_review', null, null, null
),

-- ============================================================
-- QUIET WEEK (fallback cards  -  no timing window)
-- ============================================================
(
  'quiet-week-nothing-due',
  'A quiet week  -  on purpose',
  'Nothing is due. Nothing is missed.',
  'quiet_week',
  'Reassurance',
  'Any',
  null, null, null, null, 50, false,
  'No appointments, no forms, no milestones due this week. That is not a gap in the app  -  it is the actual state of things.',
  'Some weeks the best parenting move is a walk, a coffee and absolutely no admin.',
  'The timeline only surfaces things when they matter. A quiet week means you are on top of it  -  enjoy the slack in the rope.',
  'Nothing. Genuinely. Maybe the beach.',
  'Everything. That is the whole point this week.',
  '[]'::jsonb,
  '[]'::jsonb,
  null,
  false, false, false, false, false,
  '{}'::jsonb,
  'A hammock strung between two gum trees with a coffee cup resting nearby and soft ocean light, deeply calm holiday-morning mood, cream and aqua.',
  '/card-images/pixel/px-quiet-week-nothing-due.png',
  'Pixel art hammock between gum trees with a coffee cup, for a quiet week.',
  'cute 8-bit pixel art item',
  'approved', 'published', current_date, current_date + interval '12 months', now()
),
(
  'quiet-week-take-the-photo',
  'Take the photo  -  get in the photo',
  'Future you wants proof you were there',
  'quiet_week',
  'Reassurance',
  'Any',
  null, null, null, null, 50, false,
  'A quiet week is a good week to take the unremarkable photos: the messy kitchen, the pram in the hallway, you actually in the frame.',
  'The photos you treasure later are the boring ones  -  and the parent behind the camera is missing from most albums.',
  'Milestone photos take care of themselves. The texture of ordinary weeks  -  breakfast chaos, the nap-trap couch, your tired happy face  -  is what disappears unrecorded.',
  'Hand someone your phone today, or prop it up and use the timer. One photo with you in it.',
  'Sorting, printing, or making albums. Just capture; curate someday.',
  '["One photo with you in it this week", "One photo of something gloriously ordinary"]'::jsonb,
  '[]'::jsonb,
  null,
  false, false, false, false, false,
  '{}'::jsonb,
  'A cheerful instant camera printing a warm little photo of a family kitchen scene, tiny hearts floating, sentimental but playful, coral and cream.',
  '/card-images/pixel/px-quiet-week-take-the-photo.png',
  'Pixel art instant camera printing a photo with small hearts.',
  'cute 8-bit pixel art item',
  'approved', 'published', current_date, current_date + interval '12 months', now()
),
(
  'quiet-week-small-wins',
  'Count the invisible wins',
  'You did a lot this week. It just doesn''t look like it.',
  'quiet_week',
  'Reassurance',
  'Any',
  null, null, null, null, 50, false,
  'Feeds happened. Naps happened (some of them). A small human was kept warm, fed and loved for another week. None of it goes on a CV, all of it counts.',
  'Parenting productivity is invisible  -  the absence of disasters is the achievement.',
  'On the hard days it helps to name what actually got done: the appointments made, the tears soothed, the six thousand small decisions. Quiet competence is still competence.',
  'Name three things that went fine this week. Bar is low on purpose. "Everyone got fed" absolutely counts.',
  'Comparing your week to anyone''s highlight reel.',
  '["Name three fine things from this week", "Tell your support person one of theirs too"]'::jsonb,
  '[]'::jsonb,
  null,
  false, false, false, false, false,
  '{}'::jsonb,
  'Three small glowing trophy cups made of everyday items  -  a bottle, a sock, a coffee cup  -  on a warm shelf, gentle pride mood, sun yellow and jacaranda.',
  '/card-images/pixel/px-quiet-week-small-wins.png',
  'Pixel art trophies shaped like a bottle, sock and coffee cup on a shelf.',
  'cute 8-bit pixel art item',
  'approved', 'published', current_date, current_date + interval '12 months', now()
)

on conflict (slug) do update set
  title = excluded.title,
  subtitle = excluded.subtitle,
  card_type = excluded.card_type,
  category = excluded.category,
  life_stage = excluded.life_stage,
  start_age_days = excluded.start_age_days,
  end_age_days = excluded.end_age_days,
  pregnancy_week_start = excluded.pregnancy_week_start,
  pregnancy_week_end = excluded.pregnancy_week_end,
  priority = excluded.priority,
  time_critical = excluded.time_critical,
  short_summary = excluded.short_summary,
  wish_i_knew = excluded.wish_i_knew,
  why_it_matters = excluded.why_it_matters,
  what_to_do_now = excluded.what_to_do_now,
  what_can_wait = excluded.what_can_wait,
  checklist_items = excluded.checklist_items,
  source_urls = excluded.source_urls,
  source_notes = excluded.source_notes,
  medical_sensitivity = excluded.medical_sensitivity,
  government_sensitivity = excluded.government_sensitivity,
  safety_sensitivity = excluded.safety_sensitivity,
  allergy_sensitivity = excluded.allergy_sensitivity,
  feeding_sensitivity = excluded.feeding_sensitivity,
  conditions = excluded.conditions,
  illustration_prompt = excluded.illustration_prompt,
  image_url = excluded.image_url,
  image_alt = excluded.image_alt,
  image_style = excluded.image_style,
  image_status = excluded.image_status,
  status = excluded.status,
  last_reviewed_at = excluded.last_reviewed_at,
  review_due_date = excluded.review_due_date,
  updated_at = now();
