insert into public.timeline_cards (
  slug,
  title,
  subtitle,
  card_type,
  category,
  life_stage,
  start_age_days,
  end_age_days,
  pregnancy_week_start,
  pregnancy_week_end,
  priority,
  short_summary,
  wish_i_knew,
  why_it_matters,
  what_to_do_now,
  what_can_wait,
  checklist_items,
  source_urls,
  source_notes,
  medical_sensitivity,
  government_sensitivity,
  safety_sensitivity,
  feeding_sensitivity,
  conditions,
  illustration_prompt,
  image_url,
  image_alt,
  image_style,
  image_status,
  status,
  last_reviewed_at,
  review_due_date,
  published_at
) values
(
  'first-gp-appointment',
  'First GP appointment',
  'The first boring-but-important step',
  'Big Milestone',
  'Pregnancy / Health',
  'Pregnancy',
  null,
  null,
  6,
  8,
  100,
  'Book a GP appointment to confirm pregnancy, organise early bloods, discuss supplements and plan the next steps.',
  'The first appointment is less dramatic than you imagine, but it starts the whole Australian pregnancy pathway.',
  'Your GP can help confirm pregnancy, organise early tests, discuss folate and iodine, talk through public/private care options and refer you into the right pathway.',
  'Book a GP appointment and bring your estimated last menstrual period or positive pregnancy test date if known.',
  'You do not need to have every hospital or birth decision made before this appointment.',
  '["Book a GP appointment", "Note your estimated last menstrual period if known", "Write down any early questions"]'::jsonb,
  '["https://www.pregnancybirthbaby.org.au/your-first-antenatal-visit"]'::jsonb,
  'Review against current Australian pregnancy guidance before production use.',
  true,
  false,
  false,
  false,
  '{"unborn_only": true}'::jsonb,
  'A warm illustrated calendar with a tiny positive pregnancy test and coffee cup nearby.',
  '/card-images/pixel/px-first-gp-appointment.png',
  'Illustrated calendar with a positive pregnancy test and coffee cup.',
  'cute 8-bit pixel art item',
  'approved',
  'published',
  current_date,
  current_date + interval '12 months',
  now()
),
(
  'start-thinking-about-childcare',
  'Start thinking about childcare',
  'Annoyingly early, but worth it',
  'Admin Trap',
  'Childcare / Planning',
  'Pregnancy or early baby',
  0,
  90,
  24,
  40,
  90,
  'If you might need childcare, start researching and joining waitlists earlier than feels reasonable.',
  'Childcare planning starts before you feel ready to think about childcare.',
  'Popular centres can have long waitlists, and it takes time to compare locations, fees, availability, orientation and Child Care Subsidy.',
  'Make a shortlist of centres near home and work, ask about nursery availability, and join waitlists if needed.',
  'You do not need your exact return-to-work date locked in before you start researching.',
  '["List centres near home and work", "Ask about nursery availability", "Check waitlist fees", "Read the Child Care Subsidy basics"]'::jsonb,
  '["https://www.servicesaustralia.gov.au/child-care-subsidy"]'::jsonb,
  'Review Child Care Subsidy wording before production use.',
  false,
  true,
  false,
  false,
  '{"childcare_yes_or_unsure": true, "first_child_only": true}'::jsonb,
  'A playful illustrated clipboard with tiny blocks, a dummy and a calendar.',
  '/card-images/pixel/px-start-thinking-about-childcare.png',
  'Illustrated childcare planning clipboard with blocks, dummy and calendar.',
  'cute 8-bit pixel art item',
  'approved',
  'published',
  current_date,
  current_date + interval '12 months',
  now()
),
(
  'two-month-immunisations',
  'Two-month immunisations',
  'Book it before the week gets away from you',
  'Big Milestone',
  'Health / Immunisations',
  'Baby',
  42,
  70,
  null,
  null,
  100,
  'The first major post-birth immunisation appointment comes around quickly.',
  'Two months sounds far away when they are born, then suddenly it is next week.',
  'The Australian immunisation schedule has key vaccines due in infancy. Booking ahead helps avoid scrambling.',
  'Check your child''s due date for immunisations and book with your GP or provider.',
  'You do not need to understand every vaccine in detail before booking. Your provider can talk you through it.',
  '["Check the immunisation schedule", "Book with your GP or provider", "Add the appointment to your calendar"]'::jsonb,
  '["https://www.health.gov.au/topics/immunisation/when-to-get-vaccinated/national-immunisation-program-schedule"]'::jsonb,
  'Review against current National Immunisation Program schedule before production use.',
  true,
  false,
  false,
  false,
  '{"born_only": true}'::jsonb,
  'A gentle illustrated calendar with a tiny bandage sticker, not a scary needle.',
  '/card-images/pixel/px-two-month-immunisations.png',
  'Illustrated calendar with a small bandage sticker.',
  'cute 8-bit pixel art item',
  'approved',
  'published',
  current_date,
  current_date + interval '6 months',
  now()
),
(
  'starting-solids',
  'Starting solids',
  'Cute mess, but also a bit of a project',
  'Big Milestone',
  'Feeding / Solids',
  'Baby',
  120,
  190,
  null,
  null,
  95,
  'Solids are about more than purees. You will be thinking about readiness, iron, allergens, textures, mess and routine.',
  'Starting solids is less about fancy recipes and more about repetition, safety and not losing your mind cleaning the floor.',
  'This stage introduces new skills, flavours and routines. It can feel overwhelming, but you can keep it simple.',
  'Get a high chair, a few bibs, some easy first foods and learn the basics of choking versus gagging.',
  'You do not need elaborate recipes or a freezer full of tiny gourmet cubes.',
  '["Check readiness signs with trusted guidance", "Set up a high chair", "Get a few easy-clean bibs", "Read choking and allergy basics"]'::jsonb,
  '["https://raisingchildren.net.au/babies/breastfeeding-bottle-feeding-solids/solids-drinks/introducing-solids", "https://www.allergy.org.au/patients/allergy-prevention/ascia-how-to-introduce-solid-foods-to-babies"]'::jsonb,
  'Review feeding, allergy and safety claims before production use.',
  false,
  false,
  true,
  true,
  '{"born_only": true}'::jsonb,
  'A cute messy high chair with pumpkin, spoon and bib.',
  '/card-images/pixel/px-starting-solids.png',
  'Illustrated messy high chair with pumpkin, spoon and bib.',
  'cute 8-bit pixel art item',
  'approved',
  'published',
  current_date,
  current_date + interval '6 months',
  now()
),
(
  'time-for-proper-spoons',
  'Time for proper spoons',
  'Soft-tip baby spoons had a good run',
  'Tiny Gear Shift',
  'Feeding / Gear',
  'Baby',
  320,
  380,
  null,
  null,
  70,
  'Your baby may be ready for more normal toddler spoons as they eat thicker food and practise self-feeding.',
  'Soft-tip baby spoons are great early on, but eventually they can make real food and self-feeding more annoying than helpful.',
  'Around this stage, babies are often eating thicker textures, grabbing the spoon, chewing on utensils and trying to feed themselves. A slightly more normal toddler spoon can make meals easier.',
  'Buy 2-4 toddler spoons that are small enough for their mouth but sturdier than soft-tip baby spoons.',
  'You do not need a fancy full cutlery set. A few good spoons are enough.',
  '["Check if your current spoons are too shallow or floppy", "Buy a small set of toddler spoons", "Keep old soft spoons if still useful", "Let baby practise holding one spoon while you use another"]'::jsonb,
  '[]'::jsonb,
  null,
  false,
  false,
  false,
  false,
  '{"born_only": true}'::jsonb,
  'A cute illustrated toddler spoon presented like a tiny level-up item.',
  '/card-images/pixel/px-time-for-proper-spoons.png',
  'Illustrated toddler spoon presented like a tiny level-up item.',
  'cute 8-bit pixel art item',
  'approved',
  'published',
  current_date,
  null,
  now()
),
(
  'daycare-sickness-era',
  'The daycare sickness era',
  'Stock up before the first snot wave',
  'Heads Up',
  'Childcare / Illness',
  'Baby / Toddler',
  240,
  540,
  null,
  null,
  80,
  'Starting daycare often means more bugs. It helps to have a basic illness setup before everyone is tired and covered in snot.',
  'Daycare sickness is not one cold. It is a season of life.',
  'Having basics ready can make sick days less chaotic.',
  'Prepare a simple sick-day kit and know your GP and after-hours options.',
  'You do not need to panic-buy every medicine. Keep it sensible and ask your pharmacist or GP what is appropriate.',
  '["Save your GP and after-hours details", "Check what your childcare asks parents to do when children are sick", "Ask your pharmacist or GP what basics suit your child"]'::jsonb,
  '["https://raisingchildren.net.au/guides/a-z-health-reference/colds"]'::jsonb,
  'Review illness wording before production use.',
  true,
  false,
  false,
  false,
  '{"born_only": true, "childcare_yes_or_unsure": true}'::jsonb,
  'A cute tissue box, thermometer and tiny socks in a warm illustrated style.',
  '/card-images/pixel/px-daycare-sickness-era.png',
  'Illustrated tissue box, thermometer and tiny socks.',
  'cute 8-bit pixel art item',
  'approved',
  'published',
  current_date,
  current_date + interval '6 months',
  now()
)
on conflict (slug) do update set
  title = excluded.title,
  subtitle = excluded.subtitle,
  card_type = excluded.card_type,
  category = excluded.category,
  life_stage = excluded.life_stage,
  start_age_days = excluded.start_age_days,
  end_age_days = excluded.end_age_days,
  pregnancy_week_start = excluded.pregnancy_week_start,
  pregnancy_week_end = excluded.pregnancy_week_end,
  priority = excluded.priority,
  short_summary = excluded.short_summary,
  wish_i_knew = excluded.wish_i_knew,
  why_it_matters = excluded.why_it_matters,
  what_to_do_now = excluded.what_to_do_now,
  what_can_wait = excluded.what_can_wait,
  checklist_items = excluded.checklist_items,
  source_urls = excluded.source_urls,
  source_notes = excluded.source_notes,
  medical_sensitivity = excluded.medical_sensitivity,
  government_sensitivity = excluded.government_sensitivity,
  safety_sensitivity = excluded.safety_sensitivity,
  feeding_sensitivity = excluded.feeding_sensitivity,
  conditions = excluded.conditions,
  illustration_prompt = excluded.illustration_prompt,
  image_url = excluded.image_url,
  image_alt = excluded.image_alt,
  image_style = excluded.image_style,
  image_status = excluded.image_status,
  status = excluded.status,
  last_reviewed_at = excluded.last_reviewed_at,
  review_due_date = excluded.review_due_date,
  updated_at = now();

-- Migration 003 adds time_critical; mark immunisation card as time-sensitive.
update public.timeline_cards
set time_critical = true
where slug = 'two-month-immunisations';
