-- Wish I Knew content library batch 5 (50 cards).
-- Run after seed_content_library_batch4.sql. Safe to re-run (upserts by slug).
-- Sensitive cards remain in_review with null review dates until editorial review.

insert into public.timeline_cards (
  slug, title, subtitle, card_type, category, life_stage,
  start_age_days, end_age_days, pregnancy_week_start, pregnancy_week_end,
  priority, time_critical, short_summary, wish_i_knew, why_it_matters,
  what_to_do_now, what_can_wait, checklist_items, source_urls, source_notes,
  medical_sensitivity, government_sensitivity, safety_sensitivity,
  allergy_sensitivity, feeding_sensitivity, conditions, illustration_prompt,
  image_url, image_alt, image_style, image_status, status,
  last_reviewed_at, review_due_date, published_at
) values
(
  'pregnancy-medicine-check',
  'Check before taking it',
  'Even the familiar packet',
  'Heads Up',
  'Pregnancy / Health',
  'Pregnancy',
  null, null, 4, 40,
  88,
  false,
  'Check prescription, over-the-counter and complementary medicines with a doctor, pharmacist or midwife during pregnancy.',
  'Familiar does not always mean pregnancy-ready, and asking is a normal pharmacy question.',
  'Some medicines need changing, while stopping an important medicine suddenly can also cause harm.',
  'Keep a list of everything you take and check before starting, stopping or changing it.',
  'Clearing the whole bathroom cupboard in a panic.',
  '["List medicines and supplements","Ask before changing anything","Mention pregnancy at the pharmacy"]'::jsonb,
  '["https://www.pregnancybirthbaby.org.au/pregnancy/nutrition-and-lifestyle/medicines-during-pregnancy"]'::jsonb,
  'Medical content. Review against current Australian guidance before production use.',
  true,
  false,
  false,
  false,
  false,
  '{"unborn_only":true}'::jsonb,
  'Cute pixel art collectible: a closed medicine box beside a phone with a friendly pharmacist speech bubble and a tiny gum leaf.',
  '/card-images/pixel/px-pregnancy-medicine-check.png',
  'Pixel art medicine box and phone with a pharmacist symbol for checking medicines during pregnancy.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'pregnancy-food-safety-shortlist',
  'Keep one food safety shortlist',
  'A fridge note beats food fear',
  'Tiny Gear Shift',
  'Pregnancy / Food safety',
  'Pregnancy',
  null, null, 4, 40,
  76,
  false,
  'A short Australian food safety list makes everyday choices easier without turning every meal into a research project.',
  'The useful version fits on the fridge, not in twelve anxious browser tabs.',
  'Pregnancy changes the risk from some foodborne infections, and practical handling matters as much as individual foods.',
  'Save one trusted list and focus on clean preparation, safe storage and foods that need avoiding.',
  'Building a perfect pregnancy menu.',
  '["Use one Australian source","Refrigerate leftovers promptly","Reheat ready-to-eat food until steaming"]'::jsonb,
  '["https://www.pregnancybirthbaby.org.au/pregnancy/nutrition-and-lifestyle/foods-to-avoid-when-pregnant"]'::jsonb,
  'Medical and food safety content. Review against current Australian guidance before production use.',
  true,
  false,
  true,
  false,
  false,
  '{"unborn_only":true}'::jsonb,
  'Cute pixel art collectible: a fridge checklist surrounded by a steaming meal, washed fruit and a small shield sparkle, no text.',
  '/card-images/pixel/px-pregnancy-food-safety-shortlist.png',
  'Pixel art fridge checklist, hot meal and fruit for a pregnancy food safety shortlist.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'pregnancy-movement-pattern',
  'Learn bub''s movement pattern',
  'A change is worth a call',
  'Heads Up',
  'Pregnancy / Baby movements',
  'Pregnancy',
  null, null, 20, 40,
  96,
  true,
  'There is no single right kick count. Get to know your baby''s usual pattern and seek advice promptly if movements reduce or change.',
  'You are never wasting the maternity unit''s time by calling about changed movements.',
  'A change in movement can be an early sign that a baby needs assessment.',
  'Contact your midwife, doctor or maternity unit immediately if movements feel reduced, stop or are clearly different.',
  'Trying tricks at home before making the call.',
  '["Notice the usual pattern","Call promptly about a change","Do not wait until the next day"]'::jsonb,
  '["https://www.pregnancybirthbaby.org.au/pregnancy/health-conditions-and-complications/baby-movements-during-pregnancy"]'::jsonb,
  'Medical, safety and time-critical content. Review against current Australian guidance before production use.',
  true,
  false,
  true,
  false,
  false,
  '{"unborn_only":true}'::jsonb,
  'Cute pixel art collectible: a cosy pregnant belly silhouette with gentle star-like movement sparkles and a phone nearby.',
  '/card-images/pixel/px-pregnancy-movement-pattern.png',
  'Pixel art pregnancy silhouette with gentle movement sparkles and a phone for seeking advice about changes.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'preeclampsia-warning-signs',
  'Know the pre-eclampsia flags',
  'Prompt advice, no self-diagnosis',
  'Heads Up',
  'Pregnancy / Warning signs',
  'Pregnancy',
  null, null, 20, 40,
  98,
  true,
  'Severe headache, vision changes, sudden swelling, pain under the ribs or feeling very unwell need prompt maternity advice.',
  'You do not need to decide whether a symptom is serious before you call.',
  'Pre-eclampsia can develop during pregnancy or after birth and needs professional assessment.',
  'Call your maternity unit, midwife or doctor urgently about warning signs. Call 000 for an emergency.',
  'Waiting for the next routine appointment.',
  '["Save the maternity unit number","Call about warning signs","Use 000 in an emergency"]'::jsonb,
  '["https://www.pregnancybirthbaby.org.au/pregnancy/health-conditions-and-complications/pre-eclampsia"]'::jsonb,
  'Medical and time-critical content. Review against current Australian guidance before production use.',
  true,
  false,
  false,
  false,
  false,
  '{"unborn_only":true}'::jsonb,
  'Cute pixel art collectible: a blood pressure cuff beside a calm phone and three clear alert sparkles, reassuring not alarming.',
  '/card-images/pixel/px-preeclampsia-warning-signs.png',
  'Pixel art blood pressure cuff and phone representing pregnancy warning signs that need prompt advice.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'pregnancy-exercise-comfort',
  'Let movement be comfortable',
  'The pace can change',
  'Parent Sanity',
  'Pregnancy / Movement',
  'Pregnancy',
  null, null, 4, 40,
  58,
  false,
  'For many pregnancies, comfortable regular movement is useful. Your clinician can help adapt it to your health and pregnancy.',
  'Slower still counts, and rest is not a failed workout.',
  'Movement can support wellbeing, while some symptoms and pregnancy conditions need individual advice.',
  'Choose a comfortable activity, stay hydrated and ask your clinician about any restrictions or warning signs.',
  'Chasing your pre-pregnancy pace or personal best.',
  '["Choose comfortable movement","Drink water","Stop and seek advice about warning signs"]'::jsonb,
  '["https://www.pregnancybirthbaby.org.au/exercising-during-pregnancy"]'::jsonb,
  'Medical content. Review against current Australian guidance before production use.',
  true,
  false,
  false,
  false,
  false,
  '{"unborn_only":true}'::jsonb,
  'Cute pixel art collectible: comfortable walking shoes, a water bottle and a shaded park loop with a small pause symbol.',
  '/card-images/pixel/px-pregnancy-exercise-comfort.png',
  'Pixel art walking shoes, water bottle and shaded loop for comfortable pregnancy movement.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'birth-support-backup',
  'Name a backup support person',
  'Plans enjoy a spare key',
  'Tiny Gear Shift',
  'Pregnancy / Preparation',
  'Pregnancy',
  null, null, 28, 40,
  62,
  false,
  'A second person who knows the broad plan can step in if illness, work or travel gets in the way.',
  'The backup is not bad luck. It is one less midnight phone tree.',
  'Birth timing is unpredictable, and practical backup makes the main plan feel lighter.',
  'Ask one trusted person and share key contacts, transport details and pet or sibling jobs.',
  'Rehearsing every possible birth scenario.',
  '["Choose one backup","Share key contacts","Explain practical jobs"]'::jsonb,
  '[]'::jsonb,
  null,
  false,
  false,
  false,
  false,
  false,
  '{"unborn_only":true}'::jsonb,
  'Cute pixel art collectible: two friendly contact cards beside a packed birth bag with a small backup sparkle, no text.',
  '/card-images/pixel/px-birth-support-backup.png',
  'Pixel art birth bag and two contact cards representing a backup support person.',
  'cute 8-bit pixel art item',
  'approved',
  'published',
  current_date,
  current_date + interval '12 months',
  now()
),
(
  'pet-plan-for-birth',
  'Give the pet plan a human',
  'Someone owns the lead',
  'Tiny Gear Shift',
  'Pregnancy / Home',
  'Pregnancy',
  null, null, 30, 40,
  50,
  false,
  'Choose who feeds, walks or collects your pet if labour starts at an inconvenient hour.',
  'A pet plan becomes real when one actual person has the spare key.',
  'Clear ownership removes one more job from labour and the first trip home.',
  'Give a trusted person access, written routines and your vet details.',
  'Designing an elaborate first meeting between pet and baby.',
  '["Name the helper","Share the routine","Leave food, lead and vet details together"]'::jsonb,
  '[]'::jsonb,
  null,
  false,
  false,
  false,
  false,
  false,
  '{"unborn_only":true}'::jsonb,
  'Cute pixel art collectible: a cheerful dog beside a food bowl, lead and small calendar with a heart symbol.',
  '/card-images/pixel/px-pet-plan-for-birth.png',
  'Pixel art dog, lead, bowl and calendar for arranging pet care around birth.',
  'cute 8-bit pixel art item',
  'approved',
  'published',
  current_date,
  current_date + interval '12 months',
  now()
),
(
  'hallway-night-lights',
  'Light the midnight path',
  'Tiny glow, fewer stubbed toes',
  'Tiny Gear Shift',
  'Pregnancy / Home',
  'Pregnancy',
  null, null, 30, 40,
  46,
  false,
  'Low, warm night lights can make feeds, nappies and bathroom trips easier without switching on the whole house.',
  'The hallway chair leg becomes a supervillain at 3am.',
  'A visible route removes friction when everyone is sleepy and carrying supplies.',
  'Place a soft light along the route you expect to use most.',
  'A complete smart-home lighting overhaul.',
  '["Walk the night route","Add one warm low light","Keep cords out of the path"]'::jsonb,
  '[]'::jsonb,
  null,
  false,
  false,
  false,
  false,
  false,
  '{"unborn_only":true}'::jsonb,
  'Cute pixel art collectible: two tiny warm night lights guiding a path from a cosy bed to a nappy basket.',
  '/card-images/pixel/px-hallway-night-lights.png',
  'Pixel art warm night lights along a short path between a bed and nappy basket.',
  'cute 8-bit pixel art item',
  'approved',
  'published',
  current_date,
  current_date + interval '12 months',
  now()
),
(
  'newborn-bloodspot-screen',
  'The heel-prick screen',
  'Small test, important follow-up',
  'Big Milestone',
  'Newborn / Screening',
  'Newborn (0-3 months)',
  0, 14, null, null,
  88,
  false,
  'The newborn bloodspot screen is usually offered in the first few days to check for rare but serious conditions.',
  'It is a brief, routine offer in a week already full of new information.',
  'Early detection can allow treatment or support to begin before symptoms appear.',
  'Ask when it will happen, keep the record and make sure the service can contact you about results.',
  'Trying to memorise every condition on the panel.',
  '["Confirm the screen was offered","Keep contact details current","Follow up if asked"]'::jsonb,
  '["https://www.pregnancybirthbaby.org.au/labour-and-birth/after-birth/your-baby-in-the-first-few-days"]'::jsonb,
  'Medical screening content. Review against current Australian guidance before production use.',
  true,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: a small newborn screening card with five gentle dots beside a baby health record, no words.',
  '/card-images/pixel/px-newborn-bloodspot-screen.png',
  'Pixel art newborn bloodspot screening card beside a baby health record.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'vitamin-k-and-hep-b',
  'Ask about the first preventive care',
  'Consent comes with questions',
  'Heads Up',
  'Newborn / Preventive care',
  'Newborn (0-3 months)',
  0, 7, null, null,
  84,
  false,
  'Soon after birth, parents are usually offered vitamin K and hepatitis B vaccination for their baby.',
  'You can ask what each one does before the room gets busy.',
  'These offers protect against specific serious health risks in early life.',
  'Discuss benefits, timing and consent with your midwife or doctor, and keep the record.',
  'Making the decision from social media summaries.',
  '["Ask questions before birth if helpful","Record consent and doses","Keep the baby health record handy"]'::jsonb,
  '["https://www.pregnancybirthbaby.org.au/labour-and-birth/after-birth/your-baby-in-the-first-few-days"]'::jsonb,
  'Medical preventive-care content. Review against current Australian guidance before production use.',
  true,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: a baby health record with two small shield badges and a calm hospital bassinet icon.',
  '/card-images/pixel/px-vitamin-k-and-hep-b.png',
  'Pixel art baby health record with two shield badges for newborn preventive care discussions.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'newborn-fever-call-now',
  'A young baby''s fever needs a call',
  'Under three months, act promptly',
  'Heads Up',
  'Newborn / Health',
  'Newborn (0-3 months)',
  0, 90, null, null,
  100,
  true,
  'A temperature of 38°C or more in a baby under 3 months needs urgent medical assessment.',
  'This is a call-now moment, not a wait-and-see overnight moment.',
  'Young babies can become unwell quickly and may show few other signs.',
  'Seek urgent medical advice. Call 000 if your baby is very unwell, hard to wake or struggling to breathe.',
  'Trying to manage the fever without professional advice.',
  '["Measure the temperature","Seek urgent assessment","Call 000 for emergency signs"]'::jsonb,
  '["https://www.healthdirect.gov.au/fever-and-high-temperature-in-children"]'::jsonb,
  'Medical, safety and time-critical content. Review against current Australian guidance before production use.',
  true,
  false,
  true,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: a digital thermometer beside a phone with a clear call sparkle and a tiny newborn blanket.',
  '/card-images/pixel/px-newborn-fever-call-now.png',
  'Pixel art thermometer and phone for promptly seeking advice about fever in a young baby.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'second-hand-bassinet-check',
  'Check the hand-me-down bassinet',
  'Lovely history, current safety',
  'Heads Up',
  'Safety / Sleep gear',
  'Newborn (0-3 months)',
  0, 180, null, null,
  86,
  false,
  'Before using second-hand sleep gear, check its condition, instructions, mattress fit and current Australian safety guidance.',
  'Sentimental and safe can coexist, but age alone is not the test.',
  'Missing parts, damage or an unsuitable mattress can create hazards that are not obvious in a quick look.',
  'Identify the product, find its instructions, check recalls and inspect every part before use.',
  'Using it because the first night is close.',
  '["Find the make and model","Check recalls and warnings","Inspect mattress and hardware"]'::jsonb,
  '["https://www.productsafety.gov.au/consumers/keep-baby-safe/settle-baby-to-sleep-safely/household-cots-guide"]'::jsonb,
  'Safety content. Review against current Australian guidance before production use.',
  false,
  false,
  true,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: a sturdy bassinet with a magnifying glass, firm flat mattress and small safety shield.',
  '/card-images/pixel/px-second-hand-bassinet-check.png',
  'Pixel art bassinet, magnifying glass and safety shield for checking second-hand sleep gear.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'formula-scoop-stays-with-tin',
  'Keep each scoop with its tin',
  'The ratio belongs to that product',
  'Tiny Gear Shift',
  'Feeding / Formula',
  'Newborn (0-3 months)',
  0, 365, null, null,
  82,
  false,
  'Use the scoop and mixing directions supplied with the formula you are preparing, because products can differ.',
  'A scoop is not universal just because it looks identical at 2am.',
  'Using the correct amount of water and powder helps make feeds safely.',
  'Leave the scoop with its original tin and follow that label exactly each time.',
  'Decanting formula into prettier unlabelled containers.',
  '["Use the supplied scoop","Follow the tin directions","Make feeds with safe preparation practices"]'::jsonb,
  '["https://www.pregnancybirthbaby.org.au/babies/feeding-and-nutrition/feeding-your-baby-with-formula"]'::jsonb,
  'Feeding and safety content. Review against current Australian guidance before production use.',
  false,
  false,
  true,
  false,
  true,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: a formula tin with its matching scoop, a clean bottle and a precise little sparkle, no branding.',
  '/card-images/pixel/px-formula-scoop-stays-with-tin.png',
  'Pixel art formula tin, matching scoop and clean bottle on a warm cream background.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'breast-pump-start-low',
  'Start the pump gently',
  'More suction is not more success',
  'Tiny Gear Shift',
  'Feeding / Expressing',
  'Newborn (0-3 months)',
  0, 180, null, null,
  68,
  false,
  'Begin expressing with low comfortable suction and seek qualified help if pumping hurts or causes damage.',
  'The strongest setting is not a level you need to unlock.',
  'Comfort supports repeatable expressing, while pain can signal that technique, fit or equipment needs attention.',
  'Start low, increase only while comfortable and contact a midwife, nurse or lactation professional about ongoing pain.',
  'Buying a cupboard of accessories before checking the setup.',
  '["Start on low suction","Stop if it hurts","Ask for qualified help with ongoing pain"]'::jsonb,
  '["https://www.healthdirect.gov.au/expressing-and-storing-breast-milk"]'::jsonb,
  'Medical and feeding content. Review against current Australian guidance before production use.',
  true,
  false,
  false,
  false,
  true,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: a simple breast pump with a gentle low-setting dial, soft comfort sparkles and no body.',
  '/card-images/pixel/px-breast-pump-start-low.png',
  'Pixel art breast pump with a low-setting dial and gentle comfort sparkles.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'nappy-rash-air-time',
  'Give irritated skin some air',
  'Dry, gentle, checked if worried',
  'Tiny Gear Shift',
  'Newborn / Skin',
  'Newborn (0-3 months)',
  0, 365, null, null,
  64,
  false,
  'Frequent changes, gentle cleaning and short nappy-free time can help mild nappy rash. Get advice if it is severe or not improving.',
  'The deluxe treatment is sometimes a towel, fresh air and no rushing.',
  'Keeping skin clean and dry reduces irritation, while persistent rash may need assessment.',
  'Use a washable towel for a little air time and ask a pharmacist, nurse or doctor about concerning rash.',
  'Trying several new creams at once.',
  '["Change wet or dirty nappies promptly","Clean and dry gently","Seek advice if severe or persistent"]'::jsonb,
  '["https://www.pregnancybirthbaby.org.au/babies/daily-care/nappies"]'::jsonb,
  'Medical skin-care content. Review against current Australian guidance before production use.',
  true,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: a clean folded nappy beside a soft towel, open window breeze marks and a tiny sun.',
  '/card-images/pixel/px-nappy-rash-air-time.png',
  'Pixel art clean nappy and soft towel with gentle breeze marks for nappy-free time.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'burp-cloth-drop-zones',
  'Put cloths where life happens',
  'One in every landing zone',
  'Tiny Gear Shift',
  'Newborn / Practical',
  'Newborn (0-3 months)',
  0, 120, null, null,
  42,
  false,
  'A few washable cloths beside the sofa, cot and feeding chair prevent constant supply runs.',
  'The cloth in the nursery is no help when the shoulder event happens in the kitchen.',
  'Tiny duplicated basics save energy during repetitive newborn days.',
  'Make three small cloth drop zones and refill them on laundry day.',
  'A coordinated textile collection.',
  '["Choose three landing zones","Add two cloths to each","Refill them together"]'::jsonb,
  '[]'::jsonb,
  null,
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: three folded burp cloths in tiny baskets beside a cot, sofa and feeding chair.',
  '/card-images/pixel/px-burp-cloth-drop-zones.png',
  'Pixel art burp cloth baskets placed beside a cot, sofa and feeding chair.',
  'cute 8-bit pixel art item',
  'approved',
  'published',
  current_date,
  current_date + interval '12 months',
  now()
),
(
  'laundry-baskets-count',
  'Add the extra laundry basket',
  'Containment is a system',
  'Parent Sanity',
  'Postpartum / Home',
  'Newborn (0-3 months)',
  0, 180, null, null,
  40,
  false,
  'A basket where baby changes actually happen is more useful than one perfect hamper in another room.',
  'Laundry still counts as managed while it is safely inside a basket.',
  'Reducing trips and floor piles makes a high-repeat job easier without demanding a new routine.',
  'Put one easy-carry basket near the busiest change area.',
  'Folding every tiny item before anyone can wear it.',
  '["Place the basket nearby","Choose one wash rhythm","Accept clean-basket living when needed"]'::jsonb,
  '[]'::jsonb,
  null,
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: two practical laundry baskets, one full of tiny clothes and one ready by a doorway.',
  '/card-images/pixel/px-laundry-baskets-count.png',
  'Pixel art laundry baskets with tiny baby clothes on a warm cream background.',
  'cute 8-bit pixel art item',
  'approved',
  'published',
  current_date,
  current_date + interval '12 months',
  now()
),
(
  'upstairs-downstairs-recovery-kit',
  'Duplicate the recovery basics',
  'Save the unnecessary stairs',
  'Tiny Gear Shift',
  'Postpartum / Recovery',
  'Newborn (0-3 months)',
  0, 90, null, null,
  56,
  false,
  'If your home has levels, keep water, snacks, chargers and basic baby supplies where you rest on each one.',
  'The spare charger upstairs can feel like premium postnatal infrastructure.',
  'Fewer supply trips can make feeding, resting and physical recovery gentler.',
  'Fill two small baskets with the things you reach for repeatedly.',
  'Moving the whole nursery downstairs.',
  '["Water and snack","Long charging cable","Cloths and basic baby supplies"]'::jsonb,
  '[]'::jsonb,
  null,
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: two matching recovery baskets with water bottle, snack and cloth linked by tiny stairs.',
  '/card-images/pixel/px-upstairs-downstairs-recovery-kit.png',
  'Pixel art matching recovery baskets on two levels with water, snack and cloth.',
  'cute 8-bit pixel art item',
  'approved',
  'published',
  current_date,
  current_date + interval '12 months',
  now()
),
(
  'second-hand-gear-recall-check',
  'Search the gear before saying yes',
  'A freebie still gets a safety check',
  'Heads Up',
  'Safety / Gear',
  'Baby (3-12 months)',
  90, 730, null, null,
  82,
  false,
  'Before using second-hand baby gear, identify the model, check recalls and inspect it for damage or missing parts.',
  'The bargain price does not include the missing instruction manual.',
  'Older, modified or recalled products may not meet current safety expectations.',
  'Search the product name and model on ACCC Product Safety before accepting or using it.',
  'Collecting it because the listing ends tonight.',
  '["Find make and model","Check recalls","Inspect parts and instructions"]'::jsonb,
  '["https://www.productsafety.gov.au/consumers/know-your-product-safety-rights/buy-safe-second-hand-products-online"]'::jsonb,
  'Safety content. Review against current Australian guidance before production use.',
  false,
  false,
  true,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: a second-hand baby item tag under a magnifying glass beside a phone and shield sparkle.',
  '/card-images/pixel/px-second-hand-gear-recall-check.png',
  'Pixel art baby gear tag, magnifying glass and phone for checking recalls and safety.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'lower-cot-before-standing',
  'Lower the cot before the pull-up',
  'Do it before the surprise',
  'Heads Up',
  'Safety / Sleep gear',
  'Baby (3-12 months)',
  150, 730, null, null,
  88,
  false,
  'Move the cot mattress to its lowest safe setting before your baby can pull to stand, following the product instructions.',
  'The first pull-to-stand often arrives without a calendar invitation.',
  'Correct mattress height helps reduce the chance of a mobile baby climbing or falling out.',
  'Check the cot instructions and lower the base when mobility is approaching.',
  'Waiting for the first successful climb.',
  '["Find the cot instructions","Lower the mattress base","Remove footholds near the cot"]'::jsonb,
  '["https://www.productsafety.gov.au/consumers/keep-baby-safe/settle-baby-to-sleep-safely/household-cots-guide"]'::jsonb,
  'Safety content. Review against current Australian guidance before production use.',
  false,
  false,
  true,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: a cot with its mattress shown at the lowest setting beside a tiny standing sparkle.',
  '/card-images/pixel/px-lower-cot-before-standing.png',
  'Pixel art cot with the mattress lowered for a baby beginning to stand.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'pram-brake-every-stop',
  'Brake before you let go',
  'Every stop, even the tiny ones',
  'Tiny Gear Shift',
  'Safety / Prams',
  'Baby (3-12 months)',
  90, 730, null, null,
  86,
  false,
  'Use the pram parking brake whenever you stop, even on flat ground or for a moment.',
  'Flat ground has a talent for becoming not quite flat.',
  'A secured pram is less likely to roll while you manage bags, doors or another child.',
  'Make brake-on the first move whenever the pram stops.',
  'Trusting that one hand on the handle will cover every distraction.',
  '["Brake at every stop","Check it has engaged","Keep the pram within reach"]'::jsonb,
  '["https://www.productsafety.gov.au/consumers/keep-baby-safe/move-baby-safely/prams-and-strollers-guide"]'::jsonb,
  'Safety content. Review against current Australian guidance before production use.',
  false,
  false,
  true,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: a compact pram with a clearly engaged red wheel brake and a small shield sparkle.',
  '/card-images/pixel/px-pram-brake-every-stop.png',
  'Pixel art pram with its wheel brake engaged.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'infant-first-aid-before-mobile',
  'Learn first aid before the chase',
  'Confidence for the mobile months',
  'Heads Up',
  'Safety / First aid',
  'Baby (3-12 months)',
  90, 365, null, null,
  78,
  false,
  'An infant first aid course can build practical confidence before crawling, solids and exploration expand the hazards.',
  'The best time to practise is when nobody needs the skill.',
  'Hands-on training helps carers recognise emergencies and respond while help is on the way.',
  'Find a reputable Australian infant first aid course and include regular carers if possible.',
  'Buying a giant first aid kit without learning how to use it.',
  '["Choose a reputable course","Invite regular carers","Save emergency contacts"]'::jsonb,
  '["https://www.pregnancybirthbaby.org.au/babies/daily-care/keeping-baby-safe"]'::jsonb,
  'Safety content. Review against current Australian guidance before production use.',
  false,
  false,
  true,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: a first aid booklet with a heart shield beside crawling knee pads and a phone, no text.',
  '/card-images/pixel/px-infant-first-aid-before-mobile.png',
  'Pixel art first aid booklet and phone beside symbols of a newly mobile baby.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'small-object-floor-sweep',
  'Do the crawler-level sweep',
  'The floor has a new inspector',
  'Tiny Gear Shift',
  'Safety / Choking',
  'Baby (3-12 months)',
  120, 730, null, null,
  90,
  false,
  'Get down to floor level and regularly remove coins, batteries, toy parts and other small objects from reach.',
  'The object you missed is exactly the one the crawler will find first.',
  'Small objects can become choking hazards, and mobility expands reach quickly.',
  'Sweep the main play zone and check under furniture before floor time.',
  'Making every room perfect before creating one safer play zone.',
  '["Check under furniture","Separate older children''s small toys","Secure batteries and magnets"]'::jsonb,
  '["https://raisingchildren.net.au/toddlers/safety/choking-strangulation/choking-prevention"]'::jsonb,
  'Safety content. Review against current Australian guidance before production use.',
  false,
  false,
  true,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: a hand-held floor brush finding a coin-sized object beside a crawling toy and shield.',
  '/card-images/pixel/px-small-object-floor-sweep.png',
  'Pixel art floor sweep finding a small object before a baby can reach it.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'iron-rich-food-most-days',
  'Put iron on the regular menu',
  'Small serves, many options',
  'Tiny Gear Shift',
  'Feeding / Solids',
  'Baby (3-12 months)',
  180, 730, null, null,
  80,
  false,
  'From around 6 months, offer suitable iron-rich foods regularly alongside breast milk or formula.',
  'Iron-rich does not mean one special puree. Family foods can do the job in baby-safe forms.',
  'Babies'' stored iron reduces around this age while growth remains rapid.',
  'Add one age-appropriate iron-rich option such as meat, legumes, egg or iron-fortified cereal to regular meals.',
  'Getting a large portion eaten every time.',
  '["Offer varied iron-rich foods","Use a safe texture","Keep milk feeds alongside solids"]'::jsonb,
  '["https://www.pregnancybirthbaby.org.au/babies/feeding-and-nutrition/balancing-introducing-solids-with-milk-feeds"]'::jsonb,
  'Feeding content. Review against current Australian guidance before production use.',
  false,
  false,
  false,
  false,
  true,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: a colourful baby bowl with lentils, shredded meat and soft green vegetables plus a tiny strength sparkle.',
  '/card-images/pixel/px-iron-rich-food-most-days.png',
  'Pixel art bowl of varied iron-rich baby foods on a warm cream background.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'keep-allergens-in-rotation',
  'Keep tolerated allergens in rotation',
  'Introduction is not the finish line',
  'Heads Up',
  'Feeding / Allergy',
  'Baby (3-12 months)',
  180, 730, null, null,
  84,
  false,
  'Once an allergen has been introduced without a reaction, Australian guidance recommends continuing to offer it regularly in suitable forms.',
  'The tiny first taste gets the attention. The calm repeats are the real routine.',
  'Ongoing inclusion supports the recommended approach to allergy prevention.',
  'Keep tolerated allergens in the family meal rotation and seek medical advice about any reaction.',
  'Introducing several new allergens in one complicated meal.',
  '["Use an age-safe form","Repeat tolerated foods regularly","Seek urgent help for severe reaction signs"]'::jsonb,
  '["https://www.pregnancybirthbaby.org.au/babies/feeding-and-nutrition/allergy-foods"]'::jsonb,
  'Medical, allergy and feeding content. Review against current Australian guidance before production use.',
  true,
  false,
  false,
  true,
  true,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: a simple weekly circle of egg, smooth peanut paste and yoghurt icons around a baby bowl.',
  '/card-images/pixel/px-keep-allergens-in-rotation.png',
  'Pixel art egg, smooth peanut paste and yoghurt arranged around a baby bowl.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'family-food-before-salt',
  'Serve bub''s portion before the salt',
  'One pot, tiny detour',
  'Tiny Gear Shift',
  'Feeding / Family meals',
  'Baby (3-12 months)',
  180, 730, null, null,
  66,
  false,
  'When family food suits your baby, spoon out their soft portion before adding salty sauces, stock or extra salt.',
  'Baby food can be the family dinner caught one step earlier.',
  'This reduces separate cooking while keeping texture and ingredients appropriate for a baby.',
  'Pause before seasoning, remove a small portion and adapt its texture safely.',
  'Cooking a second menu every night.',
  '["Check ingredients","Serve the baby portion first","Adapt to a safe texture"]'::jsonb,
  '["https://www.pregnancybirthbaby.org.au/babies/feeding-and-nutrition/balancing-introducing-solids-with-milk-feeds"]'::jsonb,
  'Feeding content. Review against current Australian guidance before production use.',
  false,
  false,
  false,
  false,
  true,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: a family cooking pot with a small baby portion spooned out before a salt shaker.',
  '/card-images/pixel/px-family-food-before-salt.png',
  'Pixel art family meal with a baby portion served before salt is added.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'pram-tether-strap-habit',
  'Loop in before rolling out',
  'The tether strap earns its keep',
  'Tiny Gear Shift',
  'Safety / Prams',
  'Baby (3-12 months)',
  90, 730, null, null,
  74,
  false,
  'Use the pram tether strap whenever the pram is moving, as well as the brake whenever it stops.',
  'The little wrist loop is not decorative trim.',
  'The strap helps keep the pram connected to you on slopes, bumps and distracted moments.',
  'Make hand-through-strap part of taking hold of the pram.',
  'Assuming the route is too flat to need it.',
  '["Use the tether strap","Brake at stops","Follow the pram instructions"]'::jsonb,
  '["https://www.productsafety.gov.au/consumers/keep-baby-safe/move-baby-safely/prams-and-strollers-guide"]'::jsonb,
  'Safety content. Review against current Australian guidance before production use.',
  false,
  false,
  true,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: a hand looped through a pram tether strap beside one turning wheel and a shield sparkle.',
  '/card-images/pixel/px-pram-tether-strap-habit.png',
  'Pixel art hand using a pram tether strap.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'swim-lessons-not-supervision',
  'Lessons do not replace supervision',
  'Keep watch stays the rule',
  'Heads Up',
  'Safety / Water',
  'Baby (3-12 months)',
  120, 730, null, null,
  92,
  false,
  'Swimming lessons build skills, but babies and toddlers still need active adult supervision around every body of water.',
  'Water confidence is a skill, not a force field.',
  'Young children can get into difficulty quickly and quietly.',
  'Nominate the supervising adult and stay within reach around water.',
  'Assuming flotation toys or lessons can supervise for you.',
  '["Nominate one watcher","Stay within reach","Empty small water containers after use"]'::jsonb,
  '["https://www.royallifesaving.com.au/programs/keep-watch"]'::jsonb,
  'Water safety content. Review against current Australian guidance before production use.',
  false,
  false,
  true,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: bright swim goggles and a kickboard beside an alert adult chair and water shield.',
  '/card-images/pixel/px-swim-lessons-not-supervision.png',
  'Pixel art swim goggles, kickboard and supervision chair beside a water safety shield.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'spare-outfit-in-car',
  'Put the spare outfit in the car',
  'The nappy bag will forget once',
  'Tiny Gear Shift',
  'Baby / Outings',
  'Baby (3-12 months)',
  90, 545, null, null,
  44,
  false,
  'A simple size-current outfit in a zip pouch can rescue the day when the nappy bag spare has already been used.',
  'The backup needs a backup, but only one tiny one.',
  'A permanent spare removes one common reason to cut an outing short.',
  'Pack a basic outfit and set a reminder to swap sizes in a few months.',
  'A complete emergency wardrobe.',
  '["Pack one complete outfit","Use a washable pouch","Update the size seasonally"]'::jsonb,
  '[]'::jsonb,
  null,
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: a labelled-looking but text-free zip pouch with a tiny outfit tucked beside a car seat.',
  '/card-images/pixel/px-spare-outfit-in-car.png',
  'Pixel art spare baby outfit pouch stored beside a car seat.',
  'cute 8-bit pixel art item',
  'approved',
  'published',
  current_date,
  current_date + interval '12 months',
  now()
),
(
  'label-childcare-everything',
  'Label the obvious things too',
  'Bottle, hat, jumper, repeat',
  'Tiny Gear Shift',
  'Baby / Childcare',
  'Baby (3-12 months)',
  180, 730, null, null,
  48,
  false,
  'Put a durable name label or recognisable symbol on every item likely to travel through childcare.',
  'Every small blue drink bottle has an identical twin.',
  'Clear labels reduce lost gear and make busy drop-offs easier for educators and families.',
  'Label the bottle, lunch box, hat, jumper, comfort item and spare-clothes bag.',
  'A custom label for every individual sock.',
  '["Label daily essentials","Use a clear symbol","Check labels after washing"]'::jsonb,
  '[]'::jsonb,
  null,
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: a lunch box, hat and drink bottle each with matching colourful symbol stickers, no words.',
  '/card-images/pixel/px-label-childcare-everything.png',
  'Pixel art childcare items with matching symbol labels.',
  'cute 8-bit pixel art item',
  'approved',
  'published',
  current_date,
  current_date + interval '12 months',
  now()
),
(
  'messy-play-on-a-tray',
  'Put messy play on one tray',
  'Big fun, bounded splat',
  'Fun First',
  'Baby / Play',
  'Baby (3-12 months)',
  150, 730, null, null,
  42,
  false,
  'A washable tray with a tiny amount of baby-safe messy material creates sensory play without claiming the whole room.',
  'The secret ingredient is not more paint. It is a wipeable boundary.',
  'A simple setup makes experimentation easier to offer and easier to stop.',
  'Choose one washable material, one tray and an old cloth for the finish.',
  'A social-media-ready sensory table.',
  '["Use a washable tray","Offer a small amount","Keep cleanup within reach"]'::jsonb,
  '[]'::jsonb,
  null,
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: a washable tray with safe colourful finger paint, sponge shapes and a rolled-up wipe cloth.',
  '/card-images/pixel/px-messy-play-on-a-tray.png',
  'Pixel art washable messy-play tray with finger paint, sponge shapes and cloth.',
  'cute 8-bit pixel art item',
  'approved',
  'published',
  current_date,
  current_date + interval '12 months',
  now()
),
(
  'photo-backup-first-year',
  'Back up the ordinary photos',
  'The blurry ones become treasures',
  'Parent Sanity',
  'Family / Memories',
  'Baby (3-12 months)',
  0, 365, null, null,
  38,
  false,
  'Turn on an automatic photo backup and occasionally save a second copy somewhere you control.',
  'The photo you will love is often the badly lit Tuesday one.',
  'A simple backup protects a year of small moments from a lost or broken phone.',
  'Check that automatic backup is running and test that you can open a saved photo elsewhere.',
  'Sorting every image into a perfect album.',
  '["Turn on automatic backup","Check storage space","Test one restore"]'::jsonb,
  '[]'::jsonb,
  null,
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: a phone full of tiny family-photo tiles sending sparkles to a small cloud and hard drive.',
  '/card-images/pixel/px-photo-backup-first-year.png',
  'Pixel art phone backing up family photos to a cloud and hard drive.',
  'cute 8-bit pixel art item',
  'approved',
  'published',
  current_date,
  current_date + interval '12 months',
  now()
),
(
  'fussy-eating-week-view',
  'Zoom out to the whole week',
  'One beige dinner is not the story',
  'Parent Sanity',
  'Feeding / Toddlers',
  'Toddler (12-24 months)',
  365, 730, null, null,
  70,
  false,
  'Toddler appetite and variety can change from meal to meal. Looking across several days can feel more useful than judging one plate.',
  'Tuesday''s rejected pea does not receive an annual performance review.',
  'Pressure can make meals tense, while calm repeated exposure gives children chances to learn about food.',
  'Keep offering varied family foods and notice the broader pattern rather than chasing one perfect meal.',
  'Negotiating one more bite at every sitting.',
  '["Look across several days","Keep portions small","Offer without pressure"]'::jsonb,
  '["https://raisingchildren.net.au/toddlers/nutrition-fitness/common-concerns/fussy-eating"]'::jsonb,
  'Feeding content. Review against current Australian guidance before production use.',
  false,
  false,
  false,
  false,
  true,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: a seven-space meal calendar with varied tiny foods and one cheerful tick, no words or numbers.',
  '/card-images/pixel/px-fussy-eating-week-view.png',
  'Pixel art weekly meal view with a variety of tiny foods.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'family-meal-one-safe-food',
  'Add one familiar food',
  'Not a separate second dinner',
  'Tiny Gear Shift',
  'Feeding / Family meals',
  'Toddler (12-24 months)',
  365, 730, null, null,
  64,
  false,
  'At a shared meal, include one familiar food your toddler can choose alongside the rest of the family food.',
  'A familiar item can be a welcome mat, not a reward.',
  'Predictability can reduce pressure while still letting a child see and explore other foods.',
  'Put one accepted food on the table and let your toddler decide what and how much to eat from what is offered.',
  'Cooking an entirely separate meal after each refusal.',
  '["Include one familiar option","Eat together when practical","Keep the mood neutral"]'::jsonb,
  '["https://raisingchildren.net.au/toddlers/nutrition-fitness/common-concerns/fussy-eating"]'::jsonb,
  'Feeding content. Review against current Australian guidance before production use.',
  false,
  false,
  false,
  false,
  true,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: a family table with several shared dishes and one familiar plain food near a toddler plate.',
  '/card-images/pixel/px-family-meal-one-safe-food.png',
  'Pixel art family meal with a familiar food beside a toddler plate.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'grapes-popcorn-choking-check',
  'Cut the grapes, skip the popcorn',
  'Shape and texture matter',
  'Heads Up',
  'Safety / Choking',
  'Toddler (12-24 months)',
  365, 730, null, null,
  94,
  false,
  'Prepare round, firm foods such as grapes safely and avoid hard choking hazards such as popcorn for young children.',
  'Small is not always safe. A round shape can be the problem.',
  'Toddlers are still learning to chew and can choke on foods that block the airway.',
  'Cut grapes lengthways into safe pieces, seat your child to eat and supervise closely.',
  'Offering a tricky food because everyone else at the party has it.',
  '["Cut round foods lengthways","Avoid popcorn and hard lollies","Sit and supervise eating"]'::jsonb,
  '["https://raisingchildren.net.au/toddlers/safety/choking-strangulation/choking-prevention"]'::jsonb,
  'Feeding and choking safety content. Review against current Australian guidance before production use.',
  false,
  false,
  true,
  false,
  true,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: grapes being cut lengthways beside a crossed-out popcorn bowl and a safety shield.',
  '/card-images/pixel/px-grapes-popcorn-choking-check.png',
  'Pixel art grapes cut lengthways beside a crossed-out popcorn bowl.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'dummy-weaning-gently',
  'Make the dummy goodbye gradual',
  'Comfort can change in steps',
  'Parent Sanity',
  'Toddler / Sleep',
  'Toddler (12-24 months)',
  365, 730, null, null,
  54,
  false,
  'If you are ready to reduce dummy use, a calm gradual plan can start with limiting it to specific times such as sleep.',
  'It does not need to vanish in one dramatic ceremony.',
  'Predictable limits and other comfort strategies can make change easier for a toddler and parent.',
  'Choose one small limit, offer another comfort and ask your child health professional or dentist if you have concerns.',
  'Comparing your timeline with another child.',
  '["Pick one gentle first step","Add another comfort cue","Keep the boundary predictable"]'::jsonb,
  '["https://raisingchildren.net.au/toddlers/sleep/night-time-problems/dummies-helping-your-child-let-go"]'::jsonb,
  'Oral health and sleep content. Review against current Australian guidance before production use.',
  true,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: a dummy resting in a small keepsake box beside a bedtime moon and comfort toy.',
  '/card-images/pixel/px-dummy-weaning-gently.png',
  'Pixel art dummy in a keepsake box beside a moon and comfort toy.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'screens-with-a-plan',
  'Give screens a job',
  'Purpose before autoplay',
  'Parent Sanity',
  'Toddler / Screens',
  'Toddler (12-24 months)',
  365, 730, null, null,
  60,
  false,
  'Australian guidance recommends avoiding routine screen time under 2 except video calls. When screens happen, keep them purposeful and protect sleep, movement and connection.',
  'A plan is more useful than pretending the glowing rectangle does not exist.',
  'Young children learn through responsive interaction, movement and hands-on play.',
  'Choose the purpose and stopping point before starting, and watch together when practical.',
  'Turning one difficult day into a verdict on your parenting.',
  '["Decide the purpose","Set a stopping cue","Keep screens away from bedtime where possible"]'::jsonb,
  '["https://www.healthdirect.gov.au/internet-and-kids"]'::jsonb,
  'Child development and health content. Review against current Australian guidance before production use.',
  true,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: a small tablet with a timer, video-call heart and bedtime moon arranged calmly around it.',
  '/card-images/pixel/px-screens-with-a-plan.png',
  'Pixel art tablet with a timer, video-call heart and bedtime moon.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'anchor-climbing-furniture',
  'Anchor what looks climbable',
  'Drawers become a ladder',
  'Heads Up',
  'Safety / Home',
  'Toddler (12-24 months)',
  270, 730, null, null,
  96,
  false,
  'Secure unstable furniture and televisions to a wall or suitable structure before climbing begins.',
  'A toddler sees a chest of drawers and immediately understands staircase technology.',
  'Furniture tip-overs can cause severe injury, and supervision alone cannot prevent every sudden climb.',
  'Identify tall or unstable furniture, use suitable anchors and follow manufacturer guidance.',
  'Assuming a heavy item cannot fall.',
  '["Anchor furniture and televisions","Do not place tempting items on top","Keep drawers closed"]'::jsonb,
  '["https://www.productsafety.gov.au/consumers/be-safe-around-the-home/use-products-inside-the-home-safely/toppling-furniture-and-televisions-guide"]'::jsonb,
  'Safety content. Review against current Australian guidance before production use.',
  false,
  false,
  true,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: a bookcase secured to a wall with a visible anchor strap and a small shield.',
  '/card-images/pixel/px-anchor-climbing-furniture.png',
  'Pixel art bookcase fixed to a wall with a safety anchor.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'blind-cords-out-of-reach',
  'Secure every blind cord high',
  'Check the rooms you visit too',
  'Heads Up',
  'Safety / Home',
  'Toddler (12-24 months)',
  270, 730, null, null,
  98,
  false,
  'Keep curtain and blind cords secured, tensioned and well out of children''s reach, with furniture moved away from them.',
  'The cord is high until a cot, chair or toy box becomes a step.',
  'Loose looped cords can cause strangulation quickly and silently.',
  'Check every window at child height, install suitable safety devices and move climbable furniture away.',
  'Assuming a rarely used room is not part of the safety check.',
  '["Secure cords high","Remove loops","Move climbable furniture away"]'::jsonb,
  '["https://www.productsafety.gov.au/consumers/be-safe-around-the-home/use-products-inside-the-home-safely/blinds-curtains-and-window-fittings-guide"]'::jsonb,
  'Safety content. Review against current Australian guidance before production use.',
  false,
  false,
  true,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: a window blind cord secured high on a wall cleat beside a safety shield.',
  '/card-images/pixel/px-blind-cords-out-of-reach.png',
  'Pixel art window blind cord secured high and out of reach.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'driveway-hand-hold-rule',
  'Hold hands before the driveway',
  'The rule starts at the door',
  'Heads Up',
  'Safety / Roads',
  'Toddler (12-24 months)',
  365, 730, null, null,
  92,
  false,
  'Use a consistent hand-hold or secure-wait rule around driveways, car parks and roads.',
  'The safest driveway conversation happens before the front door opens.',
  'Toddlers are small, fast and not yet able to judge traffic speed or danger.',
  'Choose simple words, hold hands and physically supervise every transition near vehicles.',
  'Expecting a toddler to remember the rule while excited.',
  '["Start the rule at the door","Hold hands near vehicles","Check around the car before moving"]'::jsonb,
  '["https://raisingchildren.net.au/school-age/safety/car-pedestrian-safety/pedestrian-safety"]'::jsonb,
  'Road and driveway safety content. Review against current Australian guidance before production use.',
  false,
  false,
  true,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: an adult hand holding a small toddler hand beside a parked car and bright boundary line.',
  '/card-images/pixel/px-driveway-hand-hold-rule.png',
  'Pixel art adult and toddler holding hands beside a parked car.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'hot-drinks-high-zone',
  'Make a high zone for hot drinks',
  'Bench edge is toddler territory',
  'Tiny Gear Shift',
  'Safety / Burns',
  'Toddler (12-24 months)',
  270, 730, null, null,
  94,
  false,
  'Keep hot drinks at the back of benches and tables, away from edges, cords and a toddler''s reach.',
  'Their reach grows overnight and coffee stays hot longer than patience.',
  'Hot drinks are a common cause of serious scalds in young children.',
  'Choose one default high spot and put every hot drink there before doing anything else.',
  'Trusting a travel mug lid as the whole safety plan.',
  '["Use the back of the bench","Keep cords out of reach","Do not hold a child and hot drink together"]'::jsonb,
  '["https://raisingchildren.net.au/newborns/safety/burns-scalds-fire/scalds-prevention"]'::jsonb,
  'Burn and scald safety content. Review against current Australian guidance before production use.',
  false,
  false,
  true,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: a steaming mug placed high at the back of a bench beyond a tiny reaching hand.',
  '/card-images/pixel/px-hot-drinks-high-zone.png',
  'Pixel art hot drink placed high and away from a toddler''s reach.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'dogs-need-toddler-free-space',
  'Give the dog a toddler-free zone',
  'Rest is part of safe togetherness',
  'Heads Up',
  'Safety / Pets',
  'Toddler (12-24 months)',
  365, 730, null, null,
  86,
  false,
  'Create a place where the dog can rest, eat and move away without a toddler following.',
  'Good family dogs still need an exit door from enthusiastic love.',
  'Space and active supervision reduce stressful interactions for both child and dog.',
  'Set up a gated rest area and keep children away when the dog is eating, sleeping or has a toy.',
  'Expecting the dog to tolerate every hug or climb.',
  '["Create a child-free rest zone","Actively supervise together time","Separate around food and sleep"]'::jsonb,
  '["https://raisingchildren.net.au/newborns/safety/home-pets/dogs"]'::jsonb,
  'Pet and child safety content. Review against current Australian guidance before production use.',
  false,
  false,
  true,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: a relaxed dog on a mat behind a low gate with a water bowl and calm heart.',
  '/card-images/pixel/px-dogs-need-toddler-free-space.png',
  'Pixel art dog resting in a toddler-free space behind a low gate.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'bath-water-temperature-check',
  'Check the bath before they climb in',
  'Warm, not hot',
  'Tiny Gear Shift',
  'Safety / Bath',
  'Toddler (12-24 months)',
  365, 730, null, null,
  90,
  false,
  'Run and mix bath water carefully, check the temperature before your child enters, and keep hot taps inaccessible.',
  'Your hand check is part of bath setup, not an optional final flourish.',
  'Young skin can scald quickly, and hot water can remain in the tap or pool unevenly.',
  'Test the mixed water before every bath and stay within arm''s reach throughout.',
  'Adding toys before the temperature and supervision are sorted.',
  '["Mix and test the water","Keep the child away from taps","Stay within arm''s reach"]'::jsonb,
  '["https://raisingchildren.net.au/newborns/safety/burns-scalds-fire/scalds-prevention"]'::jsonb,
  'Bath and scald safety content. Review against current Australian guidance before production use.',
  false,
  false,
  true,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: a bath tap with a thermometer, an adult testing the water and a small shield sparkle.',
  '/card-images/pixel/px-bath-water-temperature-check.png',
  'Pixel art bath tap, thermometer and adult hand checking water temperature.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'snack-tub-by-door',
  'Keep one outing snack tub',
  'Refill it before the shoes go on',
  'Tiny Gear Shift',
  'Feeding / Outings',
  'Toddler (12-24 months)',
  365, 730, null, null,
  48,
  false,
  'A small container of familiar age-appropriate snacks by the door can make short outings easier.',
  'The emergency snack is mostly an emergency for the adults'' decision-making.',
  'A ready option reduces last-minute packing while keeping food choices suitable for your child.',
  'Choose a few safe familiar options and refresh them before leaving.',
  'Packing a full cafe menu for a trip to the playground.',
  '["Choose age-safe snacks","Check dates and storage","Offer food seated and supervised"]'::jsonb,
  '["https://raisingchildren.net.au/toddlers/nutrition-fitness/daily-food-guides/toddlers-food-groups"]'::jsonb,
  'Feeding content. Review against current Australian guidance before production use.',
  false,
  false,
  false,
  false,
  true,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: a clear snack tub by the front door with simple crackers, fruit pouch and tiny refill sparkle.',
  '/card-images/pixel/px-snack-tub-by-door.png',
  'Pixel art snack tub with simple outing foods beside the front door.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'wet-weather-door-kit',
  'Build a wet-weather door kit',
  'Rain does not cancel the wobble walk',
  'Fun First',
  'Toddler / Outings',
  'Toddler (12-24 months)',
  365, 730, null, null,
  42,
  false,
  'Gumboots, a rain layer and an old towel by the door turn a damp forecast into a low-effort outing.',
  'Puddles are free toddler programming.',
  'Reducing the setup makes fresh air and a change of scene more available on long indoor days.',
  'Put weather gear and a cleanup towel together in one basket.',
  'Keeping every item dry and spotless during the adventure.',
  '["Gumboots","Rain layer","Old towel","Dry socks for home"]'::jsonb,
  '[]'::jsonb,
  null,
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: a small doorway basket with gumboots, rain jacket and folded towel under a rain cloud.',
  '/card-images/pixel/px-wet-weather-door-kit.png',
  'Pixel art doorway basket with toddler gumboots, rain jacket and towel.',
  'cute 8-bit pixel art item',
  'approved',
  'published',
  current_date,
  current_date + interval '12 months',
  now()
),
(
  'picnic-dinner-reset',
  'Move dinner to the picnic rug',
  'Same food, different night',
  'Parent Sanity',
  'Toddler / Family fun',
  'Toddler (12-24 months)',
  365, 730, null, null,
  38,
  false,
  'When the evening is dragging, serve the ordinary dinner on a rug indoors or outside and call it a picnic.',
  'Novelty can be one metre of floor space.',
  'A tiny setting change can soften a tense evening without adding a complicated activity.',
  'Put down a washable rug and bring the normal plates over.',
  'A themed menu, decorations or photographic evidence.',
  '["Use the usual dinner","Choose an easy-clean spot","Let novelty do the work"]'::jsonb,
  '[]'::jsonb,
  null,
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: a picnic rug on the living-room floor with simple dinner plates and cheerful fairy lights.',
  '/card-images/pixel/px-picnic-dinner-reset.png',
  'Pixel art indoor picnic dinner on a rug with simple plates and fairy lights.',
  'cute 8-bit pixel art item',
  'approved',
  'published',
  current_date,
  current_date + interval '12 months',
  now()
),
(
  'first-ferry-or-train-ride',
  'Take the ride as the outing',
  'No destination attraction required',
  'Fun First',
  'Toddler / Adventures',
  'Toddler (12-24 months)',
  450, 730, null, null,
  40,
  false,
  'A short ferry or train trip can be the whole adventure, with no need to add a major destination.',
  'For a toddler, public transport is already the theme park ride.',
  'A simple return trip offers new sounds, views and routines without overloading the day.',
  'Pick a quiet time, travel a few stops and come home while it is still fun.',
  'Making the trip educational or productive.',
  '["Choose a short route","Avoid the busiest time","Pack only the basics"]'::jsonb,
  '[]'::jsonb,
  null,
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: a cheerful little ferry and train ticket beside a tiny backpack and harbour sparkle, no words.',
  '/card-images/pixel/px-first-ferry-or-train-ride.png',
  'Pixel art ferry, ticket and tiny backpack for a toddler''s first public transport adventure.',
  'cute 8-bit pixel art item',
  'approved',
  'published',
  current_date,
  current_date + interval '12 months',
  now()
),
(
  'grandparent-care-cheat-sheet',
  'Make the care cheat sheet tiny',
  'The useful bits fit on one page',
  'Tiny Gear Shift',
  'Toddler / Support',
  'Toddler (12-24 months)',
  365, 730, null, null,
  50,
  false,
  'A one-page note with routines, comfort tricks and contacts helps occasional carers without scripting every minute.',
  'Nobody needs the full parenting operating manual to cover Tuesday afternoon.',
  'Clear essentials reduce handover questions and leave room for carers to find their own rhythm.',
  'Write meal, sleep, comfort, allergy and contact essentials in plain language.',
  'Documenting every possible mood or preference.',
  '["Emergency contacts","Food and allergy essentials","Sleep cues","Favourite comfort"]'::jsonb,
  '[]'::jsonb,
  null,
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: a fridge card with nap, snack and contact icons beside reading glasses, no text.',
  '/card-images/pixel/px-grandparent-care-cheat-sheet.png',
  'Pixel art care cheat sheet with nap, snack and contact symbols beside reading glasses.',
  'cute 8-bit pixel art item',
  'approved',
  'published',
  current_date,
  current_date + interval '12 months',
  now()
),
(
  'toddler-art-inbox',
  'Give the art one inbox',
  'Keep some, photograph some, release some',
  'Parent Sanity',
  'Toddler / Memories',
  'Toddler (12-24 months)',
  365, 730, null, null,
  34,
  false,
  'One folder or tray contains incoming artwork until you choose a few pieces to keep or photograph.',
  'Not every scribble needs a lifelong storage commitment.',
  'A simple boundary preserves favourite memories without turning paper into household infrastructure.',
  'Choose one inbox and clear it at a relaxed interval.',
  'A perfect archival system with labels and dates.',
  '["Choose one folder or tray","Keep a few favourites","Photograph bulky pieces"]'::jsonb,
  '[]'::jsonb,
  null,
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: a bright folder holding three tiny toddler paintings beside a camera and recycling basket.',
  '/card-images/pixel/px-toddler-art-inbox.png',
  'Pixel art folder for toddler artwork beside a camera and recycling basket.',
  'cute 8-bit pixel art item',
  'approved',
  'published',
  current_date,
  current_date + interval '12 months',
  now()
),
(
  'clothes-two-outfits-forward',
  'Pair two outfits ahead',
  'Morning gets fewer decisions',
  'Tiny Gear Shift',
  'Toddler / Routines',
  'Toddler (12-24 months)',
  365, 730, null, null,
  36,
  false,
  'Clip or fold two complete weather-ready outfits together so the next rushed morning has an easy answer.',
  'Finding the matching clean pants is apparently a high-level dawn puzzle.',
  'A tiny preparation step removes choices when everyone is tired or late.',
  'Pair two tops, bottoms and layers after the next wash.',
  'Planning a full week of coordinated clothing.',
  '["Check the forecast","Pair two complete outfits","Include one warm layer"]'::jsonb,
  '[]'::jsonb,
  null,
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: two complete toddler outfits clipped together on hangers beneath a small morning sun.',
  '/card-images/pixel/px-clothes-two-outfits-forward.png',
  'Pixel art two complete toddler outfits prepared together on hangers.',
  'cute 8-bit pixel art item',
  'approved',
  'published',
  current_date,
  current_date + interval '12 months',
  now()
)
on conflict (slug) do update set
  title = excluded.title,
  subtitle = excluded.subtitle,
  card_type = excluded.card_type,
  category = excluded.category,
  life_stage = excluded.life_stage,
  start_age_days = excluded.start_age_days,
  end_age_days = excluded.end_age_days,
  pregnancy_week_start = excluded.pregnancy_week_start,
  pregnancy_week_end = excluded.pregnancy_week_end,
  priority = excluded.priority,
  time_critical = excluded.time_critical,
  short_summary = excluded.short_summary,
  wish_i_knew = excluded.wish_i_knew,
  why_it_matters = excluded.why_it_matters,
  what_to_do_now = excluded.what_to_do_now,
  what_can_wait = excluded.what_can_wait,
  checklist_items = excluded.checklist_items,
  source_urls = excluded.source_urls,
  source_notes = excluded.source_notes,
  medical_sensitivity = excluded.medical_sensitivity,
  government_sensitivity = excluded.government_sensitivity,
  safety_sensitivity = excluded.safety_sensitivity,
  allergy_sensitivity = excluded.allergy_sensitivity,
  feeding_sensitivity = excluded.feeding_sensitivity,
  conditions = excluded.conditions,
  illustration_prompt = excluded.illustration_prompt,
  image_url = excluded.image_url,
  image_alt = excluded.image_alt,
  image_style = excluded.image_style,
  image_status = excluded.image_status,
  status = excluded.status,
  last_reviewed_at = excluded.last_reviewed_at,
  review_due_date = excluded.review_due_date,
  published_at = excluded.published_at,
  updated_at = now();

