-- Pregnancy weekly anchor cards (weeks 1–40). Safe to re-run (upserts by slug).
-- Review and publish from /admin after adding pixel art.

insert into public.timeline_cards (
  slug, title, subtitle, card_type, category, life_stage,
  start_age_days, end_age_days, pregnancy_week_start, pregnancy_week_end,
  priority, time_critical, short_summary, wish_i_knew, why_it_matters,
  what_to_do_now, what_can_wait, checklist_items, source_urls, source_notes,
  medical_sensitivity, government_sensitivity, safety_sensitivity,
  allergy_sensitivity, feeding_sensitivity, conditions, illustration_prompt,
  image_url, image_alt, image_style, image_status, status,
  last_reviewed_at, review_due_date, published_at
) values
(
  'pregnancy-week-1',
  'Tiny beginnings',
  'Week 1 in the womb',
  'This week with bub',
  'Pregnancy / This week',
  'Pregnancy',
  null,
  null,
  1,
  1,
  100,
  false,
  'Fertilisation and early cell division happen in the first week. Most people are not tracking pregnancy this early.',
  'You might not even know yet — and that is okay. Week one is chemistry, not kicks.',
  null,
  'If you are trying to conceive, gentle habits tend to beat obsessing over every symptom.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"unborn_only":true}'::jsonb,
  'Cute pixel art collectible: gentle womb week 1 milestone, soft heart or tiny baby silhouette, warm cream and teal palette.',
  '/card-images/pixel/px-pregnancy-week-1.png',
  'Illustration for pregnancy week 1.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'pregnancy-week-2',
  'Before the test line',
  'Week 2 in the womb',
  'This week with bub',
  'Pregnancy / This week',
  'Pregnancy',
  null,
  null,
  2,
  2,
  100,
  false,
  'The body prepares for possible implantation. Home tests usually cannot detect pregnancy yet.',
  'Week two on the calendar is often before a positive test. Waiting is its own sport.',
  null,
  'Waiting to test? Picking a day and leaving the stick alone until then can spare some mental load.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"unborn_only":true}'::jsonb,
  'Cute pixel art collectible: gentle womb week 2 milestone, soft heart or tiny baby silhouette, warm cream and teal palette.',
  '/card-images/pixel/px-pregnancy-week-2.png',
  'Illustration for pregnancy week 2.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'pregnancy-week-3',
  'Implantation week',
  'Week 3 in the womb',
  'This week with bub',
  'Pregnancy / This week',
  'Pregnancy',
  null,
  null,
  3,
  3,
  100,
  false,
  'The embryo may implant in the uterine lining. Early hormone shifts begin.',
  'Some people notice implantation spotting. Many notice nothing. Both are normal.',
  null,
  'Feeling wiped out is common this early — rest when you can, without needing a perfect reason.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"unborn_only":true}'::jsonb,
  'Cute pixel art collectible: gentle womb week 3 milestone, soft heart or tiny baby silhouette, warm cream and teal palette.',
  '/card-images/pixel/px-pregnancy-week-3.png',
  'Illustration for pregnancy week 3.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'pregnancy-week-4',
  'A positive test window',
  'Week 4 in the womb',
  'This week with bub',
  'Pregnancy / This week',
  'Pregnancy',
  null,
  null,
  4,
  4,
  100,
  false,
  'Many home tests turn positive around now. A GP visit can confirm and start care planning.',
  'Two lines can feel like a plot twist. Take a breath before the to-do list explodes.',
  null,
  'Worth thinking about a GP visit if you have not had one yet — search your local practice or healthdirect for early pregnancy care.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"unborn_only":true}'::jsonb,
  'Cute pixel art collectible: gentle womb week 4 milestone, soft heart or tiny baby silhouette, warm cream and teal palette.',
  '/card-images/pixel/px-pregnancy-week-4.png',
  'Illustration for pregnancy week 4.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'pregnancy-week-5',
  'The neural tube forms',
  'Week 5 in the womb',
  'This week with bub',
  'Pregnancy / This week',
  'Pregnancy',
  null,
  null,
  5,
  5,
  100,
  false,
  'The neural tube — future brain and spine — is developing. Folic acid support matters in early pregnancy.',
  'Major structures are forming before you have told anyone. That is a lot to carry quietly.',
  null,
  'Folate comes up a lot in early pregnancy guidance — worth a quick search of Pregnancy Care Guidelines or a chat with your GP or pharmacist.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"unborn_only":true}'::jsonb,
  'Cute pixel art collectible: gentle womb week 5 milestone, soft heart or tiny baby silhouette, warm cream and teal palette.',
  '/card-images/pixel/px-pregnancy-week-5.png',
  'Illustration for pregnancy week 5.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'pregnancy-week-6',
  'Heart tissue starts',
  'Week 6 in the womb',
  'This week with bub',
  'Pregnancy / This week',
  'Pregnancy',
  null,
  null,
  6,
  6,
  100,
  false,
  'The heart begins to form and beat. Nausea and fatigue are common even when everything is progressing normally.',
  'Morning sickness may arrive like an uninvited houseguest. Small snacks help some people.',
  null,
  'Some people find a bland bite before getting up helps with nausea. Experiment gently; what works varies.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"unborn_only":true}'::jsonb,
  'Cute pixel art collectible: gentle womb week 6 milestone, soft heart or tiny baby silhouette, warm cream and teal palette.',
  '/card-images/pixel/px-pregnancy-week-6.png',
  'Illustration for pregnancy week 6.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'pregnancy-week-7',
  'Brain growth spurt',
  'Week 7 in the womb',
  'This week with bub',
  'Pregnancy / This week',
  'Pregnancy',
  null,
  null,
  7,
  7,
  100,
  false,
  'Brain development accelerates. You might feel emotional swings — hormones are real.',
  'Your uterus is still smaller than a lemon, but the growth inside is furious.',
  null,
  'If it feels right, telling one trusted person how you are actually going can take the lid off a hard week.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"unborn_only":true}'::jsonb,
  'Cute pixel art collectible: gentle womb week 7 milestone, soft heart or tiny baby silhouette, warm cream and teal palette.',
  '/card-images/pixel/px-pregnancy-week-7.png',
  'Illustration for pregnancy week 7.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'pregnancy-week-8',
  'First prenatal visit often',
  'Week 8 in the womb',
  'This week with bub',
  'Pregnancy / This week',
  'Pregnancy',
  null,
  null,
  8,
  8,
  100,
  false,
  'Many GPs refer for early ultrasound around eight to ten weeks. Limb buds are forming.',
  'The dating scan window is approaching for many — seeing something on screen can make it real.',
  null,
  'Jotting a few appointment questions on your phone helps when brain fog hits — no need for a perfect list.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"unborn_only":true}'::jsonb,
  'Cute pixel art collectible: gentle womb week 8 milestone, soft heart or tiny baby silhouette, warm cream and teal palette.',
  '/card-images/pixel/px-pregnancy-week-8.png',
  'Illustration for pregnancy week 8.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'pregnancy-week-9',
  'Moving, invisibly',
  'Week 9 in the womb',
  'This week with bub',
  'Pregnancy / This week',
  'Pregnancy',
  null,
  null,
  9,
  9,
  100,
  false,
  'Embryo becomes fetus around now. Organs keep specialising rapidly.',
  'Bub is already making tiny movements you cannot feel. Secret gymnastics.',
  null,
  'Sipping water more often can sit better than big gulps if nausea is around. Follow what your body tolerates.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"unborn_only":true}'::jsonb,
  'Cute pixel art collectible: gentle womb week 9 milestone, soft heart or tiny baby silhouette, warm cream and teal palette.',
  '/card-images/pixel/px-pregnancy-week-9.png',
  'Illustration for pregnancy week 9.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'pregnancy-week-10',
  'Critical period continues',
  'Week 10 in the womb',
  'This week with bub',
  'Pregnancy / This week',
  'Pregnancy',
  null,
  null,
  10,
  10,
  100,
  false,
  'Major organ formation continues. Risk of certain developmental issues drops as the first trimester progresses.',
  'The first trimester finish line is in sight. That does not mean symptoms vanish overnight.',
  null,
  'Double digits are quietly worth marking — a small note to yourself is enough.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"unborn_only":true}'::jsonb,
  'Cute pixel art collectible: gentle womb week 10 milestone, soft heart or tiny baby silhouette, warm cream and teal palette.',
  '/card-images/pixel/px-pregnancy-week-10.png',
  'Illustration for pregnancy week 10.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'pregnancy-week-11',
  'Almost second trimester',
  'Week 11 in the womb',
  'This week with bub',
  'Pregnancy / This week',
  'Pregnancy',
  null,
  null,
  11,
  11,
  100,
  false,
  'Bub looks more like a tiny human on scan. The placenta takes over more hormone production.',
  'Energy may start creeping back soon for some. For others, nausea lingers — both stories happen.',
  null,
  'A small treat for yourself this week is not frivolous. Growing a person is work.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"unborn_only":true}'::jsonb,
  'Cute pixel art collectible: gentle womb week 11 milestone, soft heart or tiny baby silhouette, warm cream and teal palette.',
  '/card-images/pixel/px-pregnancy-week-11.png',
  'Illustration for pregnancy week 11.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'pregnancy-week-12',
  'Fingers are separating',
  'Week 12 in the womb',
  'This week with bub',
  'Pregnancy / This week',
  'Pregnancy',
  null,
  null,
  12,
  12,
  100,
  false,
  'Around now, fingers and toes are separating. Bub is still small, but the blueprint is getting clearer every day.',
  'Those tiny hand bumps are starting to look like actual fingers — wild that this is happening while you are still in the first trimester fog.',
  null,
  'If nausea is easing, noticing one small comfort win counts. No spreadsheet required.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"unborn_only":true}'::jsonb,
  'Cute pixel art collectible: gentle womb week 12 milestone, soft heart or tiny baby silhouette, warm cream and teal palette.',
  '/card-images/pixel/px-pregnancy-week-12.png',
  'Illustration for pregnancy week 12.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'pregnancy-week-13',
  'A more defined little body',
  'Week 13 in the womb',
  'This week with bub',
  'Pregnancy / This week',
  'Pregnancy',
  null,
  null,
  13,
  13,
  100,
  false,
  'Your baby is growing quickly now. Organs keep maturing and movement is increasing, even if you cannot feel it yet.',
  'The head is still oversized (classic baby proportions), but the rest of bub is catching up.',
  null,
  'Hydration is one of those boring things that quietly helps — sip when you remember.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"unborn_only":true}'::jsonb,
  'Cute pixel art collectible: gentle womb week 13 milestone, soft heart or tiny baby silhouette, warm cream and teal palette.',
  '/card-images/pixel/px-pregnancy-week-13.png',
  'Illustration for pregnancy week 13.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'pregnancy-week-14',
  'Expressions are practising',
  'Week 14 in the womb',
  'This week with bub',
  'Pregnancy / This week',
  'Pregnancy',
  null,
  null,
  14,
  14,
  100,
  false,
  'Facial muscles are active. Many parents start feeling a little more energy as the second trimester approaches.',
  'Bub can squint and frown in there. It is practice, not commentary on your snack choices.',
  null,
  'A slow walk or stretch only if it feels good. Comfort beats pushing through.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"unborn_only":true}'::jsonb,
  'Cute pixel art collectible: gentle womb week 14 milestone, soft heart or tiny baby silhouette, warm cream and teal palette.',
  '/card-images/pixel/px-pregnancy-week-14.png',
  'Illustration for pregnancy week 14.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'pregnancy-week-15',
  'Bones are hardening',
  'Week 15 in the womb',
  'This week with bub',
  'Pregnancy / This week',
  'Pregnancy',
  null,
  null,
  15,
  15,
  100,
  false,
  'Bone development continues and bub is moving more. You might still not feel kicks — that is normal.',
  'The skeleton is shifting from soft cartilage toward bone. You are literally building a tiny human from scratch.',
  null,
  'Worth checking whether your care pathway booking is still on track — clinic websites or your GP can point you.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"unborn_only":true}'::jsonb,
  'Cute pixel art collectible: gentle womb week 15 milestone, soft heart or tiny baby silhouette, warm cream and teal palette.',
  '/card-images/pixel/px-pregnancy-week-15.png',
  'Illustration for pregnancy week 15.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'pregnancy-week-16',
  'Movement is happening',
  'Week 16 in the womb',
  'This week with bub',
  'Pregnancy / This week',
  'Pregnancy',
  null,
  null,
  16,
  16,
  100,
  false,
  'Your baby is active in the womb. First movements can feel like bubbles or gentle taps.',
  'Some parents feel the first flutters around now. Others wait weeks longer. Both are normal.',
  null,
  'Noticing when you are most still can be when first movements show up. No pressure to feel them yet.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"unborn_only":true}'::jsonb,
  'Cute pixel art collectible: gentle womb week 16 milestone, soft heart or tiny baby silhouette, warm cream and teal palette.',
  '/card-images/pixel/px-pregnancy-week-16.png',
  'Illustration for pregnancy week 16.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'pregnancy-week-17',
  'Fat stores are starting',
  'Week 17 in the womb',
  'This week with bub',
  'Pregnancy / This week',
  'Pregnancy',
  null,
  null,
  17,
  17,
  100,
  false,
  'Growth continues and the body is preparing for life outside. The morphology scan window is often coming up.',
  'Bub is beginning to lay down fat that will help with temperature regulation after birth.',
  null,
  'If a morphology scan is not booked, a quick call or online booking link can save last-minute stress.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"unborn_only":true}'::jsonb,
  'Cute pixel art collectible: gentle womb week 17 milestone, soft heart or tiny baby silhouette, warm cream and teal palette.',
  '/card-images/pixel/px-pregnancy-week-17.png',
  'Illustration for pregnancy week 17.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'pregnancy-week-18',
  'Ears are tuning in',
  'Week 18 in the womb',
  'This week with bub',
  'Pregnancy / This week',
  'Pregnancy',
  null,
  null,
  18,
  18,
  100,
  false,
  'Hearing pathways are developing. Talking or singing to your bump is less silly than it feels.',
  'Your baby can hear muffled sounds from inside your body — heartbeat, digestion, your voice nearby.',
  null,
  'Saying something out loud to the bump (partner included) is optional and oddly nice for some people.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"unborn_only":true}'::jsonb,
  'Cute pixel art collectible: gentle womb week 18 milestone, soft heart or tiny baby silhouette, warm cream and teal palette.',
  '/card-images/pixel/px-pregnancy-week-18.png',
  'Illustration for pregnancy week 18.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'pregnancy-week-19',
  'A protective coating',
  'Week 19 in the womb',
  'This week with bub',
  'Pregnancy / This week',
  'Pregnancy',
  null,
  null,
  19,
  19,
  100,
  false,
  'Skin development continues. Movements may feel stronger if you have already felt kicks.',
  'A waxy coating called vernix is forming on the skin. It protects bub in the amniotic fluid.',
  null,
  'Noting movement patterns for yourself is enough for now — counting usually comes later if your care team suggests it.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"unborn_only":true}'::jsonb,
  'Cute pixel art collectible: gentle womb week 19 milestone, soft heart or tiny baby silhouette, warm cream and teal palette.',
  '/card-images/pixel/px-pregnancy-week-19.png',
  'Illustration for pregnancy week 19.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'pregnancy-week-20',
  'Halfway there',
  'Week 20 in the womb',
  'This week with bub',
  'Pregnancy / This week',
  'Pregnancy',
  null,
  null,
  20,
  20,
  100,
  false,
  'Many parents have the morphology scan around this stage. Bub is swallowing and practising breathing movements.',
  'The halfway mark is a mindset shift more than a medical one. You have come a long way.',
  null,
  'Halfway is worth a quiet acknowledgement — cake optional.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"unborn_only":true}'::jsonb,
  'Cute pixel art collectible: gentle womb week 20 milestone, soft heart or tiny baby silhouette, warm cream and teal palette.',
  '/card-images/pixel/px-pregnancy-week-20.png',
  'Illustration for pregnancy week 20.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'pregnancy-week-21',
  'Taste buds are forming',
  'Week 21 in the womb',
  'This week with bub',
  'Pregnancy / This week',
  'Pregnancy',
  null,
  null,
  21,
  21,
  100,
  false,
  'Digestive practice continues. You might feel clearer kicks now, especially when lying down.',
  'Bub is sampling amniotic fluid and developing taste preferences before you have even introduced solids.',
  null,
  'Resting when tired without a guilt lecture is a solid move. Growing a person qualifies as work.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"unborn_only":true}'::jsonb,
  'Cute pixel art collectible: gentle womb week 21 milestone, soft heart or tiny baby silhouette, warm cream and teal palette.',
  '/card-images/pixel/px-pregnancy-week-21.png',
  'Illustration for pregnancy week 21.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'pregnancy-week-22',
  'Lips and brows appear',
  'Week 22 in the womb',
  'This week with bub',
  'Pregnancy / This week',
  'Pregnancy',
  null,
  null,
  22,
  22,
  100,
  false,
  'Your baby looks more like a tiny person on scans. Brain development is rapid.',
  'Facial features look more like a newborn every week. It can make the abstract suddenly very real.',
  null,
  'Sharing a scan photo or update with someone you trust is optional — only if you want to.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"unborn_only":true}'::jsonb,
  'Cute pixel art collectible: gentle womb week 22 milestone, soft heart or tiny baby silhouette, warm cream and teal palette.',
  '/card-images/pixel/px-pregnancy-week-22.png',
  'Illustration for pregnancy week 22.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'pregnancy-week-23',
  'Sleep cycles begin',
  'Week 23 in the womb',
  'This week with bub',
  'Pregnancy / This week',
  'Pregnancy',
  null,
  null,
  23,
  23,
  100,
  false,
  'Rest periods and active periods alternate. Movement at night is common and normal.',
  'Bub is starting to have sleep and wake patterns. They will not match yours — practice for later.',
  null,
  'If night kicks keep you awake, some parents like a pillow between the knees and slower breathing. Search sleep positions in pregnancy if you want more ideas.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"unborn_only":true}'::jsonb,
  'Cute pixel art collectible: gentle womb week 23 milestone, soft heart or tiny baby silhouette, warm cream and teal palette.',
  '/card-images/pixel/px-pregnancy-week-23.png',
  'Illustration for pregnancy week 23.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'pregnancy-week-24',
  'Viability milestone',
  'Week 24 in the womb',
  'This week with bub',
  'Pregnancy / This week',
  'Pregnancy',
  null,
  null,
  24,
  24,
  100,
  false,
  'Lungs are still developing but care for very premature babies has improved enormously. Follow your clinician''s guidance.',
  'Week 24 is often called the viability threshold — a medical label, not a prediction of your story.',
  null,
  'Saving your maternity unit contact in your phone is a small future-you favour. Ask your care team which number they prefer.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"unborn_only":true}'::jsonb,
  'Cute pixel art collectible: gentle womb week 24 milestone, soft heart or tiny baby silhouette, warm cream and teal palette.',
  '/card-images/pixel/px-pregnancy-week-24.png',
  'Illustration for pregnancy week 24.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'pregnancy-week-25',
  'Hands are busy',
  'Week 25 in the womb',
  'This week with bub',
  'Pregnancy / This week',
  'Pregnancy',
  null,
  null,
  25,
  25,
  100,
  false,
  'Coordination improves. You might see feet or hands push against your belly from inside.',
  'Bub may grab the umbilical cord or their own feet. In-womb gymnastics are underrated entertainment.',
  null,
  'Responding to a kick with a gentle touch is a tiny early conversation if you feel like it.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"unborn_only":true}'::jsonb,
  'Cute pixel art collectible: gentle womb week 25 milestone, soft heart or tiny baby silhouette, warm cream and teal palette.',
  '/card-images/pixel/px-pregnancy-week-25.png',
  'Illustration for pregnancy week 25.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'pregnancy-week-26',
  'Eyes are opening',
  'Week 26 in the womb',
  'This week with bub',
  'Pregnancy / This week',
  'Pregnancy',
  null,
  null,
  26,
  26,
  100,
  false,
  'Vision is developing. Bub may react to bright light or loud sounds.',
  'Eyelids have been fused; now they can open. Light filters through your belly dimly.',
  null,
  'A brief torch on the belly is a curiosity experiment some parents try — skip it if it feels silly.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"unborn_only":true}'::jsonb,
  'Cute pixel art collectible: gentle womb week 26 milestone, soft heart or tiny baby silhouette, warm cream and teal palette.',
  '/card-images/pixel/px-pregnancy-week-26.png',
  'Illustration for pregnancy week 26.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'pregnancy-week-27',
  'Brain grooves deepen',
  'Week 27 in the womb',
  'This week with bub',
  'Pregnancy / This week',
  'Pregnancy',
  null,
  null,
  27,
  27,
  100,
  false,
  'Third trimester is approaching. Brain growth accelerates through the rest of pregnancy.',
  'The brain is developing folds and grooves that increase surface area. Quietly impressive.',
  null,
  'A short list of who to text when labour starts can cut one decision later. Keep it rough.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"unborn_only":true}'::jsonb,
  'Cute pixel art collectible: gentle womb week 27 milestone, soft heart or tiny baby silhouette, warm cream and teal palette.',
  '/card-images/pixel/px-pregnancy-week-27.png',
  'Illustration for pregnancy week 27.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'pregnancy-week-28',
  'Third trimester begins',
  'Week 28 in the womb',
  'This week with bub',
  'Pregnancy / This week',
  'Pregnancy',
  null,
  null,
  28,
  28,
  100,
  false,
  'Many care pathways increase monitoring from here. Bub can blink and may dream during sleep.',
  'Welcome to the third trimester — the home stretch with more frequent check-ins ahead.',
  null,
  'Glancing at your next appointment date before you leave the last one is a habit many parents like.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"unborn_only":true}'::jsonb,
  'Cute pixel art collectible: gentle womb week 28 milestone, soft heart or tiny baby silhouette, warm cream and teal palette.',
  '/card-images/pixel/px-pregnancy-week-28.png',
  'Illustration for pregnancy week 28.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'pregnancy-week-29',
  'Muscles are strengthening',
  'Week 29 in the womb',
  'This week with bub',
  'Pregnancy / This week',
  'Pregnancy',
  null,
  null,
  29,
  29,
  100,
  false,
  'Your baby is gaining weight steadily. Movement matters — know your usual pattern.',
  'Kicks can feel sharper as muscles strengthen. Rib jabs are a shared parent experience.',
  null,
  'If movements feel different from your usual, your care team would rather hear from you. Search ''reduced fetal movements'' Australia for the usual guidance, and call if unsure.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"unborn_only":true}'::jsonb,
  'Cute pixel art collectible: gentle womb week 29 milestone, soft heart or tiny baby silhouette, warm cream and teal palette.',
  '/card-images/pixel/px-pregnancy-week-29.png',
  'Illustration for pregnancy week 29.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'pregnancy-week-30',
  'Lanugo may appear',
  'Week 30 in the womb',
  'This week with bub',
  'Pregnancy / This week',
  'Pregnancy',
  null,
  null,
  30,
  30,
  100,
  false,
  'Bub is practising breathing movements and swallowing. Brain and lungs keep maturing.',
  'Fine hair called lanugo sometimes covers the skin. It usually sheds before birth.',
  null,
  'Packing one hospital-bag item a week beats a panic session — whatever pace works for you.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"unborn_only":true}'::jsonb,
  'Cute pixel art collectible: gentle womb week 30 milestone, soft heart or tiny baby silhouette, warm cream and teal palette.',
  '/card-images/pixel/px-pregnancy-week-30.png',
  'Illustration for pregnancy week 30.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'pregnancy-week-31',
  'Five senses in training',
  'Week 31 in the womb',
  'This week with bub',
  'Pregnancy / This week',
  'Pregnancy',
  null,
  null,
  31,
  31,
  100,
  false,
  'Your baby responds to sound, light and touch. Weight gain continues quickly.',
  'Touch, taste, smell, hearing and sight are all developing. A full sensory lab in there.',
  null,
  'Music or reading aloud is optional; some babies seem to recognise familiar voices later.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"unborn_only":true}'::jsonb,
  'Cute pixel art collectible: gentle womb week 31 milestone, soft heart or tiny baby silhouette, warm cream and teal palette.',
  '/card-images/pixel/px-pregnancy-week-31.png',
  'Illustration for pregnancy week 31.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'pregnancy-week-32',
  'Toenails and fingernails',
  'Week 32 in the womb',
  'This week with bub',
  'Pregnancy / This week',
  'Pregnancy',
  null,
  null,
  32,
  32,
  100,
  false,
  'Bub is getting chubbier. Space is tighter, so movement may feel different — rolls more than sharp kicks.',
  'Tiny nails are forming. You will be trimming them sooner than you think.',
  null,
  'Side sleeping is commonly suggested from here if it is comfortable — check current advice with your clinician or a trusted pregnancy guide.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"unborn_only":true}'::jsonb,
  'Cute pixel art collectible: gentle womb week 32 milestone, soft heart or tiny baby silhouette, warm cream and teal palette.',
  '/card-images/pixel/px-pregnancy-week-32.png',
  'Illustration for pregnancy week 32.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'pregnancy-week-33',
  'Immune helpers arrive',
  'Week 33 in the womb',
  'This week with bub',
  'Pregnancy / This week',
  'Pregnancy',
  null,
  null,
  33,
  33,
  100,
  false,
  'The immune system prepares for the outside world. Brain development stays rapid.',
  'Antibodies from you start crossing to bub — one of the gifts of the last weeks.',
  null,
  'Washing hands before handling newborn gear is a small habit many families lean on. Hand hygiene guidance is easy to find from healthdirect.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"unborn_only":true}'::jsonb,
  'Cute pixel art collectible: gentle womb week 33 milestone, soft heart or tiny baby silhouette, warm cream and teal palette.',
  '/card-images/pixel/px-pregnancy-week-33.png',
  'Illustration for pregnancy week 33.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'pregnancy-week-34',
  'Lungs maturing',
  'Week 34 in the womb',
  'This week with bub',
  'Pregnancy / This week',
  'Pregnancy',
  null,
  null,
  34,
  34,
  100,
  false,
  'Surfactant production increases, helping lungs work after birth. Movements should stay familiar.',
  'Lungs are still the last major system to finish. Every week in counts.',
  null,
  'Reviewing warning signs with your care provider, or searching your hospital''s pregnancy advice page, can make the last stretch feel less foggy.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"unborn_only":true}'::jsonb,
  'Cute pixel art collectible: gentle womb week 34 milestone, soft heart or tiny baby silhouette, warm cream and teal palette.',
  '/card-images/pixel/px-pregnancy-week-34.png',
  'Illustration for pregnancy week 34.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'pregnancy-week-35',
  'Head may engage',
  'Week 35 in the womb',
  'This week with bub',
  'Pregnancy / This week',
  'Pregnancy',
  null,
  null,
  35,
  35,
  100,
  false,
  'Bub is gaining about 200g a week. Position varies — head down is common but not guaranteed yet.',
  'Some babies drop lower into the pelvis now. Breathing can feel easier; bladder pressure may not.',
  null,
  'Pelvic floor ideas are worth asking your clinician or physiotherapist about — they can suggest what fits you.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"unborn_only":true}'::jsonb,
  'Cute pixel art collectible: gentle womb week 35 milestone, soft heart or tiny baby silhouette, warm cream and teal palette.',
  '/card-images/pixel/px-pregnancy-week-35.png',
  'Illustration for pregnancy week 35.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'pregnancy-week-36',
  'Almost ready',
  'Week 36 in the womb',
  'This week with bub',
  'Pregnancy / This week',
  'Pregnancy',
  null,
  null,
  36,
  36,
  100,
  false,
  'Many babies are head down by now. Weekly or fortnightly checks are common in many pathways.',
  'Bub is practising sucking and swallowing for feeding after birth.',
  null,
  'A charged phone cable in the hospital bag is one of those boring items future-you tends to thank you for.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"unborn_only":true}'::jsonb,
  'Cute pixel art collectible: gentle womb week 36 milestone, soft heart or tiny baby silhouette, warm cream and teal palette.',
  '/card-images/pixel/px-pregnancy-week-36.png',
  'Illustration for pregnancy week 36.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'pregnancy-week-37',
  'Early term',
  'Week 37 in the womb',
  'This week with bub',
  'Pregnancy / This week',
  'Pregnancy',
  null,
  null,
  37,
  37,
  100,
  false,
  'Organs are nearly ready. Babbling practice and grip strength continue in the womb.',
  'From here, many babies are considered early term. Labour could still be weeks away.',
  null,
  'Knowing practice contractions versus ''call now'' signs is useful — ask your clinician, or search your maternity service''s labour guidance.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"unborn_only":true}'::jsonb,
  'Cute pixel art collectible: gentle womb week 37 milestone, soft heart or tiny baby silhouette, warm cream and teal palette.',
  '/card-images/pixel/px-pregnancy-week-37.png',
  'Illustration for pregnancy week 37.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'pregnancy-week-38',
  'Full term approaches',
  'Week 38 in the womb',
  'This week with bub',
  'Pregnancy / This week',
  'Pregnancy',
  null,
  null,
  38,
  38,
  100,
  false,
  'Movements should stay familiar. Any reduction needs a prompt call to your care team.',
  'Bub is mostly done building — now mainly gaining weight and fine-tuning.',
  null,
  'Rest, simple food, and a fuelled car if you are driving in are the gentle checklist many people keep in mind.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"unborn_only":true}'::jsonb,
  'Cute pixel art collectible: gentle womb week 38 milestone, soft heart or tiny baby silhouette, warm cream and teal palette.',
  '/card-images/pixel/px-pregnancy-week-38.png',
  'Illustration for pregnancy week 38.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'pregnancy-week-39',
  'Full term',
  'Week 39 in the womb',
  'This week with bub',
  'Pregnancy / This week',
  'Pregnancy',
  null,
  null,
  39,
  39,
  100,
  false,
  'Your baby is ready for birth in most cases. Cervical changes may be happening quietly.',
  'Full term is a window, not a deadline. Babies pick their own entrance timing.',
  null,
  'If something feels off, trusting that instinct and calling for advice is never overreacting.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"unborn_only":true}'::jsonb,
  'Cute pixel art collectible: gentle womb week 39 milestone, soft heart or tiny baby silhouette, warm cream and teal palette.',
  '/card-images/pixel/px-pregnancy-week-39.png',
  'Illustration for pregnancy week 39.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'pregnancy-week-40',
  'Due week',
  'Week 40 in the womb',
  'This week with bub',
  'Pregnancy / This week',
  'Pregnancy',
  null,
  null,
  40,
  40,
  100,
  false,
  'If you are still pregnant, monitoring continues. Induction may be discussed depending on your pathway.',
  'Due dates are estimates. Only a small fraction of babies arrive on the exact day.',
  null,
  'The waiting week is its own marathon — be kind to yourself. Induction timing, if discussed, belongs with your care team.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"unborn_only":true}'::jsonb,
  'Cute pixel art collectible: gentle womb week 40 milestone, soft heart or tiny baby silhouette, warm cream and teal palette.',
  '/card-images/pixel/px-pregnancy-week-40.png',
  'Illustration for pregnancy week 40.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
)
on conflict (slug) do update set
  title = excluded.title,
  subtitle = excluded.subtitle,
  card_type = excluded.card_type,
  category = excluded.category,
  life_stage = excluded.life_stage,
  start_age_days = excluded.start_age_days,
  end_age_days = excluded.end_age_days,
  pregnancy_week_start = excluded.pregnancy_week_start,
  pregnancy_week_end = excluded.pregnancy_week_end,
  priority = excluded.priority,
  short_summary = excluded.short_summary,
  wish_i_knew = excluded.wish_i_knew,
  what_to_do_now = excluded.what_to_do_now,
  source_notes = excluded.source_notes,
  conditions = excluded.conditions,
  illustration_prompt = excluded.illustration_prompt,
  image_alt = excluded.image_alt,
  image_style = excluded.image_style,
  -- Keep existing image_url, image_status, status, published_at on re-seed.
  updated_at = now();

