-- Wish I Knew content library batch 3: birth and recovery (6 cards).
-- Run after seed_content_library_batch2.sql. Safe to re-run (upserts by slug).
-- All cards land as in_review: review wording and verify source links in the
-- admin Content Studio, generate images, then publish.

insert into public.timeline_cards (
  slug,
  title,
  subtitle,
  card_type,
  category,
  life_stage,
  start_age_days,
  end_age_days,
  pregnancy_week_start,
  pregnancy_week_end,
  priority,
  time_critical,
  short_summary,
  wish_i_knew,
  why_it_matters,
  what_to_do_now,
  what_can_wait,
  checklist_items,
  source_urls,
  source_notes,
  medical_sensitivity,
  government_sensitivity,
  safety_sensitivity,
  allergy_sensitivity,
  feeding_sensitivity,
  conditions,
  illustration_prompt,
  image_url,
  image_alt,
  image_style,
  image_status,
  status,
  last_reviewed_at,
  review_due_date,
  published_at
) values
(
  'vaginal-birth-recovery-basics',
  'Recovery after a vaginal birth',
  'Your body did something enormous',
  'Parent Sanity',
  'Postpartum / Health',
  'Newborn (0-3 months)',
  0, 42, null, null,
  90,
  false,
  'Soreness, swelling and stitches are common after a vaginal birth. Ice packs, rest and gentle care help, and there are clear signs for when to call someone.',
  'Nobody tells you the first week is a recovery ward at home. Plan for it like one.',
  'Perineal soreness and swelling are normal for days to weeks. Knowing what is expected and what is not (worsening pain, bad-smelling discharge, fever) means you rest instead of worry, and call early when it matters.',
  'Ice packs in the first 48 hours, warm water over the area when weeing, and rest lying down when you can. Call your midwife, GP or healthdirect (1800 022 222) if pain gets worse instead of better.',
  'Any exercise beyond short gentle walks. Pelvic floor physio is brilliant but week one is about rest.',
  '["Stock ice packs or padsicles before the birth","Rest lying down, not just sitting","Know the call-someone signs: worsening pain, fever, unusual discharge","Book a pelvic health physio for later if you can"]'::jsonb,
  '["https://www.pregnancybirthbaby.org.au/recovery-after-a-vaginal-birth"]'::jsonb,
  'Medical content - review against current guidance and verify link before production use.',
  true,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: a soft cushion, a small ice pack and a steaming cup of tea with gentle sparkles.',
  null,
  'Pixel art cushion, ice pack and cup of tea on a warm cream background.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'c-section-recovery-plan',
  'Caesarean recovery is surgery recovery',
  'Six weeks, not six days',
  'Parent Sanity',
  'Postpartum / Health',
  'Newborn (0-3 months)',
  0, 56, null, null,
  90,
  false,
  'A caesarean is major abdominal surgery. Recovery takes weeks: no lifting heavier than your baby, wound care, and a doctor check before driving.',
  'A caesarean is the only major surgery where they hand you a newborn and send you home to look after it.',
  'Treating recovery seriously prevents setbacks. Lifting, stairs and driving too early can strain the wound. Most people need help at home for the first fortnight at least.',
  'Accept every offer of help and be specific: meals, washing, holding the baby while you shower. Keep the wound clean and dry, and watch for redness, oozing or fever.',
  'Driving. Check with your doctor and your car insurer about when you are covered again - commonly around six weeks, but it varies.',
  '["Nothing heavier than your baby for the first weeks","Line up help for fortnight one before the birth if planned","Check the wound daily: redness, ooze or fever means call the GP","Ask your doctor and insurer before driving again"]'::jsonb,
  '["https://www.pregnancybirthbaby.org.au/recovery-after-a-caesarean"]'::jsonb,
  'Medical content - review against current guidance and verify link before production use.',
  true,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: a heart-shaped care badge, a small water bottle and a soft blanket folded neatly.',
  null,
  'Pixel art care badge, water bottle and folded blanket on a warm cream background.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'six-week-postnatal-check',
  'The six-week check is for you too',
  'Not just a baby appointment',
  'Big Milestone',
  'Postpartum / Health',
  'Newborn (0-3 months)',
  28, 56, null, null,
  85,
  true,
  'Around six weeks, a GP checks your recovery, mood and contraception options, and usually your baby at the same visit. Book it around week four.',
  'The six-week check is the appointment where someone finally asks how YOU are - if you book it.',
  'It covers wound or perineal healing, bleeding, mental health screening and contraception, plus the baby check. Skipping it means small problems get found late. And you never need to wait for six weeks if something feels wrong now.',
  'Book the appointment around week four so you get a slot near week six. Write down your questions - sleep deprivation eats them otherwise.',
  'Having it all together by then. The check is a check-in, not an exam you can fail.',
  '["Book with your GP around week four","Note down questions as they occur to you","Be honest in the mood questions - they are there to help","Do not wait for week six if you are worried earlier"]'::jsonb,
  '["https://www.pregnancybirthbaby.org.au/postnatal-checks-and-care"]'::jsonb,
  'Medical content - review against current guidance and verify link before production use.',
  true,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: a friendly clipboard with a heart checkbox and a small calendar showing week six.',
  null,
  'Pixel art clipboard with heart checkbox and small calendar on a warm cream background.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'partner-role-during-labour',
  'Partners: your labour job description',
  'Support crew, snack mule, advocate',
  'Heads Up',
  'Birth / Planning',
  'Pregnancy',
  null, null, 32, 40,
  75,
  false,
  'Partners do best in labour with a clear job: know the birth preferences, handle logistics, keep snacks and phone chargers flowing, and speak up when asked to.',
  'You cannot take the contractions, but you can take literally everything else off the list.',
  'Labour goes better for everyone when the labouring person only has to labour. A partner who knows the preferences and the hospital route is calm, and calm is contagious.',
  'Read the birth preferences together. Pack your own small bag: snacks, water, charger, a jumper. Know where to park at 3am and which entrance is open.',
  'A perfect script. Your presence and the snacks matter more than saying the right thing.',
  '["Read the birth preferences together before week 36","Pack a partner bag: snacks, charger, jumper","Do a 3am-entrance dry run of the hospital route","Agree on a phrase that means please advocate for me now"]'::jsonb,
  '["https://www.pregnancybirthbaby.org.au/labour-and-birth-tips-for-partners"]'::jsonb,
  'Verify link during review.',
  false,
  false,
  false,
  false,
  false,
  '{"unborn_only":true}'::jsonb,
  'Cute pixel art collectible: a small backpack with a water bottle, muesli bar and phone charger cable peeking out.',
  null,
  'Pixel art backpack with snacks and a charger cable on a warm cream background.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'first-24-hours-at-home',
  'The first 24 hours at home',
  'From staffed ward to just you',
  'Heads Up',
  'Newborn / Care',
  'Newborn (0-3 months)',
  0, 7, null, null,
  88,
  false,
  'Coming home is a cliff: no midwife button, feeds every two to three hours, and a baby who slept in hospital deciding not to. Lower the bar to feed, sleep, safety.',
  'The hospital had a button that summoned a professional. Home has you, and that turns out to be enough.',
  'The first night home is famously hard because day-two-or-three babies feed constantly and everyone is exhausted. Knowing that this is normal, and who to call, turns panic into a long night instead of a crisis.',
  'One job today: feeds in, nappies out, everyone sleeps when possible. Save healthdirect (1800 022 222) and your hospital ward number - many maternity wards take calls from recent patients.',
  'Visitors, tidying, thank-you messages, and any parenting decision that is not about today.',
  '["Save healthdirect 1800 022 222 and your ward number","Aim for feed, sleep, safety - nothing else counts today","Expect a wakeful, feed-heavy first night - it is normal","Put a no-visitors buffer on day one if you can"]'::jsonb,
  '["https://www.pregnancybirthbaby.org.au/baby-first-24-hours", "https://raisingchildren.net.au/newborns/health-daily-care"]'::jsonb,
  'Medical-adjacent content - review and verify links before production use.',
  true,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: a little house with a warm glowing window and a tiny crescent moon above it.',
  null,
  'Pixel art house with a glowing window under a crescent moon on a warm cream background.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'milk-coming-in-day-three',
  'Day three: milk, and maybe tears',
  'Hormones have a schedule of their own',
  'Heads Up',
  'Newborn / Feeding',
  'Newborn (0-3 months)',
  1, 7, null, null,
  82,
  false,
  'Around day two to five, milk typically comes in and hormones shift hard. Engorgement and a teary emotional dip are both common and usually brief.',
  'Nobody schedules the day-three cry, but almost everyone attends.',
  'The hormonal drop after birth is real and steep, and it often lands the same day as engorgement. Knowing both are coming - whatever your feeding plan - makes them events, not emergencies. If low mood lasts beyond a fortnight, that is a talk-to-someone sign, not a toughen-up sign.',
  'Warm shower or cloth for comfort, feed or express for relief if breastfeeding, and let the tears happen. The ABA helpline (1800 686 268) runs 24/7 for feeding questions of any kind.',
  'Judging your feeding journey by this week. Day three is the worst possible data point.',
  '["Expect fullness or engorgement around day two to five","Expect an emotional dip - it is hormonal and common","Save the ABA helpline: 1800 686 268","Low mood beyond two weeks: mention it to your GP or nurse"]'::jsonb,
  '["https://www.pregnancybirthbaby.org.au/breast-engorgement", "https://www.breastfeeding.asn.au/"]'::jsonb,
  'Feeding content - keep wording inclusive of all feeding methods. Review and verify links before production use.',
  true,
  false,
  false,
  false,
  true,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: a small calendar showing day three with a tiny raincloud and a warm sun peeking behind it.',
  null,
  'Pixel art calendar with a raincloud and sun on a warm cream background.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
)
on conflict (slug) do update set
  title = excluded.title,
  subtitle = excluded.subtitle,
  card_type = excluded.card_type,
  category = excluded.category,
  life_stage = excluded.life_stage,
  start_age_days = excluded.start_age_days,
  end_age_days = excluded.end_age_days,
  pregnancy_week_start = excluded.pregnancy_week_start,
  pregnancy_week_end = excluded.pregnancy_week_end,
  priority = excluded.priority,
  time_critical = excluded.time_critical,
  short_summary = excluded.short_summary,
  wish_i_knew = excluded.wish_i_knew,
  why_it_matters = excluded.why_it_matters,
  what_to_do_now = excluded.what_to_do_now,
  what_can_wait = excluded.what_can_wait,
  checklist_items = excluded.checklist_items,
  source_urls = excluded.source_urls,
  source_notes = excluded.source_notes,
  medical_sensitivity = excluded.medical_sensitivity,
  government_sensitivity = excluded.government_sensitivity,
  safety_sensitivity = excluded.safety_sensitivity,
  allergy_sensitivity = excluded.allergy_sensitivity,
  feeding_sensitivity = excluded.feeding_sensitivity,
  conditions = excluded.conditions,
  illustration_prompt = excluded.illustration_prompt,
  image_url = excluded.image_url,
  image_alt = excluded.image_alt,
  image_style = excluded.image_style,
  image_status = excluded.image_status,
  status = excluded.status,
  last_reviewed_at = excluded.last_reviewed_at,
  review_due_date = excluded.review_due_date,
  updated_at = now();
