-- Wish I Knew content library batch 2 (50 cards).
-- Run after seed_content_library.sql. Safe to re-run (upserts by slug).

insert into public.timeline_cards (
  slug,
  title,
  subtitle,
  card_type,
  category,
  life_stage,
  start_age_days,
  end_age_days,
  pregnancy_week_start,
  pregnancy_week_end,
  priority,
  time_critical,
  short_summary,
  wish_i_knew,
  why_it_matters,
  what_to_do_now,
  what_can_wait,
  checklist_items,
  source_urls,
  source_notes,
  medical_sensitivity,
  government_sensitivity,
  safety_sensitivity,
  allergy_sensitivity,
  feeding_sensitivity,
  conditions,
  illustration_prompt,
  image_url,
  image_alt,
  image_style,
  image_status,
  status,
  last_reviewed_at,
  review_due_date,
  published_at
) values
(
  'folate-and-iron-early',
  'Folate and iron in early pregnancy',
  'The supplements conversation',
  'Heads Up',
  'Pregnancy / Health',
  'Pregnancy',
  null, null, 5, 12,
  88,
  false,
  'Most Australian GPs recommend folic acid before and during early pregnancy, and will check iron as part of routine bloods.',
  'The supplement chat is boring but it is one of the few things you can actually do in the fog of the first trimester.',
  'Folate supports neural tube development in very early pregnancy. Iron deficiency is common and can leave you exhausted on top of pregnancy tiredness.',
  'Take any GP-prescribed supplements and note when you started them.',
  'Every brand and gummy variant on the pharmacy shelf.',
  '["Confirm folate with your GP","Book early bloods if not done","Set a daily reminder for supplements"]'::jsonb,
  '["https://www.pregnancybirthbaby.org.au/vitamin-and-mineral-supplements-during-pregnancy"]'::jsonb,
  'Medical content - review against current guidance before production use.',
  true,
  false,
  false,
  false,
  false,
  '{"unborn_only":true}'::jsonb,
  'Cute pixel art collectible: a friendly prenatal vitamin bottle and small iron tablet with gentle sparkles.',
  '/card-images/pixel/px-folate-and-iron-early.png',
  'Pixel art prenatal vitamin bottle and iron tablet on a warm cream background.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'dental-check-during-pregnancy',
  'A dental check while pregnant',
  'Safe, free-ish, often forgotten',
  'Heads Up',
  'Pregnancy / Health',
  'Pregnancy',
  null, null, 10, 24,
  70,
  false,
  'Routine dental care is generally safe in pregnancy and gum health can shift with hormones.',
  'Pregnancy is not a reason to skip the dentist - it is sometimes a reason to go sooner.',
  'Hormonal changes can make gums more sensitive. Treating problems early avoids pain and antibiotics later.',
  'Book a check-up and tell them you are pregnant.',
  'Cosmetic work you do not need right now.',
  '["Book a dental check","Tell the clinic your due date","Keep up gentle brushing even if gums bleed a little"]'::jsonb,
  '["https://www.pregnancybirthbaby.org.au/oral-health-during-pregnancy"]'::jsonb,
  'Medical content - review against current guidance before production use.',
  true,
  false,
  false,
  false,
  false,
  '{"unborn_only":true}'::jsonb,
  'Cute pixel art collectible: a cute toothbrush and tiny dental mirror with a small gum leaf accent.',
  '/card-images/pixel/px-dental-check-during-pregnancy.png',
  'Pixel art toothbrush and dental mirror on a warm cream background.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'glucose-tolerance-test',
  'The glucose tolerance test',
  'Around 24 to 28 weeks',
  'Big Milestone',
  'Pregnancy / Health',
  'Pregnancy',
  null, null, 24, 28,
  85,
  false,
  'Most pregnancies include screening for gestational diabetes between 24 and 28 weeks.',
  'The drink is fine. The waiting room boredom is the hard part.',
  'Gestational diabetes is common and manageable when picked up. Screening helps protect you and bub.',
  'When your clinic books the test, ask about fasting and timing.',
  'Googling horror stories the night before.',
  '["Confirm GTT booking window with your clinic","Ask about fasting instructions","Bring a snack for after"]'::jsonb,
  '["https://www.pregnancybirthbaby.org.au/glucose-tolerance-test"]'::jsonb,
  'Medical content - review against current guidance before production use.',
  true,
  false,
  false,
  false,
  false,
  '{"unborn_only":true}'::jsonb,
  'Cute pixel art collectible: a friendly juice cup with calendar sticker and soft bandage sticker, no needle.',
  '/card-images/pixel/px-glucose-tolerance-test.png',
  'Pixel art glucose screening juice cup with calendar sticker, no needle.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'group-b-strep-swab',
  'Group B strep swab',
  'Late pregnancy, simple test',
  'Heads Up',
  'Pregnancy / Health',
  'Pregnancy',
  null, null, 35, 37,
  82,
  false,
  'A quick swab around 35 to 37 weeks checks for group B strep, which affects labour antibiotics planning.',
  'This swab sounds dramatic and is really just a routine checkbox before birth.',
  'If positive, antibiotics in labour reduce transmission risk to baby. Knowing ahead helps your birth team plan.',
  'Ask when your care provider does the swab and how results reach you.',
  'Stressing about the result before it exists.',
  '["Confirm swab timing with your clinic","Know how results are communicated"]'::jsonb,
  '["https://www.pregnancybirthbaby.org.au/group-b-streptococcal-gbs-infection"]'::jsonb,
  'Medical content - review against current guidance before production use.',
  true,
  false,
  false,
  false,
  false,
  '{"unborn_only":true}'::jsonb,
  'Cute pixel art collectible: a gentle swab kit box with heart sticker and soft teal accents.',
  '/card-images/pixel/px-group-b-strep-swab.png',
  'Pixel art gentle swab kit with heart sticker on cream background.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'antenatal-classes',
  'Antenatal classes exist',
  'Hospital, online, or private',
  'Heads Up',
  'Pregnancy / Planning',
  'Pregnancy',
  null, null, 24, 34,
  75,
  false,
  'Birth and early parenting classes run through hospitals, online, and private educators. Book before they fill.',
  'Classes are less about perfect technique and more about demystifying the hospital room.',
  'Knowing where to park, what labour might look like, and basic newborn care reduces first-night panic.',
  'Search your hospital or birth centre for class dates and book one that fits.',
  'Becoming a birth expert before your first contraction.',
  '["Find hospital or online class dates","Book a session","Add partner or support person"]'::jsonb,
  '["https://www.pregnancybirthbaby.org.au/antenatal-classes"]'::jsonb,
  'Review against current state hospital offerings before production use.',
  false,
  false,
  false,
  false,
  false,
  '{"unborn_only":true}'::jsonb,
  'Cute pixel art collectible: stacked baby care books with tiny notebook and pen.',
  '/card-images/pixel/px-antenatal-classes.png',
  'Pixel art stack of antenatal class books on cream background.',
  'cute 8-bit pixel art item',
  'approved',
  'published',
  current_date,
  current_date + interval '12 months',
  now()
),
(
  'employer-maternity-chat',
  'Talk to your employer early',
  'Leave, handover, flexibility',
  'Admin Trap',
  'Work / Leave',
  'Pregnancy',
  null, null, 18, 30,
  78,
  false,
  'Parental leave rules, notice periods, and flexible return conversations go better with early, plain-language planning.',
  'HR has done this before. You have not. That is okay.',
  'Knowing your entitlements and timelines reduces stress and protects income during leave.',
  'Read your award or contract and book a low-drama chat with HR or your manager.',
  'Final leave dates before you are ready.',
  '["Check paid parental leave eligibility","Read employer leave policy","Book a planning conversation"]'::jsonb,
  '["https://www.servicesaustralia.gov.au/parental-leave-pay"]'::jsonb,
  'Government and workplace wording - review before production use.',
  false,
  true,
  false,
  false,
  false,
  '{"unborn_only":true}'::jsonb,
  'Cute pixel art collectible: desk calendar and takeaway coffee cup with friendly sticky note.',
  '/card-images/pixel/px-employer-maternity-chat.png',
  'Pixel art calendar and coffee cup for maternity planning chat.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'pelvic-floor-pregnancy',
  'Pelvic floor care starts now',
  'Not just a post-birth fix',
  'Heads Up',
  'Pregnancy / Health',
  'Pregnancy',
  null, null, 14, 40,
  72,
  false,
  'Pelvic floor exercises during pregnancy can help recovery and comfort. A women''s health physio can guide you.',
  'Pelvic floor work is unglamorous and genuinely useful.',
  'Pregnancy and birth load the pelvic floor. Gentle strengthening and learning correct technique pays off later.',
  'Ask your GP or midwife about safe exercises or a physio referral.',
  'Perfect technique on day one.',
  '["Ask about pelvic floor exercises","Consider a women''s health physio","Practice little and often"]'::jsonb,
  '["https://www.pregnancybirthbaby.org.au/pelvic-floor-exercises"]'::jsonb,
  'Medical content - review against current guidance before production use.',
  true,
  false,
  false,
  false,
  false,
  '{"unborn_only":true}'::jsonb,
  'Cute pixel art collectible: rolled soft yoga mat with small flower and gentle sparkle.',
  '/card-images/pixel/px-pelvic-floor-pregnancy.png',
  'Pixel art rolled yoga mat for pelvic floor exercises.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'pregnancy-nausea-normal',
  'Morning sickness is common',
  'All-day sickness counts too',
  'Parent Sanity',
  'Pregnancy / Health',
  'Pregnancy',
  null, null, 6, 16,
  80,
  false,
  'Nausea in early pregnancy is common. Severe vomiting needs medical review, but mild nausea is often manageable.',
  'Crackers on the bedside table are a legitimate medical strategy.',
  'Knowing what is typical helps you cope. Hyperemesis and dehydration need treatment, not toughing it out alone.',
  'Eat small, bland snacks and sip fluids. Call your care provider if you cannot keep fluids down.',
  'Cooking elaborate meals you cannot smell.',
  '["Stock bland snacks","Sip fluids through the day","Call your GP if vomiting is severe"]'::jsonb,
  '["https://www.pregnancybirthbaby.org.au/morning-sickness"]'::jsonb,
  'Medical content - review against current guidance before production use.',
  true,
  false,
  false,
  false,
  false,
  '{"unborn_only":true}'::jsonb,
  'Cute pixel art collectible: ginger tea mug and plain crackers on a small plate.',
  '/card-images/pixel/px-pregnancy-nausea-normal.png',
  'Pixel art ginger tea and crackers for pregnancy nausea.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'birth-preferences-draft',
  'Draft birth preferences, not a script',
  'Flexible beats perfect',
  'Heads Up',
  'Birth / Planning',
  'Pregnancy',
  null, null, 30, 38,
  74,
  false,
  'A one-page note on pain relief, support people, and preferences helps your team - without pretending birth is predictable.',
  'Birth plans work best as conversation starters, not contracts.',
  'Clear preferences reduce repeated questions in labour. Flexibility reduces disappointment when plans shift.',
  'Jot a few priorities and discuss them at your next appointment.',
  'A laminated twelve-page manifesto.',
  '["List top three priorities","Discuss with your partner or support person","Share with your birth team"]'::jsonb,
  '["https://www.pregnancybirthbaby.org.au/birth-plan"]'::jsonb,
  'Review wording against current birth education guidance.',
  false,
  false,
  false,
  false,
  false,
  '{"unborn_only":true}'::jsonb,
  'Cute pixel art collectible: clipboard with heart sticker, pen and soft milestone flag.',
  '/card-images/pixel/px-birth-preferences-draft.png',
  'Pixel art clipboard for birth preferences draft.',
  'cute 8-bit pixel art item',
  'approved',
  'published',
  current_date,
  current_date + interval '12 months',
  now()
),
(
  'when-labour-starts-call',
  'Know when to call your birth team',
  'Contractions, waters, reduced movement',
  'Heads Up',
  'Birth / Safety',
  'Pregnancy',
  null, null, 34, 42,
  90,
  false,
  'Your hospital or midwife will tell you when to come in. Reduced baby movement always warrants a call.',
  'The triage nurse has heard every "is this labour?" question and will not think yours is silly.',
  'Clear thresholds reduce dangerous delay. Most early labour can stay home until active labour patterns appear.',
  'Save the after-hours birth unit number and ask what signs they want reported.',
  'Timing every twinge from week 34.',
  '["Save birth unit number","Ask about movement reduction protocol","Know your hospital parking at night"]'::jsonb,
  '["https://www.pregnancybirthbaby.org.au/signs-of-labour"]'::jsonb,
  'Safety content - review against current guidance before production use.',
  true,
  false,
  true,
  false,
  false,
  '{"unborn_only":true}'::jsonb,
  'Cute pixel art collectible: phone beside small overnight hospital bag with moon and star accents.',
  '/card-images/pixel/px-when-labour-starts-call.png',
  'Pixel art phone and hospital bag for when labour starts.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'umbilical-cord-care',
  'Umbilical cord care is simple',
  'Keep dry, watch for redness',
  'Heads Up',
  'Newborn / Health',
  'Newborn (0-3 months)',
  0, 14, null, null,
  85,
  false,
  'The cord stump dries and falls off in one to three weeks. Keep it clean and dry.',
  'The little clamp looks alarming and the stump is weirder than anyone mentions.',
  'Most stumps heal without trouble. Redness, smell, or bleeding needs a review.',
  'Fold nappies below the stump and give sponge baths until it falls off.',
  'Pulling at it when it is hanging by a thread.',
  '["Keep stump dry","Fold nappy away from cord","Call nurse or GP if it looks infected"]'::jsonb,
  '["https://www.pregnancybirthbaby.org.au/umbilical-cord-care"]'::jsonb,
  'Medical content - review against current guidance before production use.',
  true,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: newborn onesie fold with tiny nappy and cotton bud, gentle and clean.',
  '/card-images/pixel/px-umbilical-cord-care.png',
  'Pixel art newborn onesie and cord care essentials.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'newborn-poo-colours',
  'Newborn poo colours change',
  'Black to yellow is normal',
  'Heads Up',
  'Newborn / Feeding',
  'Newborn (0-3 months)',
  0, 30, null, null,
  70,
  false,
  'Meconium, then mustardy breastfed poo or paste-like formula poo. Frequency varies wildly.',
  'You will become an unexpected expert in stool. This is parenting.',
  'Most changes are normal. Blood, white, or persistent watery poo with illness signs needs review.',
  'Notice patterns but do not panic about hourly variations.',
  'Comparing with Instagram-perfect nappy shots.',
  '["Know what is typical for your feeding method","Ask child health nurse at first visit"]'::jsonb,
  '["https://www.pregnancybirthbaby.org.au/baby-poo"]'::jsonb,
  'Feeding content - review before production use.',
  false,
  false,
  false,
  false,
  true,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: cute nappy with friendly harmless colour swatch cards, not gross.',
  '/card-images/pixel/px-newborn-poo-colours.png',
  'Pixel art nappy with gentle colour guide swatches.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'visitor-boundaries-newborn',
  'You can set visitor boundaries',
  'No is a complete sentence',
  'Parent Sanity',
  'Newborn / Family',
  'Newborn (0-3 months)',
  0, 28, null, null,
  88,
  false,
  'Short visits, hand hygiene, and no sick guests protect a newborn and protect your recovery.',
  'Everyone wants cuddles. You are allowed to hoard the baby for a bit.',
  'Over-tired parents and crowded rooms make early weeks harder. Boundaries are care.',
  'Agree on a simple message with your partner: visiting hours, length, and health rules.',
  'Hosting a welcome party.',
  '["Set visiting hours","Ask sick guests to reschedule","Keep hand sanitiser by the door"]'::jsonb,
  '["https://raisingchildren.net.au/newborns/health-daily-care/hand-washing"]'::jsonb,
  'Review against current health guidance.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: front door wreath with hand sanitiser bottle and soft welcome vibe.',
  '/card-images/pixel/px-visitor-boundaries-newborn.png',
  'Pixel art door wreath and hand sanitiser for visitor boundaries.',
  'cute 8-bit pixel art item',
  'approved',
  'published',
  current_date,
  current_date + interval '12 months',
  now()
),
(
  'cluster-feeding-evenings',
  'Cluster feeding is normal',
  'Especially evenings',
  'Parent Sanity',
  'Newborn / Feeding',
  'Newborn (0-3 months)',
  0, 42, null, null,
  86,
  false,
  'Many babies feed frequently in the evening. It does not automatically mean low supply.',
  'The witching hour is real and it is not because you are doing it wrong.',
  'Understanding cluster feeding reduces unnecessary formula top-ups and parental self-blame.',
  'Set up a couch nest: water, snacks, remote, and help if possible.',
  'Solving evenings with a complex schedule on day five.',
  '["Expect frequent evening feeds","Ask feeding support if worried","Lower dinner expectations"]'::jsonb,
  '["https://www.pregnancybirthbaby.org.au/cluster-feeding"]'::jsonb,
  'Feeding content - review before production use.',
  false,
  false,
  false,
  false,
  true,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: cozy couch corner with feeding pillow and warm dim lamp glow.',
  '/card-images/pixel/px-cluster-feeding-evenings.png',
  'Pixel art couch with feeding pillow for cluster feeding evenings.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'first-home-nurse-visit',
  'The first home nurse visit',
  'Free, practical, underrated',
  'Big Milestone',
  'Newborn / Health',
  'Newborn (0-3 months)',
  0, 14, null, null,
  92,
  false,
  'Child and family health nurses often visit at home early on. They weigh bub, check you, and answer small questions.',
  'No question is too small for the nurse. That is literally the job.',
  'Early checks catch feeding, jaundice, and recovery issues while they are easy to fix.',
  'Have your health book ready and write down three questions beforehand.',
  'Deep cleaning the house.',
  '["Have health record book ready","Write three questions","Ask about local clinic timetable"]'::jsonb,
  '["https://www.pregnancybirthbaby.org.au/child-and-family-health-nurse"]'::jsonb,
  'Review state service names before production use.',
  true,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: friendly child health nurse bag with baby scale sticker and notebook.',
  '/card-images/pixel/px-first-home-nurse-visit.png',
  'Pixel art child health nurse visit bag.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'postpartum-bleeding-normal',
  'Postpartum bleeding is normal',
  'Lochia for weeks',
  'Heads Up',
  'Postpartum / Health',
  'Newborn (0-3 months)',
  0, 42, null, null,
  84,
  false,
  'Bleeding after birth can last weeks and changes colour over time. Soaking pads quickly or large clots need review.',
  'Maternity pads are not optional extras. Buy more than you think.',
  'Knowing typical recovery helps you rest. Heavy bleeding or fever needs urgent care.',
  'Stock pads and rest when you can. Call if bleeding soaks a pad in an hour.',
  'Tampons until your care provider says it is okay.',
  '["Stock maternity pads","Know red-flag bleeding signs","Rest horizontally when offered"]'::jsonb,
  '["https://www.pregnancybirthbaby.org.au/bleeding-after-birth"]'::jsonb,
  'Medical content - review against current guidance before production use.',
  true,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: stack of maternity pads with warm tea cup, calm and practical.',
  '/card-images/pixel/px-postpartum-bleeding-normal.png',
  'Pixel art maternity pads and tea cup for postpartum recovery.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'postnatal-mental-health',
  'Check in on mental health',
  'Yours, not just bub''s',
  'Parent Sanity',
  'Postpartum / Mental health',
  'Newborn (0-3 months)',
  0, 90, null, null,
  95,
  false,
  'Anxiety and low mood after birth are common and treatable. PANDA and your GP are good first calls.',
  'Bad weeks are not the same as failing. Help is a phone call, not an admission of defeat.',
  'Early support protects bonding, safety, and recovery. Partners can struggle too.',
  'Save PANDA''s helpline and tell someone honestly how you are sleeping and feeling.',
  'Waiting until you are "sure" it is bad enough.',
  '["Save PANDA helpline 1300 726 306","Tell GP or nurse at check-up","Accept one practical offer of help"]'::jsonb,
  '["https://www.panda.org.au/","https://www.pregnancybirthbaby.org.au/postnatal-depression"]'::jsonb,
  'Sensitive mental health content - review wording before production use.',
  true,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: two mugs and soft blanket with gentle moonlit window hint.',
  '/card-images/pixel/px-postnatal-mental-health.png',
  'Pixel art mugs and blanket for postnatal mental health support.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'partner-support-newborn',
  'Partners need support too',
  'Not the spare adult',
  'Parent Sanity',
  'Family / Relationship',
  'Newborn (0-3 months)',
  0, 90, null, null,
  76,
  false,
  'Non-birthing partners often carry logistics while grieving their old life and feeling useless at 3am.',
  'The best partner move is often dishes, not advice.',
  'Supported partners support primary carers. Relationship strain in this window is common, not fatal.',
  'Assign one repeating job to your partner: meals, bath, or night nappy.',
  'Perfect co-parenting symmetry in week two.',
  '["One repeating task for partner","Five-minute daily check-in","Lower household standards together"]'::jsonb,
  '["https://raisingchildren.net.au/grown-ups/partners/supporting-each-other"]'::jsonb,
  'Review inclusive wording for solo parents in UI.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: two coffee cups and shared nappy stack as teamwork symbol.',
  '/card-images/pixel/px-partner-support-newborn.png',
  'Pixel art two coffee cups and nappies for partner support.',
  'cute 8-bit pixel art item',
  'approved',
  'published',
  current_date,
  current_date + interval '12 months',
  now()
),
(
  'tummy-time-from-start',
  'Tummy time from the start',
  'Minutes count',
  'Heads Up',
  'Development',
  'Newborn (0-3 months)',
  0, 120, null, null,
  74,
  false,
  'Short supervised tummy time sessions build neck strength. Start on your chest if the floor feels hard.',
  'Thirty seconds of tummy time counts. You do not need a timer and a gym mat.',
  'Regular tummy time supports motor development and head shape.',
  'Try one or two minutes on your chest after a nappy change.',
  'Fancy play gyms.',
  '["Try tummy time on your chest","Stay within arm''s reach","Stop if bub is upset and retry later"]'::jsonb,
  '["https://raisingchildren.net.au/babies/play-learning/play-ideas/tummy-time"]'::jsonb,
  'Development content - review before production use.',
  true,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: colorful baby play mat with small rattle toy and sparkle.',
  '/card-images/pixel/px-tummy-time-from-start.png',
  'Pixel art baby play mat for tummy time.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'newborn-bath-optional',
  'Daily baths are optional',
  'Top and tail works',
  'Tiny Gear Shift',
  'Newborn / Care',
  'Newborn (0-3 months)',
  0, 30, null, null,
  55,
  false,
  'Newborns do not need a full bath every day. Face, neck, and nappy area cleaning is often enough.',
  'The first bath is a photo op, not a hygiene emergency.',
  'Over-bathing can dry skin. Simple care reduces fuss.',
  'Use a warm washer for face, neck folds, and nappy area.',
  'Elaborate bath routines nightly.',
  '["Warm washer ready","Bath only when you want to","Moisturiser if skin is dry"]'::jsonb,
  '["https://raisingchildren.net.au/babies/health-daily-care/hygiene-bathing/bathing"]'::jsonb,
  'Review before production use.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: tiny rubber duck and soft washcloth with warm bubbles.',
  '/card-images/pixel/px-newborn-bath-optional.png',
  'Pixel art rubber duck and washcloth for newborn bath.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'white-noise-sleep',
  'White noise can help sleep',
  'Safe volume, away from head',
  'Tiny Gear Shift',
  'Sleep',
  'Newborn (0-3 months)',
  0, 120, null, null,
  68,
  false,
  'Continuous low white noise can soothe some babies. Keep volume moderate and place the source away from the cot.',
  'The shower running was your first white noise machine.',
  'Used safely, white noise can extend naps. Too loud or too close can harm hearing.',
  'If trying white noise, keep it at conversation level and across the room.',
  'Expensive branded machines before testing a fan or app.',
  '["Keep volume moderate","Place source away from cot","Turn off when not needed"]'::jsonb,
  '["https://www.rednose.org.au/article/white-noise"]'::jsonb,
  'Safety content - review Red Nose guidance before production use.',
  false,
  false,
  true,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: cute sound machine with moon, stars and soft cloud.',
  '/card-images/pixel/px-white-noise-sleep.png',
  'Pixel art white noise machine with moon and stars.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'teething-signs-soothers',
  'Teething signs and soothers',
  'Dribble, gnawing, grumps',
  'Heads Up',
  'Baby / Health',
  'Baby (3-12 months)',
  120, 270, null, null,
  72,
  false,
  'Teething can cause dribble, biting, and disrupted sleep. Chew toys and chilled rings help some babies.',
  'Teething gets blamed for everything. It is real, but it is not always the whole story.',
  'Simple soothing helps. Persistent fever or illness needs a GP, not just teething gel.',
  'Offer safe chew toys and extra cuddles. Check temperature if unwell.',
  'Blaming every bad night on teeth without checking health.',
  '["Safe chew toys ready","Extra bibs for dribble","GP if fever or very unwell"]'::jsonb,
  '["https://raisingchildren.net.au/babies/teething/teething-signs"]'::jsonb,
  'Medical content - review before production use.',
  true,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: teething ring and chilled washcloth with tiny sparkle.',
  '/card-images/pixel/px-teething-signs-soothers.png',
  'Pixel art teething ring and chilled washcloth.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'rolling-and-floor-time',
  'Rolling changes everything',
  'Floor time and safe sleep',
  'Heads Up',
  'Development',
  'Baby (3-12 months)',
  90, 210, null, null,
  80,
  false,
  'Once rolling starts, sleep setup and change-table safety need a refresh.',
  'The day they roll is the day the change table becomes a wrestling mat.',
  'Rolling babies need firm flat sleep surfaces and never unattended on high surfaces.',
  'Stop swaddling when rolling begins and keep one hand on bub at the change table.',
  'Fancy sleep suits that restrict movement.',
  '["Stop swaddle when rolling","One hand on change table always","Clear floor for practice"]'::jsonb,
  '["https://www.rednose.org.au/article/safe-sleep-for-babies"]'::jsonb,
  'Safety content - review Red Nose guidance.',
  false,
  false,
  true,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: play mat with colorful rolling ball and soft block.',
  '/card-images/pixel/px-rolling-and-floor-time.png',
  'Pixel art play mat and ball for rolling practice.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'separation-anxiety-phase',
  'Separation anxiety arrives',
  'Clingy is developmental',
  'Parent Sanity',
  'Development',
  'Baby (3-12 months)',
  210, 450, null, null,
  78,
  false,
  'Many babies cling and cry with leave-taking around eight to ten months. It usually peaks and eases.',
  'They are not manipulating you. Their brain just figured out you can leave.',
  'Predictable goodbyes and calm returns build security.',
  'Use a short goodbye ritual and return when you promised.',
  'Sneaking out to avoid tears (it often makes it worse).',
  '["Short consistent goodbye","Return when promised","Tell carers about the phase"]'::jsonb,
  '["https://raisingchildren.net.au/toddlers/behaviour/separation-anxiety"]'::jsonb,
  'Development content - review before production use.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: small comfort teddy and gentle waving hand with heart.',
  '/card-images/pixel/px-separation-anxiety-phase.png',
  'Pixel art comfort teddy for separation anxiety phase.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'finger-foods-stage-two',
  'Finger foods: the messy stage',
  'Soft, squishy, pea-sized',
  'Feeding',
  'Feeding / Solids',
  'Baby (3-12 months)',
  240, 365, null, null,
  82,
  false,
  'After purees, soft finger foods build chewing skills. Offer variety and expect mess.',
  'The floor gets more food than the mouth for a while. That is learning.',
  'Self-feeding supports motor skills and appetite regulation.',
  'Offer soft strips of avocado, banana, or well-cooked pasta.',
  'Instagram-worthy lunchboxes.',
  '["Soft finger foods ready","Splash mat under high chair","Stay nearby while eating"]'::jsonb,
  '["https://www.pregnancybirthbaby.org.au/finger-foods"]'::jsonb,
  'Feeding content - review before production use.',
  false,
  false,
  false,
  false,
  true,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: high chair tray with soft banana piece, messy bib and tiny cup.',
  '/card-images/pixel/px-finger-foods-stage-two.png',
  'Pixel art high chair tray with finger foods.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'crawling-proofing-refresh',
  'Crawling proofing refresh',
  'Plugs, stairs, pet bowls',
  'Heads Up',
  'Safety',
  'Baby (3-12 months)',
  210, 365, null, null,
  86,
  false,
  'Mobile babies find pet bowls, stairs, and power points fast. Re-crawl your home at their level.',
  'Baby proofing is never done once. Mobility upgrades the hazard list.',
  'Most injuries at this age are falls and household items.',
  'Move cleaners up high and gate stairs if you can.',
  'Designer furniture corner guards in every room.',
  '["Gate or block stairs","Move cleaners and medicines up","Empty pet bowls from floor"]'::jsonb,
  '["https://kidsafe.com.au/"]'::jsonb,
  'Safety content - review Kidsafe guidance.',
  false,
  false,
  true,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: baby safety gate and outlet cover as cute collectible items.',
  '/card-images/pixel/px-crawling-proofing-refresh.png',
  'Pixel art baby gate and outlet cover for crawling proofing.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'babbling-conversations',
  'Babbling deserves replies',
  'Serve and return',
  'Heads Up',
  'Development / Speech',
  'Baby (3-12 months)',
  150, 365, null, null,
  70,
  false,
  'Repeating sounds back to babbling babies builds language pathways. Narrate boring tasks shamelessly.',
  'You will say "good talking" to a person who cannot talk yet. It works.',
  'Early back-and-forth conversation supports later language.',
  'Repeat their sounds and name what you are doing out loud.',
  'Flash cards and reading programs.',
  '["Repeat babbles back","Narrate nappy changes","Read one short book daily"]'::jsonb,
  '["https://raisingchildren.net.au/babies/play-learning/learning-ideas/talking"]'::jsonb,
  'Development content - review before production use.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: picture book with playful speech bubble toys.',
  '/card-images/pixel/px-babbling-conversations.png',
  'Pixel art picture book and speech bubbles for babbling.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'introducing-sippy-cup',
  'Introduce a cup with water',
  'Open or straw, not mandatory',
  'Tiny Gear Shift',
  'Feeding',
  'Baby (3-12 months)',
  180, 300, null, null,
  65,
  false,
  'From around six months, small sips of water with meals in a cup build skills for later weaning off bottles.',
  'Most of the water will be worn, not drunk. That is fine.',
  'Cup practice supports hydration and dental health as solids increase.',
  'Offer a little water at meal times in a small open or straw cup.',
  'Mastering cups before solids are established.',
  '["Small cup at meals","Expect spills","Keep breast or formula as main drink under 12 months"]'::jsonb,
  '["https://www.pregnancybirthbaby.org.au/drinks-and-cups-for-babies"]'::jsonb,
  'Feeding content - review before production use.',
  false,
  false,
  false,
  false,
  true,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: cute sippy cup with small splash drops and sparkle.',
  '/card-images/pixel/px-introducing-sippy-cup.png',
  'Pixel art sippy cup with playful splash.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'mobile-baby-sleep-shift',
  'Mobile baby sleep shift',
  'Standing in the cot happens',
  'Sleep',
  'Sleep',
  'Baby (3-12 months)',
  240, 365, null, null,
  77,
  false,
  'Standing, sitting, and practising new skills in the cot can disrupt sleep. Practice lots in the day.',
  'They are not fighting bedtime. They are thrilled they learned to stand.',
  'Skill practice during the day reduces 3am cot gymnastics.',
  'Give extra floor time to practice the new skill before bed.',
  'Sleep training because they stood up once.',
  '["Extra daytime practice","Lower cot mattress if standing","Patience for a few nights"]'::jsonb,
  '["https://raisingchildren.net.au/babies/sleep/settling-babies"]'::jsonb,
  'Review before production use.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: crib rail with cozy sleep sack and tiny star mobile.',
  '/card-images/pixel/px-mobile-baby-sleep-shift.png',
  'Pixel art crib rail and sleep sack for mobile baby sleep.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'playgroup-for-adults',
  'Playgroup is for you too',
  'Adult company counts',
  'Parent Sanity',
  'Community',
  'Baby (3-12 months)',
  120, 365, null, null,
  62,
  false,
  'Local playgroups, library rhyme time, and parent groups are as much about your sanity as bub''s social life.',
  'Babies mostly parallel play. You go for the coffee and the nod from another tired adult.',
  'Isolation in early parenting is a risk factor for low mood.',
  'Search council library rhyme time or a local playgroup and try one session.',
  'Finding the perfect group on the first visit.',
  '["Find one local session","Go once with low expectations","Swap numbers if you click with someone"]'::jsonb,
  '["https://www.playgroupaustralia.org.au/"]'::jsonb,
  'Review local naming before production use.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: coffee cup beside stacked toy blocks and tiny sun hat.',
  '/card-images/pixel/px-playgroup-for-adults.png',
  'Pixel art coffee cup and toy blocks for playgroup.',
  'cute 8-bit pixel art item',
  'approved',
  'published',
  current_date,
  current_date + interval '12 months',
  now()
),
(
  'gagging-vs-choking',
  'Gagging is different from choking',
  'Stay calm, stay close',
  'Heads Up',
  'Feeding / Safety',
  'Baby (3-12 months)',
  180, 365, null, null,
  90,
  false,
  'Gagging is noisy and common when learning solids. True choking is silent and needs first aid.',
  'A baby gagging looks scary and often resolves if you let them work it out while you stay close.',
  'Knowing the difference prevents panic and harmful finger sweeps.',
  'Consider an infant first aid course and always stay arm''s reach during meals.',
  'Assuming every cough is an emergency.',
  '["Book infant first aid course","Stay within arm''s reach when eating","Cut food to safe sizes"]'::jsonb,
  '["https://www.redcross.org.au/courses/"]'::jsonb,
  'Safety content - review St John or Red Cross guidance.',
  false,
  false,
  true,
  false,
  true,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: infant first aid booklet with soft finger food pieces, calm and safe.',
  '/card-images/pixel/px-gagging-vs-choking.png',
  'Pixel art first aid booklet and soft finger foods.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'drop-the-third-nap',
  'The third nap might drop',
  'Two naps is a new era',
  'Sleep',
  'Sleep',
  'Baby (3-12 months)',
  270, 450, null, null,
  73,
  false,
  'Many babies move to two naps between eight and twelve months. Bedtime may need to shift earlier temporarily.',
  'The transition week feels like everyone is overtired all the time.',
  'Expecting three naps when bub is ready for two fights sleep.',
  'Watch for short third naps or bedtime battles and try an earlier two-nap day.',
  'Rigid schedules from a book written for a different baby.',
  '["Watch nap signals","Try earlier bedtime during transition","Be flexible for two weeks"]'::jsonb,
  '["https://raisingchildren.net.au/babies/sleep/sleep-routines"]'::jsonb,
  'Review before production use.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: sleepy sun icon with clock and three gentle zzz symbols, no numbers.',
  '/card-images/pixel/px-drop-the-third-nap.png',
  'Pixel art sleepy sun and clock for dropping the third nap.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'childcare-drop-off-tips',
  'Childcare drop-off gets easier',
  'Short goodbyes help',
  'Heads Up',
  'Childcare',
  'Baby (3-12 months)',
  150, 365, null, null,
  79,
  false,
  'First weeks of childcare often involve tears at drop-off. Consistent short goodbyes and trust in educators help.',
  'They often calm down minutes after you leave. That is not dismissal of their feelings.',
  'Predictable routines support attachment with carers.',
  'Use the same goodbye every time and ask educators how long settling takes.',
  'Quitting because day three was hard.',
  '["Same goodbye ritual","Comfort item if centre allows","Check in with educators after an hour"]'::jsonb,
  '["https://raisingchildren.net.au/preschoolers/child-care/child-care-starting"]'::jsonb,
  'Review before production use.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true,"childcare_yes_or_unsure":true}'::jsonb,
  'Cute pixel art collectible: tiny backpack with comfort teddy at a friendly door.',
  '/card-images/pixel/px-childcare-drop-off-tips.png',
  'Pixel art childcare backpack and comfort teddy at door.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'shoes-wait-for-walking',
  'Wait on shoes until walking',
  'Bare feet or socks indoors',
  'Tiny Gear Shift',
  'Gear',
  'Baby (3-12 months)',
  300, 450, null, null,
  58,
  false,
  'Cruising and early walking do not need stiff shoes indoors. Bare feet build grip and balance.',
  'Tiny shoes are adorable and mostly unnecessary for months.',
  'Flexible feet and toes help balance. Shoes outside protect when walking confidently.',
  'Let them cruise barefoot at home. Choose flexible shoes for rough outdoor surfaces later.',
  'Matching shoe collection.',
  '["Bare feet or socks indoors","Flexible shoes only when walking outside","Check fit often"]'::jsonb,
  '["https://raisingchildren.net.au/toddlers/play-learning/play-ideas/walking"]'::jsonb,
  'Review before production use.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: baby socks with tiny shoes waiting patiently beside them.',
  '/card-images/pixel/px-shoes-wait-for-walking.png',
  'Pixel art baby socks and waiting shoes.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'potty-curiosity-ok',
  'Potty curiosity is fine',
  'No rush to train',
  'Heads Up',
  'Toddler / Development',
  'Toddler (12-24 months)',
  365, 545, null, null,
  68,
  false,
  'Letting a toddler sit on a potty clothed builds familiarity. Formal training can wait until readiness signs.',
  'Potty training pressure comes from relatives, not from your two-year-old''s biology.',
  'Rushing training creates battles. Readiness signs matter more than age.',
  'If curious, let them sit on a potty while you talk about wee and poo plainly.',
  'Three-day bootcamp before they show interest.',
  '["Potty in bathroom if curious","Plain language for body functions","Wait for readiness signs"]'::jsonb,
  '["https://raisingchildren.net.au/toddlers/toilet-training/toilet-training-basics"]'::jsonb,
  'Review before production use.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: cute potty chair with gold star sticker.',
  '/card-images/pixel/px-potty-curiosity-ok.png',
  'Pixel art potty chair with star sticker.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'toddler-bed-can-wait',
  'The toddler bed can wait',
  'Cot until climbing',
  'Heads Up',
  'Sleep / Safety',
  'Toddler (12-24 months)',
  545, 730, null, null,
  71,
  false,
  'Many families keep a cot until climbing out is consistent. A sleeping bag can delay early escapes.',
  'A toddler bed is freedom. Freedom at 2am is overrated.',
  'Premature bed transitions often disrupt sleep and safety.',
  'If not climbing, cot plus sleeping bag is fine. Lower mattress if climbing starts.',
  'Moving to a bed because the cot looks babyish.',
  '["Delay bed until climbing","Use sleeping bag if helpful","Childproof room if bed transition happens"]'::jsonb,
  '["https://www.rednose.org.au/article/safe-sleep-for-babies"]'::jsonb,
  'Safety content - review before production use.',
  false,
  false,
  true,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: cot with cozy sleeping bag as a level-up item.',
  '/card-images/pixel/px-toddler-bed-can-wait.png',
  'Pixel art cot and sleeping bag, toddler bed can wait.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'parallel-play-normal',
  'Parallel play is normal',
  'Friends look different at two',
  'Heads Up',
  'Toddler / Social',
  'Toddler (12-24 months)',
  365, 545, null, null,
  64,
  false,
  'Toddlers often play beside, not with, other kids. Sharing develops slowly.',
  'Two toddlers in a room is not a playdate. It is two monologues with toys.',
  'Expecting sharing too early creates shame and fights.',
  'Keep playdates short and have duplicate toys if possible.',
  'Forced sharing lessons.',
  '["Short playdates","Duplicate popular toys","Stay close to coach gently"]'::jsonb,
  '["https://raisingchildren.net.au/toddlers/play-learning/play-ideas/playgroups"]'::jsonb,
  'Review before production use.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: two toy cars side by side with small sparkle between them.',
  '/card-images/pixel/px-parallel-play-normal.png',
  'Pixel art two toy cars for parallel play.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'bedtime-routine-toddler',
  'Bedtime routine still matters',
  'Same order, every night',
  'Sleep',
  'Sleep',
  'Toddler (12-24 months)',
  365, 730, null, null,
  75,
  false,
  'Predictable bath-book-bed sequences help toddlers wind down even when they stall creatively.',
  'They will ask for one more everything. The routine is the point.',
  'Consistency reduces bedtime battles.',
  'Pick three steps and repeat in the same order nightly.',
  'New surprises every bedtime.',
  '["Three-step routine","Same order nightly","Dim lights before bed"]'::jsonb,
  '["https://raisingchildren.net.au/toddlers/sleep/settling-toddlers"]'::jsonb,
  'Review before production use.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: bath duck, tiny storybook and small bed icons in a row.',
  '/card-images/pixel/px-bedtime-routine-toddler.png',
  'Pixel art bath duck, book and bed for bedtime routine.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'toddler-helping-kitchen',
  'Let them help in the kitchen',
  'Messy but worth it',
  'Fun First',
  'Toddler / Play',
  'Toddler (12-24 months)',
  365, 545, null, null,
  60,
  false,
  'Stirring, washing veg, and tearing lettuce builds skills and sometimes interest in food.',
  'It takes five times longer and that is still a win.',
  'Involvement can reduce mealtime battles and builds motor skills.',
  'Give one safe job at each meal prep.',
  'Perfect helper outcomes.',
  '["One safe kitchen job","Expect mess","Praise effort not results"]'::jsonb,
  '["https://raisingchildren.net.au/toddlers/play-learning/play-ideas/cooking"]'::jsonb,
  'Review before production use.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: toddler step stool and wooden spoon with mixing bowl.',
  '/card-images/pixel/px-toddler-helping-kitchen.png',
  'Pixel art step stool and wooden spoon for kitchen helping.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'saying-no-without-shame',
  'Saying no without shame',
  'Boundaries are kindness',
  'Parent Sanity',
  'Toddler / Behaviour',
  'Toddler (12-24 months)',
  450, 730, null, null,
  74,
  false,
  'Clear, calm limits with a short reason beat endless negotiations with a pre-verbal toddler.',
  'You are not mean. You are the adult with the prefrontal cortex.',
  'Consistent limits reduce anxiety and unsafe behaviour.',
  'Pick one non-negotiable and use the same phrase each time.',
  'Long lectures they cannot follow.',
  '["One consistent limit phrase","Stay calm","Redirect to a yes option"]'::jsonb,
  '["https://raisingchildren.net.au/toddlers/behaviour/behaviour-management-tips"]'::jsonb,
  'Review before production use.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: gentle boundary fence with heart and soft redirect arrow.',
  '/card-images/pixel/px-saying-no-without-shame.png',
  'Pixel art gentle boundary fence with heart.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'first-dentist-toddler',
  'First dentist visit around one',
  'Lift-the-lip check counts',
  'Big Milestone',
  'Health / Dental',
  'Toddler (12-24 months)',
  365, 545, null, null,
  77,
  false,
  'Australian guidance suggests a dental check by age one or within six months of first tooth.',
  'The first visit is mostly riding in the chair and counting teeth.',
  'Early checks prevent painful problems and normalise dental care.',
  'Book a family-friendly dentist and bring a comfort toy.',
  'Waiting for a toothache.',
  '["Book first dental check","Brush twice daily with low-fluoride paste if advised","Avoid bedtime bottles of milk"]'::jsonb,
  '["https://www.pregnancybirthbaby.org.au/dental-care-for-children"]'::jsonb,
  'Medical content - review before production use.',
  true,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: tiny toothbrush and friendly smiling tooth character, no fear.',
  '/card-images/pixel/px-first-dentist-toddler.png',
  'Pixel art toothbrush and friendly tooth for first dentist visit.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'library-rhyme-time',
  'Library rhyme time is free',
  'Aircon and songs',
  'Fun First',
  'Community',
  'Toddler (12-24 months)',
  300, 545, null, null,
  58,
  false,
  'Council libraries run free rhyme time and story sessions for babies and toddlers.',
  'It is the best air-conditioned activity in summer and it costs nothing.',
  'Rhythm, language, and leaving the house all happen at once.',
  'Search your council library events and pick one morning to try.',
  'Buying more toys for stimulation.',
  '["Find local rhyme time","Pack snacks","Go once this month"]'::jsonb,
  '["https://www.sl.nsw.gov.au/"]'::jsonb,
  'Update with national library locator before production use.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: stack of picture books with small maracas and sparkle.',
  '/card-images/pixel/px-library-rhyme-time.png',
  'Pixel art picture books and maracas for library rhyme time.',
  'cute 8-bit pixel art item',
  'approved',
  'published',
  current_date,
  current_date + interval '12 months',
  now()
),
(
  'return-of-period-breastfeeding',
  'Periods can return while breastfeeding',
  'Fertility may return too',
  'Heads Up',
  'Postpartum / Health',
  'Baby (3-12 months)',
  120, 365, null, null,
  66,
  false,
  'Ovulation can return before your first period while breastfeeding. Contraception conversations matter if another pregnancy is not planned.',
  'Breastfeeding is not a reliable contraceptive for everyone.',
  'Unexpected fertility affects planning and supply for some feeders.',
  'Talk contraception with your GP if relevant to you.',
  'Assuming breastfeeding blocks fertility indefinitely.',
  '["GP chat if contraception needed","Track cycles if they return","Know supply may dip briefly for some"]'::jsonb,
  '["https://www.pregnancybirthbaby.org.au/contraception-after-birth"]'::jsonb,
  'Medical content - review before production use.',
  true,
  false,
  false,
  false,
  true,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: gentle calendar with nursing bra icon and soft leaf accent.',
  '/card-images/pixel/px-return-of-period-breastfeeding.png',
  'Pixel art calendar and nursing icon for return of period.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'private-health-pregnancy-check',
  'Check private health cover',
  'Waiting periods matter',
  'Admin Trap',
  'Admin / Insurance',
  'Pregnancy',
  null, null, 8, 20,
  83,
  false,
  'Obstetrics cover needs the right policy and waiting periods. Check before you assume you are covered.',
  'Insurance fine print is less fun than nursery Pinterest boards but more expensive if ignored.',
  'Out-of-pocket obstetric costs without cover can be substantial.',
  'Call your fund and ask about obstetrics cover, waiting periods, and hospital lists.',
  'Assuming your old singles policy still works.',
  '["Call health fund","Confirm obstetrics waiting period","Check hospital agreement list"]'::jsonb,
  '["https://www.privatehealth.gov.au/"]'::jsonb,
  'Government and insurance wording - review before production use.',
  false,
  true,
  false,
  false,
  false,
  '{"unborn_only":true}'::jsonb,
  'Cute pixel art collectible: generic health insurance card shape with stethoscope, not copying real brands.',
  '/card-images/pixel/px-private-health-pregnancy-check.png',
  'Pixel art health insurance card and stethoscope.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'update-will-insurance',
  'Update will and insurance',
  'Unsexy but kind',
  'Admin Trap',
  'Admin / Planning',
  'Pregnancy or early baby',
  null, null, 20, 40,
  67,
  false,
  'A new dependant is a good prompt to check life insurance beneficiaries and guardianship wishes.',
  'Future you will be grateful for one boring afternoon of paperwork.',
  'Clear wishes reduce family stress in worst-case scenarios.',
  'Check super beneficiaries and consider a basic will update appointment.',
  'Perfect estate planning essays.',
  '["Check super beneficiaries","Book will review","Check life insurance cover"]'::jsonb,
  '["https://www.moneysmart.gov.au/"]'::jsonb,
  'Financial content - review before production use.',
  false,
  true,
  false,
  false,
  false,
  '{"unborn_only":true}'::jsonb,
  'Cute pixel art collectible: folder with tiny heart, pen and soft shield icon.',
  '/card-images/pixel/px-update-will-insurance.png',
  'Pixel art folder and pen for will and insurance update.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'baby-name-registration-timing',
  'Baby name registration timing',
  'State registry rules vary',
  'Admin Trap',
  'Admin / Government',
  'Newborn (0-3 months)',
  0, 60, null, null,
  81,
  false,
  'Birth registration deadlines and name rules vary by state. The hospital usually starts the process.',
  'You can change your mind on spelling once, but not forever.',
  'Medicare and Centrelink need registered details.',
  'Check your state registry deadline and start the online form.',
  'Announcing the name to relatives before you agree with each other.',
  '["Check state registry deadline","Complete hospital paperwork","Align name with Medicare enrolment"]'::jsonb,
  '["https://www.pregnancybirthbaby.org.au/registering-the-birth-of-your-baby"]'::jsonb,
  'Government process wording - review before production use.',
  false,
  true,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: birth registration folder with tiny baby socks and pen.',
  '/card-images/pixel/px-baby-name-registration-timing.png',
  'Pixel art birth registration folder and baby socks.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'blackout-blinds-sleep',
  'Blackout blinds help some sleep',
  'Not magic, but useful',
  'Tiny Gear Shift',
  'Sleep / Gear',
  'Baby (3-12 months)',
  90, 545, null, null,
  52,
  false,
  'Darkening the room can extend early-morning naps in sunny Australian bedrooms.',
  'Towels over windows at 5am are a valid interim strategy.',
  'Light is a strong wake cue. Darkness can help short naps.',
  'Try temporary darkening and see if the first nap lengthens.',
  'Custom blinds for every room.',
  '["Try temporary blackout","Watch nap length","Keep room ventilated"]'::jsonb,
  '["https://raisingchildren.net.au/babies/sleep/sleep-routines"]'::jsonb,
  'Review before production use.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: window with soft blackout blinds, moon and stars outside.',
  '/card-images/pixel/px-blackout-blinds-sleep.png',
  'Pixel art window with blackout blinds and moon.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'quiet-week-rest-counts',
  'Rest is productive this week',
  'Doing less is the plan',
  'quiet_week',
  'Reassurance',
  'Any',
  null, null, null, null,
  48,
  false,
  'A week with nothing due is a chance to bank sleep and sanity, not catch up on life admin.',
  'Rest is not laziness when you are growing or raising a human.',
  'Recovery and connection matter as much as milestones.',
  'Cancel one optional thing guilt-free.',
  'Everything non-essential.',
  '["Cancel one optional commitment","Take one nap without apologising"]'::jsonb,
  '[]'::jsonb,
  null,
  false,
  false,
  false,
  false,
  false,
  '{}'::jsonb,
  'Cute pixel art collectible: cozy blanket and pillow with gentle sparkles, calm rest mood.',
  '/card-images/pixel/px-quiet-week-rest-counts.png',
  'Pixel art cozy blanket and pillow for quiet week rest.',
  'cute 8-bit pixel art item',
  'approved',
  'published',
  current_date,
  current_date + interval '12 months',
  now()
),
(
  'quiet-week-partner-check-in',
  'Check in with your partner',
  'Two minutes counts',
  'quiet_week',
  'Reassurance',
  'Any',
  null, null, null, null,
  48,
  false,
  'A quiet week is a good week for a honest two-minute check-in: how are we actually doing?',
  'Small conversations prevent big blow-ups later.',
  'Teams that talk adjust before resentment builds.',
  'Ask one real question and listen without fixing.',
  'Grand relationship gestures.',
  '["Two-minute check-in","Name one thing you appreciate"]'::jsonb,
  '[]'::jsonb,
  null,
  false,
  false,
  false,
  false,
  false,
  '{}'::jsonb,
  'Cute pixel art collectible: two coffee cups with small heart between them.',
  '/card-images/pixel/px-quiet-week-partner-check-in.png',
  'Pixel art two coffee cups for partner check-in.',
  'cute 8-bit pixel art item',
  'approved',
  'published',
  current_date,
  current_date + interval '12 months',
  now()
),
(
  'quiet-week-this-phase-passes',
  'This phase is short',
  'Even when it feels endless',
  'quiet_week',
  'Reassurance',
  'Any',
  null, null, null, null,
  48,
  false,
  'The season you are in right now will change. That is not dismissive. It is true.',
  'The hard phases and the tiny-sock phases both pass.',
  'Perspective helps on flat days.',
  'Notice one small thing you might miss later.',
  'Worrying about the next decade today.',
  '["Name one thing to remember from this week"]'::jsonb,
  '[]'::jsonb,
  null,
  false,
  false,
  false,
  false,
  false,
  '{}'::jsonb,
  'Cute pixel art collectible: gentle hourglass with flowers and soft sunrise, hopeful mood.',
  '/card-images/pixel/px-quiet-week-this-phase-passes.png',
  'Pixel art hourglass with flowers, this phase passes.',
  'cute 8-bit pixel art item',
  'approved',
  'published',
  current_date,
  current_date + interval '12 months',
  now()
)
on conflict (slug) do update set
  title = excluded.title,
  subtitle = excluded.subtitle,
  card_type = excluded.card_type,
  category = excluded.category,
  life_stage = excluded.life_stage,
  start_age_days = excluded.start_age_days,
  end_age_days = excluded.end_age_days,
  pregnancy_week_start = excluded.pregnancy_week_start,
  pregnancy_week_end = excluded.pregnancy_week_end,
  priority = excluded.priority,
  time_critical = excluded.time_critical,
  short_summary = excluded.short_summary,
  wish_i_knew = excluded.wish_i_knew,
  why_it_matters = excluded.why_it_matters,
  what_to_do_now = excluded.what_to_do_now,
  what_can_wait = excluded.what_can_wait,
  checklist_items = excluded.checklist_items,
  source_urls = excluded.source_urls,
  source_notes = excluded.source_notes,
  medical_sensitivity = excluded.medical_sensitivity,
  government_sensitivity = excluded.government_sensitivity,
  safety_sensitivity = excluded.safety_sensitivity,
  allergy_sensitivity = excluded.allergy_sensitivity,
  feeding_sensitivity = excluded.feeding_sensitivity,
  conditions = excluded.conditions,
  illustration_prompt = excluded.illustration_prompt,
  image_url = excluded.image_url,
  image_alt = excluded.image_alt,
  image_style = excluded.image_style,
  image_status = excluded.image_status,
  status = excluded.status,
  last_reviewed_at = excluded.last_reviewed_at,
  review_due_date = excluded.review_due_date,
  updated_at = now();

