-- Wish I Knew content library batch 4 (25 cards).
-- Run after seed_content_library_batch3.sql. Safe to re-run (upserts by slug).
-- Sensitive cards remain in_review with null review dates until editorial review.

insert into public.timeline_cards (
  slug,
  title,
  subtitle,
  card_type,
  category,
  life_stage,
  start_age_days,
  end_age_days,
  pregnancy_week_start,
  pregnancy_week_end,
  priority,
  time_critical,
  short_summary,
  wish_i_knew,
  why_it_matters,
  what_to_do_now,
  what_can_wait,
  checklist_items,
  source_urls,
  source_notes,
  medical_sensitivity,
  government_sensitivity,
  safety_sensitivity,
  allergy_sensitivity,
  feeding_sensitivity,
  conditions,
  illustration_prompt,
  image_url,
  image_alt,
  image_style,
  image_status,
  status,
  last_reviewed_at,
  review_due_date,
  published_at
) values
(
  'freezer-breakfasts-before-baby',
  'Freeze breakfasts, not just dinners',
  'Morning you will be grateful',
  'Tiny Gear Shift',
  'Pregnancy / Preparation',
  'Pregnancy',
  null, null, 30, 40,
  58,
  false,
  'A few one-handed breakfasts in the freezer can be more useful than another perfectly folded drawer.',
  'Everyone brings lasagne. Nobody remembers you will also be hungry at 6am.',
  'Early newborn mornings are easier when food needs one hand and almost no decisions.',
  'Freeze a small batch of muffins, breakfast wraps or whatever you already like eating.',
  'A freezer packed for an imaginary six-month siege.',
  '["Choose one familiar breakfast","Freeze a small batch","Add easy snacks to the next shop"]'::jsonb,
  '[]'::jsonb,
  null,
  false,
  false,
  false,
  false,
  false,
  '{"unborn_only":true}'::jsonb,
  'Cute pixel art collectible: a neat stack of labelled freezer breakfast containers beside a small sunrise and coffee cup.',
  '/card-images/pixel/px-freezer-breakfasts-before-baby.png',
  'Pixel art freezer breakfast containers with a sunrise and coffee cup on a warm cream background.',
  'cute 8-bit pixel art item',
  'approved',
  'published',
  current_date,
  current_date + interval '12 months',
  now()
),
(
  'pregnancy-support-roster',
  'Make the help specific',
  'A roster beats vague offers',
  'Parent Sanity',
  'Pregnancy / Support',
  'Pregnancy',
  null, null, 28, 40,
  68,
  false,
  'Turn offers of help into a short list of useful jobs: meals, washing, dog walks, school runs or pharmacy trips.',
  'People mean it when they say call if you need anything. They just need a job title.',
  'Specific requests are easier to accept and easier for your support crew to actually do.',
  'Write five jobs and match each one to someone who has already offered help.',
  'Hosting visitors or repaying every favour immediately.',
  '["List five useful jobs","Name a backup contact","Share the list with your support crew"]'::jsonb,
  '[]'::jsonb,
  null,
  false,
  false,
  false,
  false,
  false,
  '{"unborn_only":true}'::jsonb,
  'Cute pixel art collectible: a friendly weekly calendar surrounded by a meal bowl, laundry basket and tiny helping hands.',
  '/card-images/pixel/px-pregnancy-support-roster.png',
  'Pixel art calendar with meal, laundry and helping-hand symbols for a newborn support roster.',
  'cute 8-bit pixel art item',
  'approved',
  'published',
  current_date,
  current_date + interval '12 months',
  now()
),
(
  'newborn-feeding-support-plan',
  'Know your feeding support options',
  'A plan, plus room to change it',
  'Heads Up',
  'Pregnancy / Feeding',
  'Pregnancy',
  null, null, 30, 40,
  82,
  false,
  'Before birth, save a few trusted feeding contacts and talk through your preferences without treating them as a pass-or-fail test.',
  'Feeding is a learned skill and a family decision, not a character assessment.',
  'Early access to calm, qualified support can make feeding problems feel solvable, whichever feeding path you use.',
  'Save your maternity ward, child health nurse and chosen feeding support contacts, then tell your support person what matters to you.',
  'Buying every feeding product before you know what you and bub need.',
  '["Save local feeding support contacts","Talk through preferences with your support person","Keep room for the plan to change"]'::jsonb,
  '["https://www.pregnancybirthbaby.org.au/babies/feeding-and-nutrition/breastfeeding-your-baby","https://www.pregnancybirthbaby.org.au/babies/feeding-and-nutrition/feeding-your-baby-with-formula"]'::jsonb,
  'Feeding content. Review inclusive wording and current Australian guidance before production use.',
  false,
  false,
  false,
  false,
  true,
  '{"unborn_only":true}'::jsonb,
  'Cute pixel art collectible: a calm feeding chair with a water bottle, burp cloth and phone showing a simple heart icon.',
  '/card-images/pixel/px-newborn-feeding-support-plan.png',
  'Pixel art feeding chair, water bottle, burp cloth and support phone on a warm cream background.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'newborn-hearing-screen',
  'The newborn hearing screen',
  'Quick, gentle, easy to miss in the fog',
  'Big Milestone',
  'Newborn / Health',
  'Newborn (0-3 months)',
  0, 30, null, null,
  86,
  false,
  'Australian newborns are offered a quick hearing screen, usually before leaving hospital or soon after discharge.',
  'Bub can sleep through the whole thing. It is often the calmest appointment of week one.',
  'The screen can flag hearing differences early, when follow-up support can help language and communication development.',
  'Check that the result is recorded before discharge, or ask how the outpatient screen will be arranged.',
  'Reading meaning into a repeat screen. Sometimes a second check is simply needed.',
  '["Confirm the screen was offered","Keep the result with the baby health record","Follow up if a repeat was recommended"]'::jsonb,
  '["https://www.pregnancybirthbaby.org.au/babies/health-and-wellbeing/newborn-hearing-screening-test"]'::jsonb,
  'Medical screening content. Review against current Australian and state guidance before production use.',
  true,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: two soft newborn hearing ear cups with a tiny sleeping moon and gentle sound sparkles.',
  '/card-images/pixel/px-newborn-hearing-screen.png',
  'Pixel art newborn hearing screening ear cups with a moon and soft sound sparkles.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'newborn-jaundice-check',
  'Yellow skin deserves a check',
  'Jaundice is common, still mention it',
  'Heads Up',
  'Newborn / Health',
  'Newborn (0-3 months)',
  0, 21, null, null,
  90,
  true,
  'Jaundice is common in newborns, but yellow skin or eyes should be checked and monitored by a nurse or doctor.',
  'The right move is not diagnosing the shade under different lamps. It is asking someone to look.',
  'Most jaundice settles, but some babies need feeding support, monitoring or treatment.',
  'Contact your midwife, child health nurse or GP if you notice yellowing, poor feeding, unusual sleepiness, pale poo or dark wee.',
  'Trying home fixes before a health professional has checked bub.',
  '["Look in natural light if concerned","Ask a nurse or doctor to check","Seek prompt advice if feeding or alertness changes"]'::jsonb,
  '["https://www.pregnancybirthbaby.org.au/jaundice-in-babies"]'::jsonb,
  'Medical and time-sensitive content. Review red flags against current Australian guidance before production use.',
  true,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: a warm bedside lamp, a tiny sun card and a friendly child health notebook, calm not clinical.',
  '/card-images/pixel/px-newborn-jaundice-check.png',
  'Pixel art bedside lamp, sun card and child health notebook for a newborn jaundice check.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'two-nappy-stations',
  'Make two tiny nappy stations',
  'Save the midnight hallway hike',
  'Tiny Gear Shift',
  'Newborn / Gear',
  'Newborn (0-3 months)',
  0, 60, null, null,
  56,
  false,
  'A small basket of nappies, wipes and spare clothes where you spend time saves surprising amounts of effort.',
  'The best changing station is the one within reach when the outfit has failed spectacularly.',
  'Duplicating a few basics reduces stairs, searching and fully waking everyone overnight.',
  'Put one small refillable basket near the main living area and one near the night setup.',
  'Matching furniture or a perfectly styled change table.',
  '["Add nappies and wipes","Include one spare outfit","Refill both baskets together"]'::jsonb,
  '[]'::jsonb,
  null,
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: two small matching baskets filled with nappies, wipes and folded cloths with level-up sparkles.',
  '/card-images/pixel/px-two-nappy-stations.png',
  'Pixel art matching nappy baskets with wipes and folded cloths on a warm cream background.',
  'cute 8-bit pixel art item',
  'approved',
  'published',
  current_date,
  current_date + interval '12 months',
  now()
),
(
  'one-handed-food-stash',
  'Build a one-handed food stash',
  'Feeding yourself counts too',
  'Parent Sanity',
  'Postpartum / Practical',
  'Newborn (0-3 months)',
  0, 90, null, null,
  65,
  false,
  'Keep easy food and a filled water bottle beside the place where you most often feed or settle bub.',
  'A snack you can reach beats a balanced lunch you cannot make.',
  'Newborn care creates long stretches where standing up feels impossible. Removing one small barrier helps you eat and drink.',
  'Set up a basket with shelf-stable favourites and refill your water bottle whenever bub feeds.',
  'Turning every snack into an optimised nutrition project.',
  '["Choose three easy snacks","Park a water bottle nearby","Ask visitors to refill the basket"]'::jsonb,
  '[]'::jsonb,
  null,
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: a snack basket with banana, muesli bar and water bottle beside a cosy armchair.',
  '/card-images/pixel/px-one-handed-food-stash.png',
  'Pixel art snack basket and water bottle beside a cosy feeding chair.',
  'cute 8-bit pixel art item',
  'approved',
  'published',
  current_date,
  current_date + interval '12 months',
  now()
),
(
  'first-outing-small-loop',
  'Make the first outing tiny',
  'One loop, one coffee, home',
  'Fun First',
  'Newborn / Outings',
  'Newborn (0-3 months)',
  7, 90, null, null,
  54,
  false,
  'The first outing does not need to be an event. A short pram loop or nearby takeaway coffee is enough.',
  'Leaving the house once makes leaving the house feel possible again.',
  'A deliberately small trip builds confidence without turning feeds, nappies and timing into a military exercise.',
  'Pick somewhere close, pack one change, and give yourself permission to turn around early.',
  'A full day out or proving you can run life exactly as before.',
  '["Choose a short familiar route","Pack one nappy change","Leave with no success criteria"]'::jsonb,
  '[]'::jsonb,
  null,
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: a compact pram on a short curved coastal path with a coffee cup and one gum leaf.',
  '/card-images/pixel/px-first-outing-small-loop.png',
  'Pixel art pram on a short coastal path with a coffee cup and gum leaf.',
  'cute 8-bit pixel art item',
  'approved',
  'published',
  current_date,
  current_date + interval '12 months',
  now()
),
(
  'carrier-fit-check',
  'Do the carrier fit check',
  'Close enough to kiss',
  'Heads Up',
  'Safety / Gear',
  'Baby (3-12 months)',
  90, 365, null, null,
  78,
  false,
  'As bub grows, recheck that the carrier suits their size and keeps their face visible, airway clear and back supported.',
  'The carrier settings that worked last month may already belong to a smaller baby.',
  'A snug, correctly positioned carrier supports safe breathing and makes carrying more comfortable for both of you.',
  'Use the TICKS check and the manufacturer''s fit guide before your next long walk.',
  'A complicated new carrier if the current one still fits its stated size range.',
  '["Tight and upright","Face visible and close enough to kiss","Chin clear of chest","Back supported"]'::jsonb,
  '["https://www.pregnancybirthbaby.org.au/babies/daily-care/baby-carriers-slings-and-backpacks"]'::jsonb,
  'Safety content. Review against current Australian carrier guidance before production use.',
  false,
  false,
  true,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: a soft structured baby carrier displayed upright with five gentle safety sparkles, no baby face.',
  '/card-images/pixel/px-carrier-fit-check.png',
  'Pixel art baby carrier with gentle safety sparkles on a warm cream background.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'high-chair-harness-habit',
  'Buckle the high-chair harness',
  'Every meal, before the food',
  'Heads Up',
  'Safety / Gear',
  'Baby (3-12 months)',
  150, 730, null, null,
  84,
  false,
  'A sturdy high chair and firmly fitted harness matter once bub starts twisting, reaching and trying to stand.',
  'The tray is for food. It is not a seatbelt, however confidently they lean on it.',
  'Falls are the most common high-chair injury, and they can happen faster than a parent can reach across the table.',
  'Make buckling the harness the first step of every meal and check for loose or broken parts.',
  'A high chair that matches the dining table better.',
  '["Use the harness every time","Check the chair is stable","Keep it away from benches and cords","Stay nearby"]'::jsonb,
  '["https://www.productsafety.gov.au/consumers/keep-baby-safe/feed-and-soothe-baby-safely/high-chairs-guide"]'::jsonb,
  'Safety content. Review against current ACCC Product Safety guidance before production use.',
  false,
  false,
  true,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: a sturdy high chair with a clearly buckled five-point harness and a small shield sparkle.',
  '/card-images/pixel/px-high-chair-harness-habit.png',
  'Pixel art sturdy high chair with a buckled safety harness and shield sparkle.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'food-mess-is-practice',
  'Food mess is part of the lesson',
  'The floor is also learning',
  'Parent Sanity',
  'Feeding / Solids',
  'Baby (3-12 months)',
  180, 450, null, null,
  62,
  false,
  'Touching, squashing and dropping food are normal parts of learning to self-feed. A simple cleanup setup protects your patience.',
  'The mess is not evidence that lunch failed. It is evidence that lunch happened.',
  'Exploring textures and practising cups and cutlery take repetition. Pressure and constant wiping can make meals harder for everyone.',
  'Use an easy-clean mat, offer small portions, and do one calm cleanup when the meal ends.',
  'A clean face and tray after every bite.',
  '["Easy-clean mat under the chair","Small portions with easy refills","One cleanup at the end"]'::jsonb,
  '["https://www.pregnancybirthbaby.org.au/children/growth-and-development/toddler-development-learning-to-feed-themselves"]'::jsonb,
  'Feeding content. Review against current Australian responsive-feeding guidance before production use.',
  false,
  false,
  false,
  false,
  true,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: a cheerful suction bowl, soft spoon and a few colourful food splats on an easy-clean mat.',
  '/card-images/pixel/px-food-mess-is-practice.png',
  'Pixel art bowl, spoon and colourful food splats on an easy-clean mat.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'nappy-bag-reset',
  'Reset the nappy bag on arrival',
  'Future-you loves a full spare outfit',
  'Tiny Gear Shift',
  'Gear / Outings',
  'Baby (3-12 months)',
  90, 545, null, null,
  52,
  false,
  'Restock the nappy bag when you get home, not while everyone is waiting at the front door next time.',
  'The spare outfit only exists if it made it back into the bag after the last explosion.',
  'A two-minute reset removes one more departure-time decision from an already busy brain.',
  'Give the bag a permanent home beside a small refill box of nappies, wipes and spare clothes.',
  'Packing for every possible weather event and bodily fluid.',
  '["Refill nappies and wipes","Replace the spare outfit","Return the bag to its launch spot"]'::jsonb,
  '[]'::jsonb,
  null,
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: an open nappy bag with three tidy refill pouches, a spare onesie and a gum leaf key charm.',
  '/card-images/pixel/px-nappy-bag-reset.png',
  'Pixel art nappy bag with tidy refill pouches and a spare onesie.',
  'cute 8-bit pixel art item',
  'approved',
  'published',
  current_date,
  current_date + interval '12 months',
  now()
),
(
  'clothes-next-size-box',
  'Keep the next size in one box',
  'Growth spurts do not send invites',
  'Tiny Gear Shift',
  'Gear / Clothing',
  'Baby (3-12 months)',
  90, 545, null, null,
  48,
  false,
  'Put hand-me-downs and bought-ahead clothes for the next size in one obvious box instead of five mystery cupboards.',
  'Half the next-size clothes get discovered the week after they stop fitting.',
  'One visible system makes sudden growth spurts cheaper and less annoying.',
  'Gather the next size, keep only the useful season, and place the box where you dress bub.',
  'Sorting every future size or keeping clothes you do not actually like.',
  '["Make one next-size box","Check the coming season","Pass on the current size when it is done"]'::jsonb,
  '[]'::jsonb,
  null,
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: a storage box with a larger striped onesie, tiny sun hat and size-up sparkle, no labels or text.',
  '/card-images/pixel/px-clothes-next-size-box.png',
  'Pixel art storage box with a larger onesie and sun hat ready for the next size.',
  'cute 8-bit pixel art item',
  'approved',
  'published',
  current_date,
  current_date + interval '12 months',
  now()
),
(
  'toy-rotation-one-basket',
  'One toy basket is plenty',
  'Rotate, do not renovate',
  'Tiny Gear Shift',
  'Play / Gear',
  'Baby (3-12 months)',
  120, 730, null, null,
  46,
  false,
  'Keep a small set of toys out and swap a few every week or two. Familiar things feel new again after a short holiday.',
  'The toy rotation system can be one basket and one cupboard. It does not need a spreadsheet.',
  'Less clutter makes choices easier for bub and cleanup easier for tired adults.',
  'Leave out a book, something to stack, something to shake and one favourite. Put the rest away.',
  'Buying new toys because this week''s pile looks boring to you.',
  '["Choose a small active set","Store the rest out of sight","Swap only when it helps"]'::jsonb,
  '[]'::jsonb,
  null,
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: one woven toy basket holding three simple toys while another closed box rests behind it.',
  '/card-images/pixel/px-toy-rotation-one-basket.png',
  'Pixel art toy basket with three toys and a closed storage box behind it.',
  'cute 8-bit pixel art item',
  'approved',
  'published',
  current_date,
  current_date + interval '12 months',
  now()
),
(
  'first-cafe-kit',
  'Make a tiny cafe kit',
  'Ten calmer minutes counts',
  'Fun First',
  'Outings / Family',
  'Baby (3-12 months)',
  180, 545, null, null,
  45,
  false,
  'A wipe-clean mat, bib and one quiet toy can turn a quick cafe stop into a manageable little family outing.',
  'You are not chasing a long lunch. You are unlocking a flat white with company.',
  'Small enjoyable outings help family life expand again without demanding perfect behaviour.',
  'Pack one quiet toy and choose a roomy, casual local cafe for a short visit.',
  'Finishing the coffee hot or staying after the mood changes.',
  '["Pack one quiet toy","Add bib and wipes","Choose an easy exit","Celebrate ten good minutes"]'::jsonb,
  '[]'::jsonb,
  null,
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: a small cafe kit with silicone placemat, quiet toy, bib and takeaway coffee cup.',
  '/card-images/pixel/px-first-cafe-kit.png',
  'Pixel art cafe kit with placemat, quiet toy, bib and coffee cup.',
  'cute 8-bit pixel art item',
  'approved',
  'published',
  current_date,
  current_date + interval '12 months',
  now()
),
(
  'move-to-one-nap-gently',
  'The one-nap shift can wobble',
  'Earlier bedtime is your friend',
  'Sleep',
  'Toddler / Sleep',
  'Toddler (12-24 months)',
  365, 600, null, null,
  67,
  false,
  'The move from two naps to one is often uneven. Some days still need two, and bedtime may move earlier for a while.',
  'Nap transitions are less a switch and more a patchy software rollout.',
  'Flexibility helps avoid turning a normal transition into weeks of overtired evenings.',
  'Let the first nap drift later, keep the afternoon gentle, and use an earlier bedtime on short-nap days.',
  'Forcing every day onto the same schedule immediately.',
  '["Watch the second nap pattern","Shift the first nap gradually","Use earlier bedtime when needed"]'::jsonb,
  '["https://raisingchildren.net.au/toddlers/sleep/understanding-sleep/toddler-sleep"]'::jsonb,
  null,
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: two small sleepy clouds merging into one cosy midday cloud above a cot.',
  '/card-images/pixel/px-move-to-one-nap-gently.png',
  'Pixel art sleepy clouds merging into one midday nap cloud above a cot.',
  'cute 8-bit pixel art item',
  'approved',
  'published',
  current_date,
  current_date + interval '12 months',
  now()
),
(
  'bottle-to-cup-one-at-a-time',
  'Swap bottles one at a time',
  'Daytime first is often easiest',
  'Tiny Gear Shift',
  'Toddler / Feeding',
  'Toddler (12-24 months)',
  340, 545, null, null,
  76,
  false,
  'Around the first birthday, many families start replacing bottles with cups. A gradual swap can make the change less dramatic.',
  'You do not need a bottle farewell ceremony. Just make one ordinary swap, then another.',
  'Moving away from bottles supports cup skills, appetite for family food and dental health.',
  'Replace one familiar daytime bottle with a cup for several days before changing another.',
  'Taking away every comfort bottle on the same difficult afternoon.',
  '["Choose one daytime bottle","Offer the cup with a familiar routine","Ask your nurse or GP if feeding or growth is a concern"]'::jsonb,
  '["https://raisingchildren.net.au/toddlers/nutrition-fitness/common-concerns/weaning-off-bottle-feeding"]'::jsonb,
  'Feeding and dental content. Review against current Australian guidance before production use.',
  false,
  false,
  false,
  false,
  true,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: a baby bottle stepping toward a small open cup across three gentle sparkle stones.',
  '/card-images/pixel/px-bottle-to-cup-one-at-a-time.png',
  'Pixel art baby bottle transitioning toward a small open cup.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'drinks-after-one',
  'Drinks change after one',
  'Water stays gloriously boring',
  'Heads Up',
  'Toddler / Feeding',
  'Toddler (12-24 months)',
  350, 450, null, null,
  79,
  false,
  'After 12 months, water remains the everyday drink, and pasteurised full-fat cow''s milk can be offered if it suits your child and family.',
  'The toddler drinks aisle is much more complicated than toddler drinks need to be.',
  'Too much milk or sweet drink can crowd out food, while plant-based alternatives need individual nutrition advice.',
  'Offer water through the day and ask your GP, dietitian or child health nurse about milk choices if needed.',
  'Toddler formula or flavoured drinks for a healthy child eating a varied diet.',
  '["Keep water easy to reach","Use a cup rather than a bottle","Ask for advice on dairy alternatives"]'::jsonb,
  '["https://raisingchildren.net.au/guides/first-1000-days/nutritious-food/healthy-drinks"]'::jsonb,
  'Feeding content. Review milk and drink wording against current Australian dietary guidance before production use.',
  false,
  false,
  false,
  false,
  true,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: a small water cup and plain milk cup beside a first-birthday sun, no words or numbers.',
  '/card-images/pixel/px-drinks-after-one.png',
  'Pixel art water cup and plain milk cup beside a birthday sun.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'brush-tiny-teeth-together',
  'Brush the tiny teeth together',
  'Their turn, then your turn',
  'Tiny Gear Shift',
  'Toddler / Dental',
  'Toddler (12-24 months)',
  365, 730, null, null,
  75,
  false,
  'Toddlers can have a practice brush, but an adult still needs to clean every tooth morning and night.',
  'Letting them go first turns a wrestling match into a very small collaboration.',
  'A predictable routine protects baby teeth and makes brushing feel like an ordinary part of the day.',
  'Use a small soft toothbrush and follow current Australian advice for toothpaste at your child''s age.',
  'A perfect two-minute brush while everyone is still learning the routine.',
  '["Brush morning and night","Let toddler practise first","Adult finishes every surface","Check toothpaste advice for their age"]'::jsonb,
  '["https://raisingchildren.net.au/toddlers/health-daily-care/dental-care/dental-care-toddlers"]'::jsonb,
  'Dental health content. Review toothpaste and fluoride wording against current Australian guidance before production use.',
  true,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: two toothbrushes, one adult and one tiny, beside a friendly mirror and small tooth sparkle.',
  '/card-images/pixel/px-brush-tiny-teeth-together.png',
  'Pixel art adult and toddler toothbrushes beside a mirror and tooth sparkle.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'rear-facing-seat-check',
  'Check the rear-facing fit',
  'Age alone does not choose the turn',
  'Heads Up',
  'Toddler / Safety',
  'Toddler (12-24 months)',
  365, 730, null, null,
  88,
  false,
  'Many children can stay rear-facing beyond their first birthday if they still fit the approved restraint''s markers and limits.',
  'Turning the seat is not a birthday milestone. The fit markers get the vote.',
  'The safest setup is an approved restraint used exactly as designed, correctly fitted and adjusted as your child grows.',
  'Read the seat''s shoulder markers and manual, then check the harness height and fit before the next drive.',
  'Turning forward because another child the same age already has.',
  '["Check shoulder markers","Read the restraint manual","Adjust harness height","Check your state road rules"]'::jsonb,
  '["https://www.nsw.gov.au/driving-boating-and-transport/roads-safety-and-rules/safe-driving/child-seats"]'::jsonb,
  'Safety and legal content. Review against current state and territory road rules before production use.',
  false,
  false,
  true,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: a rear-facing child car seat with a fit-marker sparkle and a small gum leaf charm.',
  '/card-images/pixel/px-rear-facing-seat-check.png',
  'Pixel art rear-facing child car seat with a fit-check sparkle.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'button-battery-sweep',
  'Do a button-battery sweep',
  'Remotes count too',
  'Heads Up',
  'Toddler / Safety',
  'Toddler (12-24 months)',
  365, 730, null, null,
  94,
  true,
  'Check remotes, scales, musical cards and light-up toys for secure button-battery compartments, including at grandparents'' homes.',
  'The dangerous battery is often hiding in a boring adult object, not the toy box.',
  'A swallowed or inserted button battery can cause severe internal injury quickly, even when the battery is flat.',
  'Secure loose batteries out of reach, tape both sides of used batteries, and check compartments need a tool or child-resistant action.',
  'Assuming you will notice symptoms before action is needed.',
  '["Check every remote and light-up item","Lock away new and used batteries","Save Poisons Information Centre 13 11 26","Act immediately if ingestion is suspected"]'::jsonb,
  '["https://www.productsafety.gov.au/consumers/handle-chemicals-and-poisons-safely/button-batteries-guide"]'::jsonb,
  'Urgent safety content. Review emergency wording against current ACCC guidance before production use.',
  false,
  false,
  true,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: a secured remote control and taped coin battery locked inside a high cupboard icon.',
  '/card-images/pixel/px-button-battery-sweep.png',
  'Pixel art secured remote and taped button battery with a lock symbol.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'poisons-number-saved',
  'Save the poisons number now',
  'Before you ever need it',
  'Heads Up',
  'Toddler / Safety',
  'Toddler (12-24 months)',
  365, 730, null, null,
  92,
  true,
  'The Poisons Information Centre answers 24/7 on 13 11 26 from anywhere in Australia. Save it before cupboards become interesting.',
  'In a scary minute, a saved contact is much better than a search result.',
  'Poisoning advice depends on the exact substance and amount. Expert phone guidance tells you what to do next.',
  'Save 13 11 26 in every carer''s phone and keep medicines, cleaners and chemicals locked away and in original containers.',
  'Waiting for symptoms before calling if you think exposure happened.',
  '["Save 13 11 26","Lock medicines and cleaners","Keep products in original containers","Call 000 for collapse, seizure or breathing trouble"]'::jsonb,
  '["https://www.healthdirect.gov.au/poisoning"]'::jsonb,
  'Medical and urgent safety content. Review emergency wording before production use.',
  true,
  false,
  true,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: a phone with a simple shield icon beside a locked cleaning cupboard, no text or numbers.',
  '/card-images/pixel/px-poisons-number-saved.png',
  'Pixel art phone with a shield beside a locked household cleaning cupboard.',
  'cute 8-bit pixel art item',
  'approved',
  'in_review',
  null,
  null,
  null
),
(
  'transition-warning-countdown',
  'Give the two-minute warning',
  'Transitions need a runway',
  'Parent Sanity',
  'Toddler / Behaviour',
  'Toddler (12-24 months)',
  420, 730, null, null,
  64,
  false,
  'A short, repeated warning before leaving the bath, park or playroom can soften the switch between activities.',
  'Surprise endings are hard when your whole life is happening right now.',
  'Predictable language gives toddlers a little time to process change, even when they still protest.',
  'Use the same simple sequence: two more minutes, one last turn, then we go.',
  'A long negotiation or expecting the warning to prevent every feeling.',
  '["Use one familiar warning phrase","Offer one last turn","Follow through calmly"]'::jsonb,
  '[]'::jsonb,
  null,
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: three stepping stones leading from toy blocks to tiny shoes with a gentle arrow and sparkles.',
  '/card-images/pixel/px-transition-warning-countdown.png',
  'Pixel art stepping stones from toy blocks to tiny shoes for a toddler transition warning.',
  'cute 8-bit pixel art item',
  'approved',
  'published',
  current_date,
  current_date + interval '12 months',
  now()
),
(
  'two-choices-not-twenty',
  'Offer two choices, not twenty',
  'Independence with guardrails',
  'Parent Sanity',
  'Toddler / Behaviour',
  'Toddler (12-24 months)',
  420, 730, null, null,
  61,
  false,
  'Two acceptable options let a toddler practise independence without handing them an impossible open-ended decision.',
  'Blue cup or yellow cup is a choice. What do you want is a research project.',
  'Small choices can reduce power struggles while keeping the adult responsible for the boundary.',
  'Pick one daily friction point and offer two options you are genuinely happy to accept.',
  'Offering a choice when there is only one possible answer.',
  '["Choose one friction point","Offer two acceptable options","Keep the wording short"]'::jsonb,
  '[]'::jsonb,
  null,
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: two weather-ready toddler outfits on hangers with a cheerful choice sparkle between them.',
  '/card-images/pixel/px-two-choices-not-twenty.png',
  'Pixel art two toddler outfits on hangers representing a simple choice.',
  'cute 8-bit pixel art item',
  'approved',
  'published',
  current_date,
  current_date + interval '12 months',
  now()
),
(
  'playground-go-bag',
  'Keep a playground go-bag',
  'The outing is already half packed',
  'Fun First',
  'Toddler / Outings',
  'Toddler (12-24 months)',
  365, 730, null, null,
  49,
  false,
  'A permanent little bag with water, hat, wipes and a simple snack makes spontaneous park stops much easier.',
  'The best family adventure equipment is the bag that was already in the car.',
  'Removing packing friction creates more chances for a quick play, a coastal walk or a sanity-saving change of scene.',
  'Pack the basics, keep the bag by the door, and refresh food and water before leaving.',
  'Enough gear for an expedition when the local slide is ten minutes away.',
  '["Water bottle","Broad-brim hat","Wipes and spare nappy","Simple snack","Tiny towel or picnic cloth"]'::jsonb,
  '[]'::jsonb,
  null,
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: a small playground bag with water bottle, broad-brim hat, wipes and snack container.',
  '/card-images/pixel/px-playground-go-bag.png',
  'Pixel art playground bag with water bottle, sun hat, wipes and snack container.',
  'cute 8-bit pixel art item',
  'approved',
  'published',
  current_date,
  current_date + interval '12 months',
  now()
)
on conflict (slug) do update set
  title = excluded.title,
  subtitle = excluded.subtitle,
  card_type = excluded.card_type,
  category = excluded.category,
  life_stage = excluded.life_stage,
  start_age_days = excluded.start_age_days,
  end_age_days = excluded.end_age_days,
  pregnancy_week_start = excluded.pregnancy_week_start,
  pregnancy_week_end = excluded.pregnancy_week_end,
  priority = excluded.priority,
  time_critical = excluded.time_critical,
  short_summary = excluded.short_summary,
  wish_i_knew = excluded.wish_i_knew,
  why_it_matters = excluded.why_it_matters,
  what_to_do_now = excluded.what_to_do_now,
  what_can_wait = excluded.what_can_wait,
  checklist_items = excluded.checklist_items,
  source_urls = excluded.source_urls,
  source_notes = excluded.source_notes,
  medical_sensitivity = excluded.medical_sensitivity,
  government_sensitivity = excluded.government_sensitivity,
  safety_sensitivity = excluded.safety_sensitivity,
  allergy_sensitivity = excluded.allergy_sensitivity,
  feeding_sensitivity = excluded.feeding_sensitivity,
  conditions = excluded.conditions,
  illustration_prompt = excluded.illustration_prompt,
  image_url = excluded.image_url,
  image_alt = excluded.image_alt,
  image_style = excluded.image_style,
  image_status = excluded.image_status,
  status = excluded.status,
  last_reviewed_at = excluded.last_reviewed_at,
  review_due_date = excluded.review_due_date,
  published_at = excluded.published_at,
  updated_at = now();

