-- Baby weekly anchor cards (weeks 1–52). Safe to re-run (upserts by slug).
-- Review and publish from /admin after adding pixel art.

insert into public.timeline_cards (
  slug, title, subtitle, card_type, category, life_stage,
  start_age_days, end_age_days, pregnancy_week_start, pregnancy_week_end,
  priority, time_critical, short_summary, wish_i_knew, why_it_matters,
  what_to_do_now, what_can_wait, checklist_items, source_urls, source_notes,
  medical_sensitivity, government_sensitivity, safety_sensitivity,
  allergy_sensitivity, feeding_sensitivity, conditions, illustration_prompt,
  image_url, image_alt, image_style, image_status, status,
  last_reviewed_at, review_due_date, published_at
) values
(
  'baby-week-1',
  'Brand new earthside',
  'Baby week 1',
  'This week with bub',
  'Baby / This week',
  'Newborn',
  0,
  6,
  null,
  null,
  100,
  false,
  'Your newborn is adjusting to light, sound and feeding outside the womb. Short wake windows and cluster feeds are normal.',
  'Week one is mostly feeding, sleeping, and surviving — for both of you.',
  null,
  'Noticing one tiny thing bub does that delights you is enough of a win for week one.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: Cute pixel art newborn bundle with a tiny hat and soft blanket heart, warm cream and teal palette.',
  '/card-images/pixel/px-baby-week-1.png',
  'Pixel art illustration for baby week 1.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'baby-week-2',
  'Settling into rhythm',
  'Baby week 2',
  'This week with bub',
  'Baby / This week',
  'Newborn',
  7,
  13,
  null,
  null,
  100,
  false,
  'Feeding patterns may start to stretch slightly. Crying peaks for many babies around now before easing.',
  'There is still no reliable schedule. That is not you failing — it is week two.',
  null,
  'Accepting help for one household job so you can rest in a nap window is allowed — and smart.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: Cute pixel art rocking chair and tiny socks, soft morning light, warm cream and teal palette.',
  '/card-images/pixel/px-baby-week-2.png',
  'Pixel art illustration for baby week 2.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'baby-week-3',
  'First little social smiles',
  'Baby week 3',
  'This week with bub',
  'Baby / This week',
  'Newborn',
  14,
  20,
  null,
  null,
  100,
  false,
  'Bub may start brief eye contact and early social responses. Tummy time in tiny bursts builds neck strength.',
  'Real smiles can appear around now — they hit harder than you expect.',
  null,
  'A short burst of tummy time after a nappy change is something many parents try; stop when bub is done.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: Cute pixel art baby face with sparkle eyes and gentle smile curve, warm cream and teal palette.',
  '/card-images/pixel/px-baby-week-3.png',
  'Pixel art illustration for baby week 3.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'baby-week-4',
  'The four-week mark',
  'Baby week 4',
  'This week with bub',
  'Baby / This week',
  'Newborn',
  21,
  27,
  null,
  null,
  100,
  false,
  'Many families have a GP check around the four-week mark. Feeding and weight gain are the main focus.',
  'One month sounds small. From where you are standing it probably feels enormous.',
  null,
  'The four-week check is worth putting on the radar if it is due — your GP or child health nurse can confirm timing.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: Cute pixel art calendar with one heart sticker and stethoscope charm, warm cream and teal palette.',
  '/card-images/pixel/px-baby-week-4.png',
  'Pixel art illustration for baby week 4.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'baby-week-5',
  'Sounds and stares',
  'Baby week 5',
  'This week with bub',
  'Baby / This week',
  'Newborn',
  28,
  34,
  null,
  null,
  100,
  false,
  'Vision is still fuzzy but faces are fascinating. Cooing and throaty sounds may begin.',
  'Bub may stare at your face like you are the most interesting show on earth — because you are.',
  null,
  'Holding bub a little closer during a calm alert moment can make eye contact easier. No perfect distance required.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: Cute pixel art parent silhouette and baby eyes meeting, soft heart sparkle, cream and teal palette.',
  '/card-images/pixel/px-baby-week-5.png',
  'Pixel art illustration for baby week 5.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'baby-week-6',
  'Longer stretches (maybe)',
  'Baby week 6',
  'This week with bub',
  'Baby / This week',
  'Newborn',
  35,
  41,
  null,
  null,
  100,
  false,
  'Sleep is still irregular. Immunisation conversations often start around six to eight weeks in Australia.',
  'Some nights get a little longer between feeds. Others do not. Both belong to week six.',
  null,
  'Worth checking when the next immunisation is due — your blue book, GP, or health.gov.au immunisation pages are solid places to look.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: Cute pixel art moon and baby bottle with shield badge, warm cream and teal palette.',
  '/card-images/pixel/px-baby-week-6.png',
  'Pixel art illustration for baby week 6.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'baby-week-7',
  'Wobbly head control',
  'Baby week 7',
  'This week with bub',
  'Baby / This week',
  'Newborn',
  42,
  48,
  null,
  null,
  100,
  false,
  'During tummy time bub may lift their head briefly. Always supervise on a firm flat surface.',
  'Head control improves in micro-increments — like levelling up in a game you did not know you were playing.',
  null,
  'Tucking a tiny tummy-time moment into one nappy change is a low-friction habit if it suits your day.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: Cute pixel art baby doing mini tummy time on a play mat, warm cream and teal palette.',
  '/card-images/pixel/px-baby-week-7.png',
  'Pixel art illustration for baby week 7.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'baby-week-8',
  'Two months approaching',
  'Baby week 8',
  'This week with bub',
  'Baby / This week',
  'Newborn',
  49,
  55,
  null,
  null,
  100,
  false,
  'Social smiling is more reliable. Some babies show clearer fussy periods in late afternoon.',
  'Eight weeks is a common checkpoint for feeding, sleep and how you are really doing.',
  null,
  'Worried about feeding or how you are travelling? A GP or child health nurse chat is a good place to start — search your local child health service too.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: Cute pixel art two-month milestone ribbon and rattle, warm cream and teal palette.',
  '/card-images/pixel/px-baby-week-8.png',
  'Pixel art illustration for baby week 8.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'baby-week-9',
  'Hands discover hands',
  'Baby week 9',
  'This week with bub',
  'Baby / This week',
  'Baby',
  56,
  62,
  null,
  null,
  100,
  false,
  'Hand discovery and batting at objects begins. Vision and tracking improve week by week.',
  'Watching bub stare at their own fingers is free entertainment.',
  null,
  'A high-contrast toy or your fingers during alert time can be fun to offer. Bub will tell you when they are done.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: Cute pixel art baby hands and simple black-white toy, warm cream and teal palette.',
  '/card-images/pixel/px-baby-week-9.png',
  'Pixel art illustration for baby week 9.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'baby-week-10',
  'Chatting back',
  'Baby week 10',
  'This week with bub',
  'Baby / This week',
  'Baby',
  63,
  69,
  null,
  null,
  100,
  false,
  'Bub may vocalise when you pause, as if replying. This builds language foundations.',
  'Turn-taking coos are the first conversations. You are already fluent.',
  null,
  'Leaving a pause after you speak lets bub fill the silence sometimes. Turn-taking, not performance.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: Cute pixel art speech bubble hearts between parent and baby icons, cream and teal palette.',
  '/card-images/pixel/px-baby-week-10.png',
  'Pixel art illustration for baby week 10.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'baby-week-11',
  'Rolling prep',
  'Baby week 11',
  'This week with bub',
  'Baby / This week',
  'Baby',
  70,
  76,
  null,
  null,
  100,
  false,
  'Stronger neck and shoulder muscles prepare for rolling. Never leave bub unattended on elevated surfaces.',
  'Some babies start rolling early. Others wait months. Your timeline is fine.',
  null,
  'Clearing a bit of floor for supervised play can make rolling experiments safer when they start.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: Cute pixel art play mat with rolling arrow sparkle, warm cream and teal palette.',
  '/card-images/pixel/px-baby-week-11.png',
  'Pixel art illustration for baby week 11.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'baby-week-12',
  'Three months',
  'Baby week 12',
  'This week with bub',
  'Baby / This week',
  'Baby',
  77,
  83,
  null,
  null,
  100,
  false,
  'Many babies laugh out loud around now. Sleep may begin to consolidate slightly for some families.',
  'Quarter of a year. You have been showing up through the thick of it.',
  null,
  'Three months is worth marking somehow — a photo, a cake, or a nap all count.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: Cute pixel art three-month cake candle and baby booties, warm cream and teal palette.',
  '/card-images/pixel/px-baby-week-12.png',
  'Pixel art illustration for baby week 12.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'baby-week-13',
  'Reach and grab',
  'Baby week 13',
  'This week with bub',
  'Baby / This week',
  'Baby',
  84,
  90,
  null,
  null,
  100,
  false,
  'Purposeful reaching develops. Safe toys within arm''s length keep exploration calm.',
  'Everything reachable is now a scientific instrument.',
  null,
  'Rotating a couple of toys on the play mat keeps things interesting without buying more stuff.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: Cute pixel art reaching hand and soft rattle, warm cream and teal palette.',
  '/card-images/pixel/px-baby-week-13.png',
  'Pixel art illustration for baby week 13.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'baby-week-14',
  'Predictable fuss windows',
  'Baby week 14',
  'This week with bub',
  'Baby / This week',
  'Baby',
  91,
  97,
  null,
  null,
  100,
  false,
  'Short awake windows still rule. Over tiredness shows up fast.',
  'You might notice when bub is usually happiest — use that window for outings.',
  null,
  'Noting one reliable calm hour in your phone can help when you need to plan a short outing.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: Cute pixel art sun clock and pram icon, warm cream and teal palette.',
  '/card-images/pixel/px-baby-week-14.png',
  'Pixel art illustration for baby week 14.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'baby-week-15',
  'Babbling experiments',
  'Baby week 15',
  'This week with bub',
  'Baby / This week',
  'Baby',
  98,
  104,
  null,
  null,
  100,
  false,
  'Repeated sounds like ba-ba or ga-ga may appear. Respond like it makes perfect sense.',
  'The vowel concert series has begun. Applause optional but encouraged.',
  null,
  'Mirroring bub''s sounds back is a simple, optional conversation starter.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: Cute pixel art musical notes and baby mouth shape, warm cream and teal palette.',
  '/card-images/pixel/px-baby-week-15.png',
  'Pixel art illustration for baby week 15.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'baby-week-16',
  'Rolling may start',
  'Baby week 16',
  'This week with bub',
  'Baby / This week',
  'Baby',
  105,
  111,
  null,
  null,
  100,
  false,
  'Rolling front to back or back to front can start. Lower the cot before standing phase later.',
  'The moment they roll once, your floor lifestyle begins. Welcome.',
  null,
  'Change tables and sofas reward a habit of one hand on bub — search baby fall prevention if you want a refresher.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: Cute pixel art rolling baby arrow on soft mat, warm cream and teal palette.',
  '/card-images/pixel/px-baby-week-16.png',
  'Pixel art illustration for baby week 16.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'baby-week-17',
  'Object permanence seeds',
  'Baby week 17',
  'This week with bub',
  'Baby / This week',
  'Baby',
  112,
  118,
  null,
  null,
  100,
  false,
  'Bub begins to understand things exist when hidden briefly. Games build trust and giggles.',
  'Peek-a-boo is about to become a stadium event.',
  null,
  'Peek-a-boo with a muslin once a day is optional entertainment with a side of learning.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: Cute pixel art muslin cloth peek-a-boo face, warm cream and teal palette.',
  '/card-images/pixel/px-baby-week-17.png',
  'Pixel art illustration for baby week 17.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'baby-week-18',
  'Sitting with support',
  'Baby week 18',
  'This week with bub',
  'Baby / This week',
  'Baby',
  119,
  125,
  null,
  null,
  100,
  false,
  'Core strength grows. Prop with pillows or sit in your lap facing out.',
  'Supported sitting changes the view — for bub and for your arms.',
  null,
  'Supported sitting for a minute after a feed, when content, is something to try if bub seems ready — skip if they fuss.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: Cute pixel art baby sitting with pillow support, warm cream and teal palette.',
  '/card-images/pixel/px-baby-week-18.png',
  'Pixel art illustration for baby week 18.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'baby-week-19',
  'Teeth may be brewing',
  'Baby week 19',
  'This week with bub',
  'Baby / This week',
  'Baby',
  126,
  132,
  null,
  null,
  100,
  false,
  'Some babies teethe early. Chew toys and chilled cloths can soothe — follow product safety guidance.',
  'Drool fashion week is not your fault.',
  null,
  'If everything is going in the mouth, a safe teether is worth having around. Check product safety labelling, or search ACCC baby product safety.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: Cute pixel art teether ring and drool bib, warm cream and teal palette.',
  '/card-images/pixel/px-baby-week-19.png',
  'Pixel art illustration for baby week 19.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'baby-week-20',
  'Halfway to one',
  'Baby week 20',
  'This week with bub',
  'Baby / This week',
  'Baby',
  133,
  139,
  null,
  null,
  100,
  false,
  'Many babies transfer objects hand to hand. Exploration gets messier and more joyful.',
  'Twenty weeks since birth — the newborn fog and the current you can coexist in one photo.',
  null,
  'A comparison photo from week one is optional nostalgia — only if you want it.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: Cute pixel art half-year milestone star and blocks, warm cream and teal palette.',
  '/card-images/pixel/px-baby-week-20.png',
  'Pixel art illustration for baby week 20.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'baby-week-21',
  'Stranger awareness',
  'Baby week 21',
  'This week with bub',
  'Baby / This week',
  'Baby',
  140,
  146,
  null,
  null,
  100,
  false,
  'Bub may show caution with unfamiliar faces. Slow introductions help.',
  'Preferring you is biology, not drama.',
  null,
  'Letting visitors wait a minute before picking up can help if bub is warming up slowly to new faces.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: Cute pixel art friendly visitor wave and baby clutching parent, cream and teal palette.',
  '/card-images/pixel/px-baby-week-21.png',
  'Pixel art illustration for baby week 21.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'baby-week-22',
  'Solid food curiosity',
  'Baby week 22',
  'This week with bub',
  'Baby / This week',
  'Baby',
  147,
  153,
  null,
  null,
  100,
  false,
  'Around six months many families start solids. Readiness signs matter more than the calendar.',
  'Watching you eat is their research phase.',
  null,
  'Watching whether bub is interested in your food and sitting with a bit of support is part of solids readiness chatter — search Australian Infant Feeding Guidelines when you get there.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: Cute pixel art high chair tray with soft spoon and avocado slice, cream and teal palette.',
  '/card-images/pixel/px-baby-week-22.png',
  'Pixel art illustration for baby week 22.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'baby-week-23',
  'Comms beyond crying',
  'Baby week 23',
  'This week with bub',
  'Baby / This week',
  'Baby',
  154,
  160,
  null,
  null,
  100,
  false,
  'Bub communicates wants with sounds and gestures. Naming what you see builds language.',
  'Pointed looks and grunts are full sentences if you squint.',
  null,
  'Narrating one routine out loud (nappy, bath, walk) is optional language practice that fits into things you already do.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: Cute pixel art gesture hands and heart speech bubble, warm cream and teal palette.',
  '/card-images/pixel/px-baby-week-23.png',
  'Pixel art illustration for baby week 23.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'baby-week-24',
  'Six months',
  'Baby week 24',
  'This week with bub',
  'Baby / This week',
  'Baby',
  161,
  167,
  null,
  null,
  100,
  false,
  'A major milestone month. Immunisations, solids and sitting often cluster around here.',
  'Half a year. Half a year of learning each other.',
  null,
  'Six-month checks and immunisations are worth confirming if due — GP, child health nurse, or your immunisation history online.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: Cute pixel art six-month banner and stacking cups, warm cream and teal palette.',
  '/card-images/pixel/px-baby-week-24.png',
  'Pixel art illustration for baby week 24.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'baby-week-25',
  'Sitting solo (briefly)',
  'Baby week 25',
  'This week with bub',
  'Baby / This week',
  'Baby',
  168,
  174,
  null,
  null,
  100,
  false,
  'Balance improves with padding nearby. Soft surfaces and supervision always.',
  'Independent sitting for five seconds deserves a medal.',
  null,
  'A small safe floor play zone with soft padding nearby can make early sitting experiments less stressful.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: Cute pixel art baby sitting alone with soft block tower, cream and teal palette.',
  '/card-images/pixel/px-baby-week-25.png',
  'Pixel art illustration for baby week 25.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'baby-week-26',
  'First foods mess',
  'Baby week 26',
  'This week with bub',
  'Baby / This week',
  'Baby',
  175,
  181,
  null,
  null,
  100,
  false,
  'Iron-rich foods matter in the Australian guidance. Mess is part of motor learning.',
  'The point of early solids is exposure, not a clean kitchen.',
  null,
  'A cover bib or nappy-only meal can make early solids mess more manageable. Exposure over tidy kitchens.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: Cute pixel art messy bowl and splatter-proof bib, warm cream and teal palette.',
  '/card-images/pixel/px-baby-week-26.png',
  'Pixel art illustration for baby week 26.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'baby-week-27',
  'Transfer masterclass',
  'Baby week 27',
  'This week with bub',
  'Baby / This week',
  'Baby',
  182,
  188,
  null,
  null,
  100,
  false,
  'Passing toys between hands supports brain wiring. Offer varied textures.',
  'Two toys, one in each hand, maximum satisfaction.',
  null,
  'Two safe objects within reach during floor play is a low-effort way to invite hand-to-hand practice.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: Cute pixel art two textured blocks swapping hands, warm cream and teal palette.',
  '/card-images/pixel/px-baby-week-27.png',
  'Pixel art illustration for baby week 27.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'baby-week-28',
  'Mobile or not yet',
  'Baby week 28',
  'This week with bub',
  'Baby / This week',
  'Baby',
  189,
  195,
  null,
  null,
  100,
  false,
  'Some babies scoot early. Baby-proofing low cupboards starts to matter.',
  'Army crawling counts. So does rolling everywhere. Mobility has many styles.',
  null,
  'A quick scan of one room from floor level can reveal choking hazards you stop seeing at adult height. Search babyproofing checklist if you want a fuller list.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: Cute pixel art baby crawling arrow and cupboard lock, warm cream and teal palette.',
  '/card-images/pixel/px-baby-week-28.png',
  'Pixel art illustration for baby week 28.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'baby-week-29',
  'Sleep shifts again',
  'Baby week 29',
  'This week with bub',
  'Baby / This week',
  'Baby',
  196,
  202,
  null,
  null,
  100,
  false,
  'Developmental leaps can disturb sleep briefly. Consistency helps more than new gadgets.',
  'Just when you tell someone it got better, week twenty-nine sends a plot twist.',
  null,
  'Keeping bedtime in a short, familiar order helps some families more than new gadgets. Search infant sleep routines for ideas that fit you.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: Cute pixel art bedtime book and dim lamp, warm cream and teal palette.',
  '/card-images/pixel/px-baby-week-29.png',
  'Pixel art illustration for baby week 29.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'baby-week-30',
  'Seven months',
  'Baby week 30',
  'This week with bub',
  'Baby / This week',
  'Baby',
  203,
  209,
  null,
  null,
  100,
  false,
  'Babbling may include consonant sounds. Social games stay a hit.',
  'Seven months of practice being a parent — you are not a beginner anymore.',
  null,
  'A regular floor-play pocket at a similar time of day can become a nice anchor — whenever works.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: Cute pixel art seven star badge and rubber duck, warm cream and teal palette.',
  '/card-images/pixel/px-baby-week-30.png',
  'Pixel art illustration for baby week 30.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'baby-week-31',
  'Pulling up prep',
  'Baby week 31',
  'This week with bub',
  'Baby / This week',
  'Baby',
  210,
  216,
  null,
  null,
  100,
  false,
  'Leg strength builds for standing. Lower cot mattress if bub is pulling up in the cot.',
  'Furniture cruising is audition season.',
  null,
  'If bub is pulling up in the cot, cot mattress height and bumper guidance are worth a look — search Red Nose or product instructions.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: Cute pixel art cot rail and strong little legs, warm cream and teal palette.',
  '/card-images/pixel/px-baby-week-31.png',
  'Pixel art illustration for baby week 31.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'baby-week-32',
  'Finger food fun',
  'Baby week 32',
  'This week with bub',
  'Baby / This week',
  'Baby',
  217,
  223,
  null,
  null,
  100,
  false,
  'Soft finger foods support self-feeding skills. Stay nearby for safety.',
  'Pincer grasp turns snacks into a fine motor sport.',
  null,
  'One soft finger food at a shared meal is a gentle way to explore self-feeding when you are ready. Australian solids guidance is easy to search.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: Cute pixel art finger food plate with banana coin and cup, cream and teal palette.',
  '/card-images/pixel/px-baby-week-32.png',
  'Pixel art illustration for baby week 32.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'baby-week-33',
  'Separation peek-a-boo',
  'Baby week 33',
  'This week with bub',
  'Baby / This week',
  'Baby',
  224,
  230,
  null,
  null,
  100,
  false,
  'Brief separation games build confidence. Always return with a calm hello.',
  'Short goodbyes beat long anxious ones.',
  null,
  'A short leave-the-room-and-return practice can build confidence for some babies. Keep it calm and brief.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: Cute pixel art doorway wave and teddy waiting, warm cream and teal palette.',
  '/card-images/pixel/px-baby-week-33.png',
  'Pixel art illustration for baby week 33.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'baby-week-34',
  'Eight months',
  'Baby week 34',
  'This week with bub',
  'Baby / This week',
  'Baby',
  231,
  237,
  null,
  null,
  100,
  false,
  'Crawling, sitting and babbling combine into busy days. Energy comes in bursts.',
  'Eight months looks different in every house — compare gently, if at all.',
  null,
  'Planning one low-effort outing that matches bub''s rhythm beats forcing a big day out.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: Cute pixel art eight-month medal and playground leaf, warm cream and teal palette.',
  '/card-images/pixel/px-baby-week-34.png',
  'Pixel art illustration for baby week 34.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'baby-week-35',
  'Object exploration',
  'Baby week 35',
  'This week with bub',
  'Baby / This week',
  'Baby',
  238,
  244,
  null,
  null,
  100,
  false,
  'Cause and effect play is peak comedy for bub. Safe pots and wooden spoons count.',
  'Banging two blocks together is acoustics research.',
  null,
  'A drawer or basket of safe kitchen items (wooden spoon, plastic tub) can turn exploration into free entertainment.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: Cute pixel art wooden spoon and pot with sparkles, warm cream and teal palette.',
  '/card-images/pixel/px-baby-week-35.png',
  'Pixel art illustration for baby week 35.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'baby-week-36',
  'Standing hangs',
  'Baby week 36',
  'This week with bub',
  'Baby / This week',
  'Baby',
  245,
  251,
  null,
  null,
  100,
  false,
  'Many babies stand holding furniture. Sharp corners deserve softening or supervision.',
  'Pull-to-stand on the couch is their gym membership.',
  null,
  'Padding or blocking one sharp coffee table corner is a small, practical thought if cruising is starting.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: Cute pixel art couch edge and standing baby hands, warm cream and teal palette.',
  '/card-images/pixel/px-baby-week-36.png',
  'Pixel art illustration for baby week 36.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'baby-week-37',
  'Wave hello',
  'Baby week 37',
  'This week with bub',
  'Baby / This week',
  'Baby',
  252,
  258,
  null,
  null,
  100,
  false,
  'Imitation of gestures like waving or clapping may start. Model without pressure.',
  'A floppy wave from bub can fix a hard day.',
  null,
  'Waving goodbye at one predictable moment models a gesture without turning it into homework.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: Cute pixel art waving hand with hello sparkle, warm cream and teal palette.',
  '/card-images/pixel/px-baby-week-37.png',
  'Pixel art illustration for baby week 37.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'baby-week-38',
  'Nine months',
  'Baby week 38',
  'This week with bub',
  'Baby / This week',
  'Baby',
  259,
  265,
  null,
  null,
  100,
  false,
  'Mobility increases curiosity. Double-check stairs and pet bowls.',
  'Nine months in — you have a relationship now, not just a routine.',
  null,
  'If stairs are in play, a stair gate is worth thinking about — search Australian stair gate safety and measure before you buy.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: Cute pixel art stair gate and teddy, warm cream and teal palette.',
  '/card-images/pixel/px-baby-week-38.png',
  'Pixel art illustration for baby week 38.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'baby-week-39',
  'Clapping phase',
  'Baby week 39',
  'This week with bub',
  'Baby / This week',
  'Baby',
  266,
  272,
  null,
  null,
  100,
  false,
  'Clapping and repetitive games reinforce joy and coordination.',
  'Applause for eating one pea is valid parenting.',
  null,
  'A clap when bub does something small is optional cheerleading they often notice.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: Cute pixel art clapping hands and confetti hearts, warm cream and teal palette.',
  '/card-images/pixel/px-baby-week-39.png',
  'Pixel art illustration for baby week 39.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'baby-week-40',
  'Cruising furniture',
  'Baby week 40',
  'This week with bub',
  'Baby / This week',
  'Baby',
  273,
  279,
  null,
  null,
  100,
  false,
  'Cruising builds balance for independent steps later. Clear paths help.',
  'Side-stepping along the sofa is the pre-walking tour.',
  null,
  'Moving stable furniture into a safer cruising line can reduce the ''oh no'' moments.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: Cute pixel art sofa cruise path with arrow, warm cream and teal palette.',
  '/card-images/pixel/px-baby-week-40.png',
  'Pixel art illustration for baby week 40.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'baby-week-41',
  'First words loading',
  'Baby week 41',
  'This week with bub',
  'Baby / This week',
  'Toddler',
  280,
  286,
  null,
  null,
  100,
  false,
  'Early word-like sounds emerge. Reading one board book daily helps.',
  'Ma-ma and da-da might be practice sounds long before they mean you — enjoy anyway.',
  null,
  'Pointing at a picture and naming one object per page is a gentle reading habit if you have a board book handy.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: Cute pixel art board book with apple and cat icons, warm cream and teal palette.',
  '/card-images/pixel/px-baby-week-41.png',
  'Pixel art illustration for baby week 41.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'baby-week-42',
  'Ten months',
  'Baby week 42',
  'This week with bub',
  'Baby / This week',
  'Toddler',
  287,
  293,
  null,
  null,
  100,
  false,
  'Fine motor play improves. Stacking and dumping are peak toddler prep.',
  'Ten months of micro-decisions that add up to a childhood.',
  null,
  'A container to fill and empty safely is peak ten-month entertainment for many babies.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: Cute pixel art stacking rings and bucket, warm cream and teal palette.',
  '/card-images/pixel/px-baby-week-42.png',
  'Pixel art illustration for baby week 42.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'baby-week-43',
  'Opinions appear',
  'Baby week 43',
  'This week with bub',
  'Baby / This week',
  'Toddler',
  294,
  300,
  null,
  null,
  100,
  false,
  'Preferences show clearly. Offer two acceptable choices when you can.',
  'The head shake when they do not want something is early boundary setting.',
  null,
  'Holding up two acceptable options (outfits, snacks) lets bub practise choosing without a power struggle.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: Cute pixel art two-choice cards with heart icons, warm cream and teal palette.',
  '/card-images/pixel/px-baby-week-43.png',
  'Pixel art illustration for baby week 43.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'baby-week-44',
  'Walking may be close',
  'Baby week 44',
  'This week with bub',
  'Baby / This week',
  'Toddler',
  301,
  307,
  null,
  null,
  100,
  false,
  'First steps need bare feet on safe floors for balance practice.',
  'Some walk at ten months. Some at sixteen. The range is enormous.',
  null,
  'Clearing a walking lane across one room helps if first steps are close — bare feet on safe floors are commonly suggested.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: Cute pixel art first steps footprint trail, warm cream and teal palette.',
  '/card-images/pixel/px-baby-week-44.png',
  'Pixel art illustration for baby week 44.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'baby-week-45',
  'Eleven months',
  'Baby week 45',
  'This week with bub',
  'Baby / This week',
  'Toddler',
  308,
  314,
  null,
  null,
  100,
  false,
  'Sleep, food and movement keep shifting. Routine anchors still help.',
  'Eleven months feels like the last chapter before the one-year party.',
  null,
  'A simple list for a low-key first birthday is optional planning, not a Pinterest brief.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: Cute pixel art eleven candle and party hat, warm cream and teal palette.',
  '/card-images/pixel/px-baby-week-45.png',
  'Pixel art illustration for baby week 45.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'baby-week-46',
  'Pointing at everything',
  'Baby week 46',
  'This week with bub',
  'Baby / This week',
  'Toddler',
  315,
  321,
  null,
  null,
  100,
  false,
  'Joint attention links words to the world. Name what they point at.',
  'Shared pointing is how bub says look at that with you.',
  null,
  'Following bub''s point and saying the object''s name once is shared attention in its simplest form.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: Cute pixel art pointing finger and dog icon, warm cream and teal palette.',
  '/card-images/pixel/px-baby-week-46.png',
  'Pixel art illustration for baby week 46.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'baby-week-47',
  'Helpful mimicry',
  'Baby week 47',
  'This week with bub',
  'Baby / This week',
  'Toddler',
  322,
  328,
  null,
  null,
  100,
  false,
  'Imitation of daily tasks emerges. Tiny chores become play.',
  'They will copy wiping the table with a sock. Praise the effort.',
  null,
  'A clean cloth during tidy-up can turn copying into a tiny helpful game.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: Cute pixel art mini cloth and toy broom, warm cream and teal palette.',
  '/card-images/pixel/px-baby-week-47.png',
  'Pixel art illustration for baby week 47.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'baby-week-48',
  'One year approaching',
  'Baby week 48',
  'This week with bub',
  'Baby / This week',
  'Toddler',
  329,
  335,
  null,
  null,
  100,
  false,
  'Walking, words and personality converge. Immunisations may include twelve-month doses.',
  'The first birthday is for you as much as bub — you crossed a year together.',
  null,
  'Twelve-month health visit timing is worth confirming soon — GP, child health nurse, or your reminder texts.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: Cute pixel art birthday one candle and number block, warm cream and teal palette.',
  '/card-images/pixel/px-baby-week-48.png',
  'Pixel art illustration for baby week 48.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'baby-week-49',
  'Cup practice',
  'Baby week 49',
  'This week with bub',
  'Baby / This week',
  'Toddler',
  336,
  342,
  null,
  null,
  100,
  false,
  'Transition toward cup drinking supports oral development. Small sips with help.',
  'Water on the shirt is tuition for open-cup skills.',
  null,
  'A small open cup or straw cup at one meal is something to try when you are ready. Search cup drinking for babies for current tips.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: Cute pixel art training cup with water droplet, warm cream and teal palette.',
  '/card-images/pixel/px-baby-week-49.png',
  'Pixel art illustration for baby week 49.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'baby-week-50',
  'Dance breaks',
  'Baby week 50',
  'This week with bub',
  'Baby / This week',
  'Toddler',
  343,
  349,
  null,
  null,
  100,
  false,
  'Rhythm and movement support coordination and mood for everyone.',
  'Bouncing to music is gross motor joy — join in.',
  null,
  'One song and a sixty-second dance break is optional joy for everyone in the room.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: Cute pixel art music note and dancing shoes, warm cream and teal palette.',
  '/card-images/pixel/px-baby-week-50.png',
  'Pixel art illustration for baby week 50.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'baby-week-51',
  'Simple instructions',
  'Baby week 51',
  'This week with bub',
  'Baby / This week',
  'Toddler',
  350,
  356,
  null,
  null,
  100,
  false,
  'Receptive language runs ahead of speech. Simple one-step requests are worth trying.',
  'Give the block may work before you expect it.',
  null,
  'Asking for one easy action (''give me the ball'') is receptive language practice if bub is in the mood.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: Cute pixel art ball and open hand gesture, warm cream and teal palette.',
  '/card-images/pixel/px-baby-week-51.png',
  'Pixel art illustration for baby week 51.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
),
(
  'baby-week-52',
  'One whole year',
  'Baby week 52',
  'This week with bub',
  'Baby / This week',
  'Toddler',
  357,
  363,
  null,
  null,
  100,
  false,
  'A year of growth for bub and for you. Walking, words and personality keep unfolding.',
  'You made it through year one. That is not small.',
  null,
  'Writing one sentence about year one for future you is a small gift to yourself.',
  null,
  '[]'::jsonb,
  '[]'::jsonb,
  'Suggestions only — not individual medical advice. Prefer your GP, midwife, child health nurse, or trusted sources (e.g. healthdirect, Pregnancy Care Guidelines, Infant Feeding Guidelines). Search when unsure.',
  false,
  false,
  false,
  false,
  false,
  '{"born_only":true}'::jsonb,
  'Cute pixel art collectible: Cute pixel art first birthday cake and confetti, warm cream and teal palette.',
  '/card-images/pixel/px-baby-week-52.png',
  'Pixel art illustration for baby week 52.',
  'cute 8-bit pixel art item',
  'needed',
  'in_review',
  null,
  null,
  null
)
on conflict (slug) do update set
  title = excluded.title,
  subtitle = excluded.subtitle,
  card_type = excluded.card_type,
  category = excluded.category,
  life_stage = excluded.life_stage,
  start_age_days = excluded.start_age_days,
  end_age_days = excluded.end_age_days,
  pregnancy_week_start = excluded.pregnancy_week_start,
  pregnancy_week_end = excluded.pregnancy_week_end,
  priority = excluded.priority,
  short_summary = excluded.short_summary,
  wish_i_knew = excluded.wish_i_knew,
  what_to_do_now = excluded.what_to_do_now,
  source_notes = excluded.source_notes,
  conditions = excluded.conditions,
  illustration_prompt = excluded.illustration_prompt,
  image_alt = excluded.image_alt,
  image_style = excluded.image_style,
  -- Keep existing image_url, image_status, status, published_at on re-seed.
  updated_at = now();

